### ISSUE TITLE
Can't import torchtext experimental dataset Multi30K [Translation]

### ISSUE THREAD

**Issue by sidwa** [pytorch/text#1041]
## 🐛 Bug
**Describe the bug**
Trying to import torchtext experimental dataset yields import error

**To Reproduce**
```
from torchtext.experimental.datasets import Multi30K
```
Based on #1038 it looks like currently the documentation shows the wrong import statement which is why I have used the one shown above.

**Expected behavior**
no output, successful import

**Environment**

PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home
GCC version: (GCC) 7.4.0
Clang version: Could not collect
CMake version: version 3.12.4

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.17.2
[pip3] numpydoc==0.9.1
[pip3] torch==1.6.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.6.0
[pip3] torchvision==0.7.0
[conda] Could not collect

**Additional context**

**Comment by zhangguanheng66** [comment]
Is this the same issue due to the wrong doc strings in #1038. We have CI test to cover the Multi30K dataset https://github.com/pytorch/text/blob/0ffbfb3b55a08132f40cb7ec6d7c9c75dbf908fe/test/data/test_builtin_datasets.py#L162
```
from torchtext.experimental.datasets import Multi30K
```

**Comment by sidwa** [comment]
@zhangguanheng66 Is there something else I have to do or was that for the rest of the team? 😅

**Comment by zhangguanheng66** [comment]
> @zhangguanheng66 Is there something else I have to do or was that for the rest of the team? 😅

I don't quite understand. You should be able to import `Multi30k` dataset by using

```
from torchtext.experimental.datasets import Multi30k 
```

**Comment by sidwa** [comment]
> from torchtext.experimental.datasets import Multi30k

Ohh I see, you aren't able to replicate it? I'll reinstall torch and torchtext and give you an update.

**Comment by sidwa** [comment]
> 
> 
> > @zhangguanheng66 Is there something else I have to do or was that for the rest of the team? 😅
> 
> I don't quite understand. You should be able to import `Multi30k` dataset by using
> 
> ```
> from torchtext.experimental.datasets import Multi30k 
> ```
> 
> You should call `Multi30k`, not `Multi30K`.

I created a conda environment and installed torch and torchtext. Still getting the same error.

**Environment**
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home
GCC version: (GCC) 7.4.0
Clang version: Could not collect
CMake version: version 3.12.4

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.6.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.6.0
[pip3] torchvision==0.7.0
[conda] blas                      2.16                        mkl    conda-forge
[conda] cudatoolkit               10.2.89              h74a9793_1
[conda] libblas                   3.8.0                    16_mkl    conda-forge
[conda] libcblas                  3.8.0                    16_mkl    conda-forge
[conda] liblapack                 3.8.0                    16_mkl    conda-forge
[conda] liblapacke                3.8.0                    16_mkl    conda-forge
[conda] mkl                       2020.1                      216
[conda] numpy                     1.19.2           py37h7cee19a_1    conda-forge
[conda] pytorch                   1.6.0           py3.7_cuda102_cudnn7_0    pytorch
[conda] torchtext                 0.7.0                      py37    pytorch
[conda] torchvision               0.7.0                py37_cu102    pytorch

**Comment by zhangguanheng66** [comment]
I saw you install two torchtext, one for 0.6.0 and another one for 0.7.0. Please double check the package and make sure it's 0.7.0 because the experimental Multi30k dataset is in 0.7.0 release.

**Comment by sidwa** [comment]
Ohh my god. My bad it's working now. The torchtext version was the issue. Thanks alot
