### ISSUE TITLE
How to get the original sentences from train_iter object?

### ISSUE THREAD

**Issue by sunyangfu** [pytorch/text#1045]
## ❓ Questions and Help

**Description**
Is there a easy way to print out the original input sentences instead of tensor objects? For example:

```
def eval(data_iter, model, args):
    model.eval()
    corrects, avg_loss = 0, 0
    for batch in data_iter:
        feature, target = batch.text, batch.label
        print (feature.original_sentence)
```

**Comment by zhangguanheng66** [comment]
Do you mean the raw data strings? We have several iterators for the raw text strings in `torchtext.experimental.datasets.raw`.

**Comment by sunyangfu** [comment]
Yes this could work. I also figured to use index to get the string out. Thanks!
