### ISSUE TITLE
pip install torchtext==0.7.0 installs incompatible PyTorch 1.7.0

### ISSUE THREAD

**Issue by da03** [pytorch/text#1063]
## 🐛 Bug
**Describe the bug**
Recently, after I do `pip install torchtext==0.7.0`, import torchtext would cause segmentation fault. I found that degrading pytorch to 1.6.0 fixes this issue. 

**To Reproduce**
1. `pip install torchtext==0.7.0` (assuming that pytorch is not installed yet, and this command will install the latest pytorch)
2. python -c "import torchtext"

**Expected behavior**
Segmentation Fault

**Environment**

 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): Linux/MacOS
 - Python: 3.8.3

**Comment by zhangguanheng66** [comment]
Yup. That's expected. Since we add cpp extension in torchtext, we have to publish torchtext and pytorch together for compatibility. You should use torchtext=0.8.0 with torch=1.7.0. Any version before 0.7.0 has python only so the compatibility is not an issue. Feel free to re-open the issue if you still have questions.

**Comment by mthrok** [comment]
But, shouldn't `pip install torchtext==0.7.0` install `pytorch==1.6` then?

**Comment by zhangguanheng66** [comment]
> But, shouldn't `pip install torchtext==0.7.0` install `pytorch==1.6` then?

It should but obviously it didn't. If users would like the access to the previous version, please follow the version compatibility on README file of the repo.

**Comment by da03** [comment]
> > But, shouldn't `pip install torchtext==0.7.0` install `pytorch==1.6` then?
> 
> It should but obviously it didn't. If users would like the access to the previous version, please follow the version compatibility on README file of the repo.

Is it possible for you to fix this such that `pip install torchtext==0.7.0` automatically installs `pytorch==1.6` ? torchtext 0.7.0 was released only **a few months ago** and lots of users are still using that due to the overhaul of code in later versions (such as the retiring of `Field` and `Batch`).

**Comment by zhangguanheng66** [comment]
cc @seemethere

**Comment by mthrok** [comment]
cc @seemethere

**Comment by seemethere** [comment]
Yup looks like this is a real bug, we don't actually set a specific torch version in the setup.py

https://github.com/pytorch/text/blob/v0.8.0-rc2/setup.py#L85

**Comment by zhangguanheng66** [comment]
Since this will be addressed in the next release to fix the torch/torchtext version.
