### ISSUE TITLE
> > But, shouldn't `pip install torchtext==0.7.0` install `pytorch==1.6` then?

### ISSUE THREAD

**Issue by da03** [pytorch/text#1066]
I cannot reopen my issue so have to create a new issue here. What I want is to let `pip install torchtext==0.7.0` automatically install `pytorch==1.6`. It'd be great if you can fix this (doesn't sound too hard) because we are using `torchtext 0.7.0` (which was only released a few months ago) in a class and this caused lots of troubles for my students.

> > But, shouldn't `pip install torchtext==0.7.0` install `pytorch==1.6` then?
> 
> It should but obviously it didn't. If users would like the access to the previous version, please follow the version compatibility on README file of the repo.

Is it possible for you to fix this such that `pip install torchtext==0.7.0` automatically installs `pytorch==1.6` ? torchtext 0.7.0 was released only **a few months ago** and lots of users are still using that due to the overhaul of code in later versions (such as the retiring of `Field` and `Batch`).

_Originally posted by @da03 in https://github.com/pytorch/text/issues/1063#issuecomment-721189948_

**Comment by zhangguanheng66** [comment]
Just re-open the early issue. Maybe we can keep them together for easy tracking.

**Comment by mthrok** [comment]
Closing the issue in favor of #1063
