### ISSUE TITLE
is pytorch1.8 supported ?

### ISSUE THREAD

**Issue by wellhowtosay** [pytorch/text#1070]
(base) lujia@baolj:~/torchtext$ python -c "import torchtext"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lujia/torchtext/torchtext/__init__.py", line 6, in <module>
    from . import experimental
  File "/home/lujia/torchtext/torchtext/experimental/__init__.py", line 2, in <module>
    from . import transforms
  File "/home/lujia/torchtext/torchtext/experimental/transforms.py", line 4, in <module>
    from torchtext._torchtext import RegexTokenizer as RegexTokenizerPybind
ModuleNotFoundError: No module named 'torchtext._torchtext'

1. pytorch build from source
2. torchtext build from source using the commands in https://github.com/pytorch/text

**Environment**

Collecting environment information...
PyTorch version: 1.8.0a0+2caa3bd
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.18.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 3090
Nvidia driver version: 455.32.00
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.8.0a0
[pip3] torchtext==0.9.0a0+97e6d1d
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               11.0.221             h6bb024c_0    defaults
[conda] mkl                       2020.2                      256    defaults
[conda] mkl-include               2020.2                      256    defaults
[conda] mkl-service               2.3.0            py38he904b0f_0    defaults
[conda] mkl_fft                   1.2.0            py38h23d657b_0    defaults
[conda] mkl_random                1.1.1            py38h0573a6f_0    defaults
[conda] numpy                     1.19.2           py38h54aff64_0    defaults
[conda] numpy-base                1.19.2           py38hfa32c7d_0    defaults
[conda] torch                     1.8.0a0                   dev_0    <develop>
[conda] torchtext                 0.9.0a0+97e6d1d          pypi_0    pypi

**Comment by zhangguanheng66** [comment]
If you build the packages successfully, try to load torchtext not from the folder `/text`.

**Comment by wellhowtosay** [comment]
> If you build the packages successfully, try to import torchtext not from your local folder `~/torchtext`.

sorry, my fault
