### ISSUE TITLE
python2 iterator bug?

### ISSUE THREAD

**Issue by tombosc** [pytorch/text#109]
here is the snippet:

```
from __future__ import print_function
from torchtext.datasets import WikiText2

i_train, i_dev, i_test = WikiText2.iters(device='-1', root="data/")
for i in i_train:
    print(i)
```

here's the error:
```
Traceback (most recent call last):
  File "bug.py", line 5, in <module>
    for i in i_train:
  File "/u/bosctom/.local/lib/python2.7/site-packages/torchtext/data/iterator.py", line 218, in __iter__
    self.batch_size - len(text)))
TypeError: can't multiply sequence by non-int of type 'float'
```

The bug is related to python2's math.ceil() returning a float?

**Comment by nelson-liu** [comment]
what version of torchtext are you using? A git hash would be nice, if you have one (or did you install from pip)? I get a different error related to the `WikiText2` dataset not being updated to use the latest Vocab API on Python 2 and 3.

**Comment by tombosc** [comment]
I got that error using the pip version: 0.1.1

**Comment by nelson-liu** [comment]
yes, you're right --- there needs to be an `int` call at https://github.com/pytorch/text/blob/0634892b91bbac24c15b2d75147f2c47b24fd0dd/torchtext/data/iterator.py#L220. Would you be willing to create a PR, or should i go ahead?
