### ISSUE TITLE
No module named 'torchtext._torchtext'

### ISSUE THREAD

**Issue by lbq8942** [pytorch/text#1092]
## 🐛 Bug
**Describe the bug**
in transforms.py:
from torchtext._torchtext import RegexTokenizer as RegexTokenizerPybind

but there is no package named "torchtext._torchtest"
so when i import torchtext,error occured as follows,ModuleNotFoundError: No module named 'torchtext._torchtext'

**Comment by zhangguanheng66** [comment]
If you build torchtext from source code, you will get this error message if you try to load the library from `text` directory. Try it again outside the `text` directory.

**Comment by lbq8942** [comment]
i am sorry to bother you again,it still does not work!

when i type "import text.torchtext",i get the following.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-8-3e4802f7a097> in <module>
----> 1 import text.torchtext

~\pythoncode\text\torchtext\__init__.py in <module>
----> 1 from . import data
      2 from . import nn
      3 from . import datasets
      4 from . import utils
      5 from . import vocab

~\pythoncode\text\torchtext\data\__init__.py in <module>
      5 from .iterator import (batch, BucketIterator, Iterator, BPTTIterator,
      6                        pool)
----> 7 from .metrics import bleu_score
      8 from .pipeline import Pipeline
      9 from .utils import get_tokenizer, interleave_keys

~\pythoncode\text\torchtext\data\metrics.py in <module>
      2 import collections
      3 import torch
----> 4 from torchtext.data.utils import ngrams_iterator
      5 
      6 

ModuleNotFoundError: No module named 'torchtext

in addtion,i put the library "text" into the same directory of my python code,is that right?

**Comment by zhangguanheng66** [comment]
As long as you are not in the directory which contains `torchtext`.

**Comment by zhangguanheng66** [comment]
@lbq8942 Do you still see this error? Feel free to re-open the issue if you still have questions.
