### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by eriche2016** [pytorch/text#11]
I have installed this package in my machine with python 2.7, however, when i import it, it gives me error:
```
Segmentation fault (core dumped)
```

**Comment by eriche2016** [comment]
can anyone fix it?

**Comment by eriche2016** [comment]
hi, i find that the bug comes from [this line](https://github.com/pytorch/text/blob/master/torchtext/datasets/__init__.py#L4), maybe this dataset is too big?? , because if i remove this line, everything is okay.

**Comment by eriche2016** [comment]
I find that removing [this line]https://github.com/pytorch/text/blob/master/torchtext/datasets/sentiment.py#L1 can solve my problem

**Comment by eriche2016** [comment]
hi. Unfortunately, sometimes i still cannot import this module even if i remove the above lines.  can you fix this.

**Comment by soumith** [comment]
if the segfault come from importing nltk, have you tried reinstalling nltk package?

**Comment by eriche2016** [comment]
yes, and currently my nltk version is  nltk-3.2.2, but still gives:
```
Segmentation fault (core dumped)
```

**Comment by eriche2016** [comment]
Also, when i import nltk separately, it is okay. However, when  ```import torchtext``` , it gives the above segmentation error.

**Comment by elyase** [comment]
did you try 

`import nltk`

or:

`from nltk.tree import Tree`?

**Comment by eriche2016** [comment]
@elyase  Yes. And both are okay on my machine.  but only when i import this package, it output ```segmenation fault``
```
>>> import torchtext
Segmentation fault (core dumped)
```

```
>>> import nltk
>>> from nltk.tree import Tree
```

**Comment by soumith** [comment]
can you run it in gdb?
then you can know where the segfault is happening.

**Comment by eriche2016** [comment]
Hi, all. I find that when importing this package, i have to ```import nltk``` in advance. Otherwise,  it gives me error, for example, 
```
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import nltk
>>> import torchtext
>>>
```
is it a bug in this repository
below is the error code: 
```
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import torchtext
Segmentation fault (core dumped)

```

**Comment by elyase** [comment]
There was a thread where importing tensorflow first would cause scipy to crash while importing scipy first and then tensorflow was ok. IIRC the solution was to reinstall scipy.

**Comment by eriche2016** [comment]
@soumith , @elyase  Thank you very much.  reinstalling scipy solves my problem.

**Comment by rajan-blackboxes** [comment]
Rather than installing from `pip install torchtext` upgrading and installing latest torchtext helped to solve this problem.
`$ pip install --upgrade git+https://github.com/pytorch/text`
