### ISSUE TITLE
infinite loop when testing for membership in Vocab

### ISSUE THREAD

**Issue by gchaperon** [pytorch/text#1107]
## 🐛 Bug
**Describe the bug**
membership test is broken on Vocab when the value is not in Vocab

**To Reproduce**
```python
import string
from collections import Counter
from torchtext.vocab import Vocab

vocab = Vocab(Counter(string.ascii_lowercase))
"not in vocab" in vocab
```
this snipet hangs indefinitely

**Expected behavior**
to return `False`

**Environment**

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.8

**Additional context**
So, I know it is not documented, but since Vocab does implement `__getitem__`, and it is (kind of) a proxy for `self.stoi` I would expect that membership test to work in the same way.
By the way, why this happens is documented here https://docs.python.org/3/reference/expressions.html#membership-test-operations. When a class does not define `__contains__` but does define `__getitem__`, all integers are tested to see if there is one that returns the value, and python expects `IndexError` to know when it is not contained. Since `Vocab.__getitem__` always returns this never happens. This also makes `0 in vocab` return `True`, even though it doesn't appear in the vocab.

I would be glad to submit a PR.

**Comment by zhangguanheng66** [comment]
Could you test it on the one in `torchtext/experimental` folder. Very likely it has the similar behavior and we can accept a PR to add `__contains__` func.
