### ISSUE TITLE
why is Vocab.__getitem__ slightly different than just using stoi?

### ISSUE THREAD

**Issue by gchaperon** [pytorch/text#1108]
## ❓ Questions and Help

**Description**

Hi! I was looking at the source code and realized that the implementation of [`Vocab.__getitem__`](https://github.com/pytorch/text/blob/v0.8.1/torchtext/vocab.py#L106) is slightly different than just retrieving the value from `stoi`.

This produces and inconsistency when the vocabulary doesn't contain the `<unk>` token.
```python
from torchtext.vocab import Vocab
from collections import Counter

vocab = Vocab(Counter("abc"), specials=tuple())
print(vocab["not in vocab"]) # returns None
print(vocab.stoi["not in vocab"])  # raises KeyError (expected)
```

I am new to the project so maybe there is a reason I don't know of, but it seems to me that both ways should be consistent.
Cheers!

**Comment by zhangguanheng66** [comment]
Could you try the one in `torchtext.experimental`. We are going to retire the vocab in the root folder.

**Comment by orangetwo** [comment]
Took a look at this function
`    def __getitem__(self, token):
        return self.stoi.get(token, self.stoi.get(Vocab.UNK))
`
then you will the idea.
