### ISSUE TITLE
Current ns_task code does not work with current form of WikiText103

### ISSUE THREAD

**Issue by knagrecha** [pytorch/text#1123]
The process_raw_data function (as the name suggests) seems to want to take in raw string data - however the current form of WikiText103 in experimental returns an already processed, tokenized format which raises errors when running the code.

Errors tend to be the tensor size/shape - attempting to get len() of a 0-d tensor.

Perhaps this is being addressed in the new experimental.datasets.raw folder? Let me know if I should update my code to use that instead of experimental.datasets.

**Comment by knagrecha** [comment]
Just downloaded the latest code from this repo (rather than the pip-version), and with the "raw" dataset backend for the LM datasets, it works. Problem earlier was the stable code returns scalar tensors rather than sequences.

**Comment by zhangguanheng66** [comment]
Happy to see the raw dataset helps
