### ISSUE TITLE
The optimal way to save and load TEXT.vocab 

### ISSUE THREAD

**Issue by aimanmutasem** [pytorch/text#1168]
## ❓ Questions and Help

**Description**

Dear @all

Problem:
I have three datasets for NMT task each one has a different length of vocabulary.

Solution:
The proposed solution is to build the vocabulary using the three datasets, as follow:

```
DE.build_vocab(train_data_1, train_data_2, train_data_3, min_freq=MIN_COUNT)
EN.build_vocab(train_data_1, train_data_2, train_data_3, min_freq=MIN_COUNT)
```

The challenge of this method is to load the three datasets each time I need to use one of them. The best way is to save the `TEXT.vocab` once and then loaded each time that I need to use one of these datasets.

I have found some methods online to do that but it is not effective，which doesn’t take all vector variables `freqs`, `stoi`, and `itos`.

Question:
What is the optimal way to save and load `TEXT.vocab` taking into account all vector variables?

Kind regards,
Aiman Solyman

**Comment by zhangguanheng66** [comment]
This is related to the legacy code, like `Field` class, which will be retired soon. For your questions, you can try the prototype vocab, `torchtext.experimental.vocab`, and pass an iterator to [build_vocab_from_iterator](https://github.com/pytorch/text/blob/master/torchtext/experimental/vocab.py#L84) to handle multiple files.

**Comment by aimanmutasem** [comment]
@zhangguanheng66 

Thank you sir for your response, I appreciate  :) 

I have tried to implement your method but I'm a little confused about the implementation. I expect to use the final output as `EN.vocab.stoi[EN.pad_token]`. Could you explain your idea in a few lines of code? 

I have tried to implement it as follow: 

```
def save_vocab(vocab, path):
    with open(path, 'w+') as f:     
        for token, index in vocab.stoi.items():
            f.write(f'{index}\t{token}\n')
```

Then 

```
def read_vocab(path):
    vocab = dict()
    with open(path, 'r') as f:
        for line in f:
            index, token = line.split('\t')
            vocab[token] = int(index)
    return vocab
```

**Comment by zhangguanheng66** [comment]
With `torchtext.experimental.vocab`, you can use `torch.save()` and `torch.load()`. See this [example](https://github.com/pytorch/text/blob/master/test/experimental/test_vocab.py#L206-L207).

**Comment by aimanmutasem** [comment]
Thank you sir its worked for me :) 

```
src_1000_ltr = os.path.join('src_1000_ltr.pt')
trg_1000_ltr = os.path.join('trg_1000_ltr.pt')
torch.save(SRC.vocab, src_1000_ltr)
torch.save(TRG.vocab, trg_1000_ltr)
```

Then loaded as : 

```
SRC= torch.load(src_1000_ltr)
TRG= torch.load(trg_1000_ltr)
```

I used as : 

`TRG.stoi[TRG.unk_token]`

but small problem comes here, I can't called as **TRG.vocab.stoi[x]** , which make the below issue, could you help sir ? 


```
~/anaconda3/lib/python3.6/site-packages/torchtext/data/field.py in <listcomp>(.0)
    334         if self.use_vocab:
    335             if self.sequential:
--> 336                 arr = [[self.vocab.stoi[x] for x in ex] for ex in arr]
    337             else:
    338                 arr = [self.vocab.stoi[x] for x in arr]

AttributeError: 'Field' object has no attribute 'vocab'
```

**Comment by zhangguanheng66** [comment]
Should you 
```
SRC.vocab = torch.load(src_1000_ltr)
```
?

**Comment by aimanmutasem** [comment]
This issue embarrassed me very much, I tried the same `SRC.vocab` before and didn't work, but it works well. Thank you sir so much I appreciate your kind support.
