### ISSUE TITLE
Looking for an example on how to use BucketIterator with a transformer model?

### ISSUE THREAD

**Issue by sorenwacker** [pytorch/text#1193]
I would appreciate an end-to-end example. The examples that I found stop with the BucketIterator. It is unclear what to do with it.

**Comment by zhangguanheng66** [comment]
Transformer is a model while `BucketIterator` or `Iterator` batches data. So in theory, users should be able to choose whatever they prefer to combine. Nevertheless, `BucketIterator` has been retired to the legacy folder (officially in v0.9.0 release).

A simple way to have `BucketIterator` func is to sort the processed data by lengths
