### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by dasguptar** [pytorch/text#12]
I did a `git clone` of this repo, ran `python setup.py install`, and then when I try to do a simple `import torchtext`, I keep getting a segmentation fault.
Based on the comments from #11 , I tried re-installing all relevant package dependencies, such as `numpy`, `scipy`, `nltk`, but the error persists. As observed in the referenced issue, I have also tried the following which works fine:
```
import nltk (even numpy or scipy or matplotlib here works just fine)
import torchtext
```
Further, as suggested by @soumith in the other thread, I tried using `gdb`, which gives me the following point where the segfault is actually happening:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffdfeb7fc0 in PyArray_API () from /home/riddhiman/.local/lib/python2.7/site-packages/numpy/core/multiarray.so
```
Any pointers as to why this is happening, and how to resolve this issue? For now, I am using the workaround of importing numpy and then importing torchtext, but it would be nice to know the real cause.

**Comment by apaszke** [comment]
It's the same problem as with scipy. For some reason they initialize numpy in a way such that it segfaults if we've initialized it already. We're going to look into that soon.

**Comment by apaszke** [comment]
And I think it's best to keep only a single issue in PyTorch repo, so I'll close that for now. Thanks!

**Comment by dasguptar** [comment]
Yeah, I only created a new issue because I didn't know if commenting on the old one was the right thing to do or not. Apologies. :smile:
