### ISSUE TITLE
Unable to build from source torchtext on google Collab 

### ISSUE THREAD

**Issue by StephennFernandes** [pytorch/text#1215]
unable to build from source in the google colab  

on running the cmd  `python setup.py clean install`
gives this error 

`error: command 'x86_64-linux-gnu-gcc' failed with exit status`

tried with without GPU, TPU and CPU Runtime

**Comment by zhangguanheng66** [comment]
You can always install the nightly release on Google Collab, and the nightly release was generated daily based on the master branch.

I think some people use `pip install` to build torchtext from source but I haven't tried.

**Comment by StephennFernandes** [comment]
i did try installing the nightly release in collab via the cmd :
`pip install --pre torch torchtext -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html`

but i says requirements already satisfied 
and i get the same old 0.3 torchtext by default in collab

**Comment by zhangguanheng66** [comment]
You can add the version like this
```
!pip install --pre torchtext==0.9.0.dev20210212 -f https://download.pytorch.org/whl/nightly/cu101/torch_nightly.html
```

**Comment by parmeet** [comment]
Google colab now have the latest version installed (0.12). Also the nightly installed instructions seems working fine. Feel free to re-open if the issue reappears.
