### ISSUE TITLE
how to load data using TabularDataset and the new nightly torchtext experimental dataloader

### ISSUE THREAD

**Issue by StephennFernandes** [pytorch/text#1218]
the `torchtext.data.TabularDataset` returns an iterable of objects that cannot further be split into batches, or (x,y) sets of values. making it impossible to use the new `torchtext.vocab.Vocab` to build vocab using `Counter` 

**my use-case code:**
tokenize = lambda x:x.split(" ")

konkani = Field(sequential=True, tokenize=tokenize, init_token='<sos>', eos_token='<eos>')

hindi = Field(sequential=True, tokenize=tokenize, init_token='<sos>', eos_token='<eos>')

fields = [("word_token_konkani", konkani), ('word_token_hindi', hindi)]

train_data, test_data = TabularDataset.splits(path="translation/", train="train.csv",
                                              test="test.csv", format="csv", fields=fields)

i was trying to refer the migration tutorials here : [link](https://github.com/pytorch/text/blob/master/examples/legacy_tutorial/migration_tutorial.ipynb)

**Comment by zhangguanheng66** [comment]
Currently, we don't have the utility functions to directly process the tabular data in a file. However, creating an iterator to yield the tabular data is quite straightforward. Here are a few examples:

- a `csv` file: [AG_NEWS](https://github.com/pytorch/text/blob/master/torchtext/datasets/ag_news.py#L27-L31)
- a `json` file: [SQuAD1](https://github.com/pytorch/text/blob/master/torchtext/datasets/squad1.py#L23-L36)

Eventually, we can provide those utility functions to users directly and simply our code as well.

**Comment by StephennFernandes** [comment]
@zhangguanheng66 thanks a ton for all the help.
