### ISSUE TITLE
Field containing list of characters for each word

### ISSUE THREAD

**Issue by sriniiyer** [pytorch/text#124]
Hi,

For every example, I want to store a (#words, max_char_size) tensor, containing characters in each word in the sequence. Is there a way to do this currently using Field ? I think right now, numericalize expect a single list and doesn't allow a list of lists.

Thanks!

**Comment by nelson-liu** [comment]
Yeah, I think you're right in that you can't do this with the current Field. Supporting more than basic tokenization shouldn't be too difficult though, and is definitely a good feature to have.

**Comment by sriniiyer** [comment]
cool thanks. Gonna hack something up in Batch and Field to do it for now.

**Comment by kmkurn** [comment]
There is a `SubwordField` implemented that might be able to achieve this but I am not sure. I also need this and currently I just make my own custom field. Maybe @jekbradbury can help?

**Comment by jekbradbury** [comment]
SubwordField is for subword-splitting tokenizers that still result in a flat list of tokens (at the subword rather than word level) so I think you'd have to make your own custom field for now.

**Comment by kmkurn** [comment]
@jekbradbury I see. Would you be interested in a PR for such a field?

**Comment by jekbradbury** [comment]
Sure!
