### ISSUE TITLE
TranslationDataset defined in datasets torch is taking too long to load

### ISSUE THREAD

**Issue by mohitvaidya** [pytorch/text#1242]
## ❓ Questions and Help

**I am trying to load my translation data(txt files, separated by lines) with torchtext [TranslationDataset](https://github.com/pytorch/text/blob/0.4.0/torchtext/datasets/translation.py) , It usually takes more than 20-25 minutes even to load smaller datasets(10k lines). Is there a way around to make data loading faster ?**
Snippet of the code:
`datasets.TranslationDataset(
     path='./data_torch/data', exts=('.hi', '.en'),
     fields=(hindi, english))`

**Comment by zhangguanheng66** [comment]
We just release torchtext 0.9.0 and those legacy datasets have been moved to `torchtext.legacy`. Please give a try on the new datasets, which currently are only IWSLT2016 and IWSLT2017. The other two translation datasets are available in the nightly release.

**Comment by parmeet** [comment]
In addition, we are working on new API for [TranslationDataset](https://github.com/pytorch/text/blob/408c4cfad9f2ec68c2d462326867787df2dba307/torchtext/experimental/datasets/translation.py#L87) that could help with this use case.

**Comment by mohitvaidya** [comment]
I am closing this issue, since it has more to do with pre-processing implementation, Thanks for support @zhangguanheng66
