### ISSUE TITLE
Tags clean-up or not in IWSLT2016 and IWSLT2017 translation datasets

### ISSUE THREAD

**Issue by parmeet** [pytorch/text#1249]
torchtext provides [iterables](https://github.com/pytorch/text/blob/6d8d50bece1f4e7023d778b1b5b23bb02f2f0f02/torchtext/data/datasets_utils.py#L279) to [IWSLT2016](https://github.com/pytorch/text/blob/6d8d50bece1f4e7023d778b1b5b23bb02f2f0f02/torchtext/datasets/iwslt2016.py#L148) and [IWLST2017](https://github.com/pytorch/text/blob/6d8d50bece1f4e7023d778b1b5b23bb02f2f0f02/torchtext/datasets/iwslt2017.py#L120) translation datasets. In the process it clean up all the tags using the functions [_clean_xml_file](https://github.com/pytorch/text/blob/6d8d50bece1f4e7023d778b1b5b23bb02f2f0f02/torchtext/data/datasets_utils.py#L21) and [_clean_tags_file](https://github.com/pytorch/text/blob/6d8d50bece1f4e7023d778b1b5b23bb02f2f0f02/torchtext/data/datasets_utils.py#L30) and provide clean data-pointers that contains the raw sentences in source and target language. This is neat, because it give user direct access to the underlying training/evaluations sets, but at the same time devoid user from accessing any tags that might be relevant for downstream tasks. 

We would like to understand:
- If there are relevant use-cases for returning tags 
- If answer is yes, what are some examples of preferred format for returning the tag information

cc: @cpuhrsch @zhangguanheng66

**Comment by parmeet** [comment]
This issue is on similar lines with how we should provide capability to pre-process EnWik9 dataset (https://github.com/pytorch/text/issues/1272) without removing original tags if that what really user wants. We solved this by implementing pre-processing as a functional (https://github.com/pytorch/text/pull/1292). 

I wonder if we should also make [_clean_xml_file](https://github.com/pytorch/text/blob/6d8d50bece1f4e7023d778b1b5b23bb02f2f0f02/torchtext/data/datasets_utils.py#L21) and [_clean_tags_file](https://github.com/pytorch/text/blob/6d8d50bece1f4e7023d778b1b5b23bb02f2f0f02/torchtext/data/datasets_utils.py#L30) as functionals, and provide raw IWSLT2016 and IWLST2017 datasets without removing tags? This way if user really wants the clean data, she could really just apply the functional. wdyt @cpuhrsch ?

**Comment by cpuhrsch** [comment]
It would certainly be more consistent and flexible, since it allows direct access to the raw data and then allows to layer these filters on top.

**Comment by parmeet** [comment]
Closing this issue as the dataset is already implemented.
