### ISSUE TITLE
what is the purpose of this project?

### ISSUE THREAD

**Issue by rabintang** [pytorch/text#125]
pytorch has offered utils.data.dataset, and what is the purpose of torchtext?
what features do torchtext support?

**Comment by nelson-liu** [comment]
torchtext is specifically tailored toward text data, with NLP applications in mind. We haven't quite had a chance to build docs yet for the project, but there are a few example usages in the README + we have prebuilt data loaders for several common datasets.

**Comment by marikgoldstein** [comment]
Meanwhile, I found the test directory to be a great source of examples as well
