### ISSUE TITLE
I can't install the torchtext==0.8.1

### ISSUE THREAD

**Issue by sangwz** [pytorch/text#1268]
I failed installing  the torchtext by the command "pip install torchtext==0.8.1" ,told me can't found the satisfied file. I am also failed by "pip install torchxxx.zip". How should I do?

The torchtext==0.6.1 can also setup by pip install.

**Comment by zhangguanheng66** [comment]
cc @seemethere

**Comment by cpuhrsch** [comment]
The Bug report issue template mentions the following instructions to help us help you best.
"""
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/text/master/torchtext/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
python -c "import torchtext; print(\"torchtext version is \", torchtext.__version__)"
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

"""

**Comment by sangwz** [comment]
There is my environment:
* Torch Version: 1.7.1
* Win10
* Conda installed PyTorch
* command : Pip install torchtext==0.8.1 & conda install torchtext=0.8.1
* python Version: 3.8.5
* Cuda: 10.1
* Gpu: 1660s

**Comment by chngdickson** [comment]
Am currently facing the same issue. How were u able to solve it?

**Comment by Rain-Main** [comment]
I am sorry that I notice your comment just now. It is too long to solve the issue, I forget the method to solve it. maybe I tried another version that I can install. I am not clearly sure.

**Comment by mahmudhasankhan** [comment]
@chngdickson hey man, if you'd like to install this exact package using conda you can do that by,

```
conda install -c pytorch torchtext=0.8.1
```

I also tried using pip, it didn't work. Then I tried conda but that didn't work either. Then I figured out that I have to mention the pytorch channel.
