### ISSUE TITLE
ImportError: cannot import name 'Field' from 'torchtext.data'

### ISSUE THREAD

**Issue by UdbhavPrasad072300** [pytorch/text#1274]
## 📚 Documentation

**Description**

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-13-c35a13515335> in <module>
      6 import torchtext
      7 from torchtext.vocab import Vocab
----> 8 from torchtext.data import Field, BucketIterator, TabularDataset
      9 
     10 from torchsummary import summary

ImportError: cannot import name 'Field' from 'torchtext.data' (C:\Users\udbha\anaconda3\lib\site-packages\torchtext\data\__init__.py)
```

I get an error when trying to import Field like this, I'm using the latest torchtext (0.9.1)

```
from torchtext.data import Field
```

Thank you.

**Comment by parmeet** [comment]
These primitives are retired and moved to legacy folder in the latest release (torchtext >= 0.9.0). Please refer to [release notes](https://github.com/pytorch/text/releases/tag/v0.9.0-rc5). Also you may find [migration guide](https://github.com/pytorch/text/blob/master/examples/legacy_tutorial/migration_tutorial.ipynb) useful.

**Comment by UdbhavPrasad072300** [comment]
Oh, I didn't notice that; Thank you for your help!

**Comment by hemangjoshi37a** [comment]
what is the latest equivalent of `TabularDataset` , `Field` and `BucketIterator`? from legacy

**Comment by eslambakr** [comment]
@hemangjoshi37a 
Just add legacy.
For instance:
from torchtext.data import Field, BucketIterator
becomes:
from torchtext.legacy.data import Field, BucketIterator

**Comment by Mohesh-B** [comment]
no module named torchtext.legacy is coming as an error

**Comment by toshk9** [comment]
> 

the same error

**Comment by yahya010** [comment]
same here, can't find it

**Comment by vaishn99** [comment]
Same issue here

**Comment by robinshie** [comment]
Same +1

**Comment by a2d8a4v** [comment]
The same here

**Comment by averagestud** [comment]
Use !pip install torchtext==0.6
and restart runtime 
then use
from torchtext.data import Field, BucketIterator

**Comment by kabyanil** [comment]
This is still an issue. Downgraded to 0.6 for now.

**Comment by Smitha-4** [comment]
The same error

**Comment by cfz1998** [comment]
How to fix it？

**Comment by GirijaVusal** [comment]
Downgrade your  numpy to pip install numpy==1.26.4
and install pip install torchtext==0.6.0
