### ISSUE TITLE
SSL certificate verification issue when running translation tests

### ISSUE THREAD

**Issue by jfsantos** [pytorch/text#132]
I am getting the following message when I try to run the tests related to machine translation: `urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)`. This is on Python 3. The same does not happen on Python 2 (although then there's an issue regarding encoding which seems to be already covered in #131).

**Comment by jekbradbury** [comment]
I haven't seen this locally, but please reopen if it's still an issue.
