### ISSUE TITLE
ImportError undefined symbol: _ZNK3c104Type14isSubtypeOfExtERKSt10shared_ptrIS0_EPSo

### ISSUE THREAD

**Issue by AK391** [pytorch/text#1342]
getting this error recently

ImportError: /home/user/miniconda/lib/python3.8/site-packages/torchtext/_torchtext.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtERKSt10shared_ptrIS0_EPSo

**Comment by parmeet** [comment]
Hi @AK391 Thanks for raising this issue. In order to better understand the problem, could you please try to provide info using this [template](https://github.com/pytorch/text/issues/new?assignees=&labels=&template=bug-report.md) ?

**Comment by AK391** [comment]
this is part of the stacktrace
<img width="1306" alt="Screen Shot 2021-06-25 at 11 34 19 PM" src="https://user-images.githubusercontent.com/81195143/123500708-f3e93d00-d60d-11eb-813d-20d030355778.png">

**Comment by parmeet** [comment]
> part

could you please share details of your environment as per the [template](https://github.com/pytorch/text/issues/new?assignees=&labels=&template=bug-report.md?

**Comment by OmegAshEnr01n** [comment]
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.10

Python version: 3.7.9 (default, Aug 31 2020, 12:42:55)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.8.0-59-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1070 Ti
Nvidia driver version: 460.80
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.9.0
[pip3] torchaudio==0.7.0a0+a853dff
[pip3] torchtext==0.10.0
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.0.221             h6bb024c_0  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py37he8ac12f_0  
[conda] mkl_fft                   1.2.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.19.2           py37h54aff64_0  
[conda] numpy-base                1.19.2           py37hfa32c7d_0  
[conda] torch                     1.9.0                    pypi_0    pypi
[conda] torchaudio                0.7.2                      py37    pytorch
[conda] torchtext                 0.10.0                   pypi_0    pypi
[conda] torchvision               0.8.2                py37_cu110    pytorch

**Comment by n8henrie** [comment]
Same error here.

pytorch 1.9.0 in arch linux installed via pytorch-opt-cuda, torchtext 0.1.0 installed via pip

**Comment by Tharunkumar01** [comment]
I'm too facing the same error. Please fix this issue faster.

**Comment by selene57** [comment]
@AK391 why did you close this issue? I'm still running into this error. Do you have a solution?

**Comment by AK391** [comment]
@selene57 sorry reopened

**Comment by kusoboy520** [comment]
i'm facing the same error too.
pytorch 1.10.0
torchtext 0.10.0

**Comment by mthrok** [comment]
torchtext has an extension module written in C++, which is compiled against specific PyTorch binary distribution. This means that torch text requires the matching PyTorch binary distribution.
If installing an official binary distribution of torchtext, please make sure that the combination of pytorch and torchtext is one that is listed in README. https://github.com/pytorch/text#installation

If you are using PyTorch built and maintained by unofficial source, such as pytorch-opt-cuda, torchtext official release is not expected to work. Please ask the maintainers to publish the matching torchtext.

**Comment by parmeet** [comment]
> i'm facing the same error too. pytorch 1.10.0 torchtext 0.10.0

As noted in previous [comment](https://github.com/pytorch/text/issues/1342#issuecomment-993928516) could you please try installing torchtext 0.11.0 which is the compatible version for pytorch 1.10.0?

**Comment by vipermu** [comment]
I had the same error but managed to fix it.

As @parmeet and @mthrok noted, I fixed it by using a compatible `torchtext` and `torch` versions. In my case, `torchtext==0.8.0` and `torch==1.7.1`.

**Comment by parmeet** [comment]
Closing this issue, as the resolution is to use compatible versions.

**Comment by manchandasahil** [comment]
Issue still there with the following : 

pytorch-lightning==1.2.10
pytorch-quantization==2.1.2
torch==1.12.0a0+2c916ef
torch-stft==0.1.4
torch-tensorrt @ file:///opt/pytorch/torch_tensorrt/py/dist/torch_tensorrt-1.1.0a0-cp38-cp38-linux_x86_64.whl
torchmetrics==0.2.0
torchtext==0.12.0

**Comment by amiyalahiri9800** [comment]
> I had the same error but managed to fix it.
> 
> As @parmeet and @mthrok noted, I fixed it by using a compatible `torchtext` and `torch` versions. In my case, `torchtext==0.8.0` and `torch==1.7.1`.

ImportError: cannot import name 'Batch' from 'torchtext.data' (/usr/local/lib/python3.8/dist-packages/torchtext/data/__init__.py)
getting this error .. I have torch==1.7.1 and torchtext==0.8.0

**Comment by Gi-gigi** [comment]
> > I had the same error but managed to fix it.
> > As @parmeet and @mthrok noted, I fixed it by using a compatible `torchtext` and `torch` versions. In my case, `torchtext==0.8.0` and `torch==1.7.1`.
> 
> ImportError: cannot import name 'Batch' from 'torchtext.data' (/usr/local/lib/python3.8/dist-packages/torchtext/data/**init**.py) getting this error .. I have torch==1.7.1 and torchtext==0.8.0

me too

**Comment by Coelodonta** [comment]
Same issue with torch 2.0.1 and torchtext 0.15.2 with Python 3.10, see error below:

OSError: /home/py/annotated/venv/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN5torch6detail10class_baseC2ERKSsS3_SsRKSt9type_infoS6_
