### ISSUE TITLE
Access vocabulary of Pretrained SentencePiece model using SentencePieceProcessor

### ISSUE THREAD

**Issue by anjali-chadha** [pytorch/text#1368]
## ❓ Questions and Help

**Description**
I have a pretrained SentencePiece Tokenizer model "foo.model" which I want to serialize using torchscript.

I am using `sentencepiece_processor` for this purpose as described in the [code documentation](https://github.com/pytorch/text/blob/f7a6fbd3a910c4066b9a748545df388ae5933a6a/torchtext/experimental/transforms.py#L310-L312)

I am interested in accessing vocabulary associated with the "foo.model" SPM model, similar to `get_vocab()` method provided by [HuggingFace's AlbertTokenizer (based on SentencePiece)](https://github.com/huggingface/transformers/blob/master/src/transformers/models/albert/tokenization_albert.py#L177-L180). 

Any suggestions on how can I achieve that using torchtext library?

Thanks!

**Comment by parmeet** [comment]
Hi @anjali-chadha, sentencepiece_processor is nn.module and is a wrapper around the sentencepiece model itself. So you can use public functions in [SentencePiece](https://github.com/pytorch/text/blob/master/torchtext/csrc/sentencepiece.h) class implementation to create the vocabulary. Below is the complete example.

```python
import torchtext
from torchtext.experimental.transforms import PRETRAINED_SP_MODEL, sentencepiece_processor
sp_model_path = torchtext.utils.download_from_url(PRETRAINED_SP_MODEL['text_unigram_25000'])
sp_processor = sentencepiece_processor(sp_model_path)
sp_vocab = {sp_processor.sp_model.IdToPiece(i):i for i in range(sp_processor.sp_model.GetPieceSize())}
```

cc: @hudeven

**Comment by anjali-chadha** [comment]
Thanks @parmeet for detailed explanation. This was helpful.
