### ISSUE TITLE
Can't install torchtext == 0.8.1

### ISSUE THREAD

**Issue by chngdickson** [pytorch/text#1379]
## 🐛 Bug
**Describe the bug**
Unable to install torchtext == 0.8.1 with pip install nor with conda install.

**To Reproduce**
1. pip install torchtext==0.8.1

**Expected behavior**
A matching distribution for torchtext==0.8.1 should be found. and a working **.whl** file for windows.

**Screenshots**
![image](https://user-images.githubusercontent.com/20728313/130208972-d0e914b1-5279-4ac9-8cc4-9fb8b3bab2b9.png)

**Env**
There is my environment:

- Torch Version: 1.7.1
- Win10
- pip install torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
- command : Pip install torchtext==0.8.1 & conda install torchtext=0.8.1
- python Version: 3.8.5
- Cuda: 10.1
- Gpu: 1070

**Comment by lizhixi212** [comment]
maybe there is not torchtext 0.8.1（<0.9）for windows，but linux、macos

**Comment by hudeven** [comment]
@lizhixi212 is right. @chngdickson you may try the latest version 0.10.0 which has pre-built wheels for windows: https://pypi.org/project/torchtext/0.10.0/#files

**Comment by parmeet** [comment]
cc: @seemethere

**Comment by hudeven** [comment]
Please reopen if the issue is not resolved
