### ISSUE TITLE
Publish torchtext 0.9.2 on PyPi

### ISSUE THREAD

**Issue by philipGaudreau** [pytorch/text#1397]
It is not a bug _per se_, but it would be nice if **torchtext** **0.9.2** could be added to the releases, since at the moment, 0.9.1 requires Pytorch 1.8.1, which is not the LTS (1.8.2). 

In other words, at the moment, if I do a `pip install "torchtext<0.10"`, it will install torchtext 0.9.1 and thus pytorch 1.8.1.

**Comment by parmeet** [comment]
cc: @seemethere, @malfet

**Comment by brando90** [comment]
yes please!

**Comment by brando90** [comment]
related: https://stackoverflow.com/questions/69229975/how-does-one-install-torchtext-with-cuda-11-0-and-pytorch-1-9

**Comment by brando90** [comment]
@philipGaudreau 

does this help?

> Thanks @brando90 for raising the issue. Yes, looks like the problem with Conda installation. could you please try with pip using version 0.8.1 (the supported version for 3.9, I will update the readme as well)

pip install torchtext==0.8.1
It seems to be same issue using Conda with audio/vision as well for pytorch version<1.9?

CC: @seemethere

CC: @mthrok, @NicolasHug

**Comment by harishsk** [comment]
Currently the LTS releases are published on the Anaconda `pytorch-lts` channel and the pip packages are published at https://download.pytorch.org/whl/lts/1.8/torch_lts.html.

Torchtext 0.9.2 is also published there. Can you use the installation command lines listed at [Start Locally|Pytorch](https://pytorch.org/get-started/locally/) or is your request to publish the LTS packages on PyPi?

**Comment by philipGaudreau** [comment]
Here is what is happening:

```
$ pip install -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html torch==1.8.2+cu102
Looking in indexes: https://pypi.org/simple
Looking in links: https://download.pytorch.org/whl/lts/1.8/torch_lts.html
Collecting torch==1.8.2+cu102
  Using cached https://download.pytorch.org/whl/lts/1.8/cu102/torch-1.8.2%2Bcu102-cp38-cp38-linux_x86_64.whl (804.1 MB)
Collecting numpy
.
.
.
Installing collected packages: typing-extensions, numpy, torch
Successfully installed numpy-1.21.2 torch-1.8.2+cu102 typing-extensions-3.10.0.2

$  pip freeze
certifi==2021.5.30
numpy==1.21.2
torch==1.8.2+cu102
typing-extensions==3.10.0.2

$  pip install "torchtext<0.10"
Looking in indexes: https://pypi.org/simple
Collecting torchtext<0.10
  Downloading https://<...>/_packaging/<...>/pypi/download/torchtext/0.9.1/torchtext-0.9.1-cp38-cp38-manylinux1_x86_64.whl (7.0 MB)
     |████████████████████████████████| 7.0 MB 3.9 MB/s
Collecting requests
  Downloading https://<...>/_packaging/<...>/pypi/download/requests/2.26/requests-2.26.0-py2.py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 317 kB/s
Collecting torch==1.8.1
  Downloading https://<...>/_packaging/<...>/pypi/download/torch/1.8.1/torch-1.8.1-cp38-cp38-manylinux1_x86_64.whl (804.1 MB)
     |█▉                              | 47.2 MB 3.8 MB/s eta 0:03:18```

**Comment by harishsk** [comment]
The installation instructions need to be fixed on the site. Until then please try the following:
```
pip install -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html torch==1.8.2+cu102 torchtext==0.9.2
```

**Comment by gkowarzyk** [comment]
I've included a [comment related to this here](https://github.com/pytorch/pytorch.github.io/issues/828#issuecomment-941370876), as it is also an issue for us.

**Comment by gkowarzyk** [comment]
Hello,

Following up: @harishsk , I also don't see the `v0.9.2` tag for `torchtext`, only `v0.9.2-rc1`.
Would it be possible to add i please?

Thanks in advance!

**Comment by harishsk** [comment]
@malfet  / @seemethere I do not have permissions to add the tags. Can you please do so?

**Comment by malfet** [comment]
Added https://github.com/pytorch/text/releases/tag/v0.9.2

**Comment by Nayef211** [comment]
Thanks @malfet for adding the `v0.9.2` release tag. Closing the issue!
