### ISSUE TITLE
ModuleNotFoundError: No module named 'torchtext.experimental' for "examples/BERT/qa_task.py"

### ISSUE THREAD

**Issue by batermj** [pytorch/text#1401]
## 🐛 Bug
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
python -c "import torchtext; print(\"torchtext version is \", torchtext.__version__)"
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Additional context**

**Comment by parmeet** [comment]
Hi @batermj, The experimental package is not part of release binaries. It is available through nightly releases. Also on side note, the examples folder is broken as we have removed some of the experimental functionalities in this PR https://github.com/pytorch/text/pull/1326 on which they depend. We are in process of fixing our examples directory.

**Comment by parmeet** [comment]
closing the issue as BERT example is removed from the repo
