### ISSUE TITLE
Non-Tensor Field

### ISSUE THREAD

**Issue by kylegao91** [pytorch/text#141]
Many dynamic models, e.g. sequence to sequence with copy mechanism, require information in addition to the data during the forward pass.  The additional information could be primitive numbers or complex data objects such as dynamic vocabularies.

Currently since a batch only carries registered fields, and fields only carry tensors, it's hard to pass non-tensor objects to the model.  It'd be nice if a field can store any object.

**Comment by jekbradbury** [comment]
The current story here is to create a custom Field subclass where `pad` and `numericalize` are no-ops. But yes, that should be built-in.

**Comment by kylegao91** [comment]
I'd like to work on this.  How about a ObjectField that allows any object and the current Field (TensorField?) becomes a subclass of ObjectField?  I think the inheritance is more natural in this way.

**Comment by jekbradbury** [comment]
Sure, I think that would work. But `TensorField` would probably have to continue to be called `Field`, so maybe the base class would be `RawField`?

**Comment by kylegao91** [comment]
Of course, changing the name is disrupting...  I will work on it.
