### ISSUE TITLE
Is there a torchtext Pipeline or transformation pipeline for 0.10.0

### ISSUE THREAD

**Issue by 00krishna** [pytorch/text#1446]
## ❓ Questions and Help

**Description**

I saw that in earlier versions of Torchtext there used to be a torchtext.data.Pipeline() to facilitate sequential transformation of text data. 
I just looked through the documentation for 0.10.0 and I don't see this functionality anymore. I was just wonder if perhaps this Pipeline was renamed or if the developers decided on a better way to handle these transformations? I an write my own transform function, but sometimes using the built-in function allows pytorch to introspect and optimize those functions. Thanks.

**Comment by parmeet** [comment]
Indeed we are doing revamp on our transforms. Although we do not have good support for transforms in version 0.10.0 (or current released version i.e 0.11.0), but we plan to add a bunch in upcoming release. You could take a look at newly added [transforms](https://pytorch.org/text/main/transforms.html) and [functionals](https://pytorch.org/text/main/functional.html). These transforms are nn modules, so can be piped together using [nn.Sequential](https://pytorch.org/docs/stable/generated/torch.nn.Sequential.html). There is model level transform as well which is part of our [model API](https://pytorch.org/text/main/models.html). Note that documentation is still bleak and APIs are in development process, so you may expect some changes going forward.  Do not hesitate to also look in the repo directly if document doesn't help for now. You can try these newly added features by installing nightly releases. Also please do not hesitate to create feature requests for your specific transforms or provide feedback on existing ones. Thanks!

**Comment by 00krishna** [comment]
Thanks @parmeet yeah this makes sense. I was just working on my preprocessing pipeline and have a lot of `list(map(lambda x: ...))` stuff going on, so I am looking forward to the revamped transforms. But what I have will work for now and into the future. And I can convert them over when the new features are ready. Thanks again.
