### ISSUE TITLE
How to get all tokens in a Vocab using text

### ISSUE THREAD

**Issue by yipliu** [pytorch/text#1476]
## 🚀 Feature

**Motivation**
Hi,

When I load a vocab or have built a vocab using torchtext.vocab, I can not print its all token in the Vocab

**Comment by erip** [comment]
There are several different "Vocab" classes in torchtext. If it's one you've generated from `vocab_factory`, you can use `vocab.vocab.itos_` which prints a list of tokens in the vocab ordered by their index.

**Comment by yipliu** [comment]
Thank you!
