### ISSUE TITLE
error when x is a string instead of a unicode 

### ISSUE THREAD

**Issue by eriche2016** [pytorch/text#15]
[this line](https://github.com/pytorch/text/blob/a4d597e194e933b384fbce62a13600c4adb6fbd7/torchtext/data.py#L138]), six.text_type.lower requires the input x to be of type unicode, so when x is a string, this will complain with an error. what about changing this line to be:
```
 x = Pipeline(six.text_type.lower)(unicode(x))
```
any ideas

**Comment by jekbradbury** [comment]
If that works for you and doesn’t break Py3, that sounds good. Sorry that I didn’t actually fix the Python2 problem before.

**Comment by eriche2016** [comment]
Yes, it fixes my problem. And i donot know whether it will break py3.

**Comment by jekbradbury** [comment]
Fixed in #21.
