### ISSUE TITLE
ValueError: Got input vectors of type <type 'str'>, expected str or Vectors object

### ISSUE THREAD

**Issue by aotemandess** [pytorch/text#152]
when I run the code, it has the error,
**Traceback (most recent call last):
  File "test/example.py", line 16, in <module>
    inputs.vocab.load_vectors('glove.840B.300d')
  File "/Users/wangyuan/anaconda2/lib/python2.7/site-packages/torchtext/vocab.py", line 129, in load_vectors
    "Vectors object".format(type(vector)))
ValueError: Got input vectors of type <type 'str'>, expected str or Vectors object**

**Comment by jekbradbury** [comment]
Thanks! Will merge the fix (#153) as soon as it passes CI.
