### ISSUE TITLE
Add a `max_words` argument to `build_vocab_from_iterator`

### ISSUE THREAD

**Issue by xhlulu** [pytorch/text#1523]
## 🚀 Feature

[Link to the docs](https://pytorch.org/text/stable/vocab.html?highlight=build%20vocab#torchtext.vocab.build_vocab_from_iterator)

I believe it would be beneficial to limit the number of words you want in your vocabulary with an argument like `max_words`, e.g.:
```
vocab = build_vocab_from_iterator(yield_tokens_batch(file_path), specials=["<unk>"], max_words=50000)
```

**Motivation**

This allows a controllable-sized `nn.Embedding`, with rare words being mapped to `<unk>`. Otherwise, it would not be practical to use `build_vocab_from_iterator` for larger datasets.

**Alternatives**

Keras and Huggingface's tokenizers would be viable alternatives, but do not nicely integrate with the torchtext ecosystem.

**Comment by parmeet** [comment]
Thank you @xhlulu for interesting proposal. I don't see any downsides for adding this argument. Internally, we are sorting tokens by frequency and I think it would be trivial to add the support for max_words by discarding the lowest frequency tokens. I wonder if there are any other criteria that users might want to follow instead of frequency?

**Comment by erip** [comment]
I'll add that normally your "upstream" tokenization strategy will sometimes handle this for you. For instance, you can specify subword vocab size when training unigram LM as in sentencepiece or BPE-based models. Building your torchtext vocabulary from subword tokenized segments means you already get this "max_tokens" implicitly.

**Comment by parmeet** [comment]
> I'll add that normally your "upstream" tokenization strategy will handle this for you. 

I wonder if this is valid for all types of tokenizers? For instance white-space or other rule/regex based tokenizers may not provide such constraints out-of-the-box, right?

**Comment by erip** [comment]
It's certainly not valid in all cases and your point is well taken. I'd at the very least recommend sticking with "max tokens" or "max vocab size" since words are a bit sticky. :-)

**Comment by abhinavarora** [comment]
This does seem like a valid request as this limit from upstream tokenizers is something that is not applicable to regex, whitespace or from a pre-existing vocabulary. Agree with @erip on the naming being something like `max_vocab_size`

**Comment by abhinavarora** [comment]
> Thank you @xhlulu for interesting proposal. I don't see any downsides for adding this argument. Internally, we are sorting tokens by frequency and I think it would be trivial to add the support for max_words by discarding the lowest frequency tokens. I wonder if there are any other criteria that users might want to follow instead of frequency?

Having the frequency criteris seems good enough for now :-)
