### ISSUE TITLE
Add secondary caching to newly-migrated datapipe-based datasets

### ISSUE THREAD

**Issue by erip** [pytorch/text#1526]
This is mostly so things don't fall through the cracks...

## 🚀 Feature

**Motivation**

CI spends too much time unpacking cached datasets. We can also cache uncompressed and extracted files for relevant splits.

**Pitch**

Add secondary caching to datasets which have been migrated per #1494.

**Alternatives**

N/A

**Additional context**

See discussion in review of #1515

**Comment by parmeet** [comment]
I would also add to Motivation that it helps improve workflow efficiency. With extracted files being cached on disk in the first iteration, datapipe would avoid doing the same in the consecutive iterations. Also the alternative would be [In Memory caching](https://github.com/pytorch/data/blob/c06066ae360fc6054fb826ae041b1cb0c09b2f3b/torchdata/datapipes/iter/util/cacheholder.py#L19) in which case the files won't be dumped to the disk. @ejguan just to confirm this is indeed the right understanding?

**Comment by ejguan** [comment]
> I would also add to Motivation that it helps improve workflow efficiency. With extracted files being cached on disk in the first iteration, datapipe would avoid doing the extraction in the consecutive iterations. Also the alternative would be [In Memory caching](https://github.com/pytorch/data/blob/c06066ae360fc6054fb826ae041b1cb0c09b2f3b/torchdata/datapipes/iter/util/cacheholder.py#L19) in which case the files won't be dumped to the disk. @ejguan just to confirm this is indeed the right understanding?

Correct. But, it requires more careful design. If we do in memory caching over file handlers, it won't actually work unless you explicitly rewind them.

**Comment by erip** [comment]
I think this can be closed since the previously-migrated datasets now have double caching and future migrations will require it as part of code review.

**Comment by parmeet** [comment]
> I think this can be closed since the previously-migrated datasets now have double caching and future migrations will require it as part of code review. Feel free to reopen as necessary.

Thanks @erip for helping keep track of progress through this issue!
