### ISSUE TITLE
[META] how do we want to handle stale issues/PRs?

### ISSUE THREAD

**Issue by erip** [pytorch/text#1537]
## ❓ Questions and Help

There are many issues and PRs in the repo either related to long-gone legacy APIs or have been overcome by events. How do we want to track/manage these potentially stale issues?

Options:
- A bot
  - I don't like this option because it can permit false positives which makes it hard for users to find real issues
- Manual inspection
  - This can take a bit of time, but it's more precise
- Others?

**Comment by abhinavarora** [comment]
Maybe we can do a manual rundown and close them? For future ones we could establish a core process. What do you think?

**Comment by Nayef211** [comment]
> Maybe we can do a manual rundown and close them? For future ones we could establish a core process. What do you think? I also created a tag called `obsolete` that we can use to close such PRs and issues. Will make searching easier if we ever have to search them?

Thanks @erip for creating this issue. I also brought this up with @parmeet earlier last week and we thought that it would make sense to do this manually so we can ensure that only non-relevant PRs/issues are closed. This can be a collaborative effort throughout the next couple of months. If each of us spends 30 minutes a day going through and closing some of the stale issues and PRs, the torchtext repo will look a lot more welcoming for new OSS contributors!

**Comment by abhinavarora** [comment]
> If each of us spends 30 minutes a day going through and closing some of the stale issues and PRs, the torchtext repo will look a lot more welcoming for new OSS contributors!

Yes, agree with this. Let's use the obsolete tag for such PRs and diffs so that we can quantify the number of PRs and issues easily.

**Comment by parmeet** [comment]
Some issues/PRs are related to legacy torchtext APIs (which we have removed recently #1422 ). We might also want to attach `legacy` tag with those PRs/issues. It's not a hard-requirement, but let's try to do so wherever it's obvious :)

**Comment by parmeet** [comment]
> Yes, agree with this. Let's use the obsolete tag for such PRs and diffs so that we can quantify the number of PRs and issues easily.

@abhinavarora  I am not sure what `obsolete` really mean? Are you referring to `legacy` torchtext issues/PRs as `obsolete`?

**Comment by abhinavarora** [comment]
> > Yes, agree with this. Let's use the obsolete tag for such PRs and diffs so that we can quantify the number of PRs and issues easily.
> 
> @abhinavarora I am not sure what `obsolete` really mean? Are you referring to `legacy` torchtext issues/PRs as `obsolete`?

Obsolete just means out of date or deprecated. I am referring to any issue or PR that refers to legacy or non-existent code as `obsolete`.  I don't have context on what was the state of the library before we had the `legacy` directory, that we removed in Dec. So `obsolete` is just a blanket label for anything that is stale or legacy or is no longer relevant. Hope that makes sense.

**Comment by parmeet** [comment]
> Obsolete just means out of date or deprecated. 

yupp, we had the label for that `legacy`. You may be able to find more https://github.com/pytorch/text/issues?q=label%3Alegacy+ although I could imagine not all the issues/PR associated with legacy code is labelled as such.

**Comment by Nayef211** [comment]
Closing this issue as we decided to manually close out old PRs and opened issues. I will add this to torchtext's better engineering efforts for this half.
