### ISSUE TITLE
ReversibleField performs in-place transpose operation

### ISSUE THREAD

**Issue by jihunchoi** [pytorch/text#154]
I am using the recently added `ReversibleField` field.
Converting padded indices into original words was always a cumbersome chore, and the newly added class greatly reduces this burden.
However, I found a strange behavior of the class; when `batch_first` is `True`, it performs in-place transpose operation, which I think not intuitive.
Is it an intended side effect?
The following is the code for reproducing this behavior.
```
TEXT = data.ReversibleField()
LABEL = data.Field(sequential=False)
train, dev, test = datasets.SNLI.splits(TEXT, LABEL)
TEXT.build_vocab(train, max_size=1000) 
LABEL.build_vocab(train) 
train_iter, dev_iter, test_iter = data.BucketIterator.splits((train, dev, test), batch_size=4)
b = next(iter(train_iter))
b.premise.size()  # torch.Size([7, 4])
TEXT.reverse(b.premise.data)
b.premise.size()  # torch.Size([4, 7])
```

And it is also problematic in that calling `TEXT.reverse(b.premise.data)` repeatedly does not give consistent results.
For example, when I call it for the first time, it works nicely:
```
['A girl jumps off of a diving board into a pool.',
 'The mountain biker is UNK the hill on a UNK trail.',
 'A man is standing next to a large black UNK statue.',
 'A young gentleman is pointing to a sign on a building.']
```
However if I call it again, since `b.premise.data` is transposed, it emits wrong results.
```
['A The A A',
 'girl mountain man young',
 'jumps biker is gentleman',
 'off is standing is',
 'of UNK next pointing',
 'a the to to',
 'diving hill a a',
 'board on large sign',
 'into a black on',
 'a UNK UNK a',
 'pool trail statue building',
 '....']
```

**Comment by jekbradbury** [comment]
Good catch! You're right, that should definitely be out-of-place.
