### ISSUE TITLE
Datasets Documentation

### ISSUE THREAD

**Issue by parmeet** [pytorch/text#1588]
## 📚 Documentation
 
**Description**
Torchtext provides access to publicly hosted datasets for varying NLP tasks like  classification, machine translation, sequence tagging, Q&A, self-supervised learning etc. In terms of documentation available [here](https://pytorch.org/text/stable/datasets.html#), there is only minimal information provided to the user. Unfortunately, it does not necessarily cover dataset description, source, associated license or citation information, format etc that can help significantly improve user experience. For instance, popular [Datasets](https://huggingface.co/docs/datasets/) library from HuggingFace provides Data Cards for hosted datasets that covers many of these items (and more like leadership boards etc). [Here](https://huggingface.co/datasets/imdb) is an example for the IMDB dataset.
 
## Proposal
In this Issue we would like to improve and standardize the dataset documentation that would help provide better user experience. 
 
Items that we can potentially include (wherever available):
 
**summary**
A brief description of dataset
 
**source and legal**
Provide information on dataset source, licensing and citation information
 
**Statistics**
Provide information on number of examples in the dataset,  number of classes (for classification data), supported language-pairs (for MT data) etc.  
 
**Format**
Provide information on what to expect in the data. For eg for IMDB this may look like `Tuple( class label (type: int), text (type: str))` (this is just an example, other formats suggestions are welcome)

**Comment by Nayef211** [comment]
Thanks for creating this issue @parmeet! Do you want to take on creating/standardizing the documentation for one of the datasets that we can use as an example moving forward when writing the docs for the rest of the datasets? Also would it be worthwhile keeping a checklist of which datasets still need to be worked on similar to what we've been doing for https://github.com/pytorch/text/issues/1493

**Comment by parmeet** [comment]
Closing this issue, since the basic documentation has been added.
