### ISSUE TITLE
Add Secondary Caching for Extracted Datasets Files

### ISSUE THREAD

**Issue by Nayef211** [pytorch/text#1589]
## 🚀 Feature
We need to update our dataset implementations to add secondary caching for extracted files as a followup to https://github.com/pytorch/text/issues/1494. 

**Motivation**

Some of our datasets have a `cache_compressed_dp` and then a `cache_decompressed_dp` which is the behavior we want (i.e. [EnWik9](https://github.com/pytorch/text/blob/main/torchtext/datasets/enwik9.py#L35-L50)). On the other hand some of our other datasets only cache the downloaded archive file and not the files extracted from that archive (i.e. [SogouNews](https://github.com/pytorch/text/blob/main/torchtext/datasets/sogounews.py#L47-L51)).

## Backlog of Dataset Tests
The following datasets need to be updated to add the secondary caching mechanism:

- [x] SogouNews #1594
- [x] AmazonReviewFull #1594
- [x] CoNLL2000Chunking #1590 
- [x] DBpedia #1571 

cc @parmeet @abhinavarora @VirgileHlav @erip

**Comment by erip** [comment]
Isn't it the case that some of these files (e.g., AG_NEWS) are just text files? So there's no `cache_decompressed_dp` that would exist?

**Comment by Nayef211** [comment]
> Isn't it the case that some of these files (e.g., AG_NEWS) are just text files so there's no `cache_decompressed_dp` that would exist? Some of these definitely need to be fixed for sure.

Oops you're right thanks for catching this. I've removed AG_NEWS from this list. I may also have missed a dataset or two so it might be worth going through all the datasets again to make sure the list is accurate!
