### ISSUE TITLE
Strongly suggest the ability to split the dataset

### ISSUE THREAD

**Issue by windweller** [pytorch/text#160]
So current the `.splits()` defined in `Dataset` seems to only take in pre-split files. This is very helpful for pre-defined, well-established datasets like WikiText, IMDB, etc. However, for people in other fields, it could be beneficial if the `Dataset` can provide a split function where I dump the whole data in, and it splits nicely into train, valid, test?

(Besides that, I love this library :) saved me so much trouble! Might move away from Tensorflow just because of this...

it's unfortunate that there's a lack of documentation, but I was still able to figure everything out within a few hours and connect to a PyTorch model)

**Comment by jekbradbury** [comment]
Not a bad idea! Will try to add this if I get some time.

**Comment by alejandrodumas** [comment]
I also think this library is great! Trying to use a seq2seq model with the
english to french data from: [http://www.manythings.org/anki/](http://www.manythings.org/anki/)
I arrived to the same problem, as you only have 1 big file. I want to help, but don't now
how we could handle the signature of the method, or do you have another method in mind @jekbradbury ? Don't know if adding another parameter for the train/val/test proportion is the best thing, but having another method would be strange

**Comment by windweller** [comment]
Haha :) Another question/concern: can PyTorch save cached vocabulary list and numericalized files somewhere so it doesn't reparse/re-numericalize every time it runs?

**Comment by jekbradbury** [comment]
You can definitely save the vocabulary using torch.save; however, we currently numericalize on the fly in order to not fill up GPU memory so you can't save that.

**Comment by oja** [comment]
This should be closed, right?
