### ISSUE TITLE
[META] Add missing unicode generation for IWSLTs

### ISSUE THREAD

**Issue by erip** [pytorch/text#1607]
With #1599 most tests have utf-8 roundtrip tests with the exception of the IWSLTs. It seems like the `xml.etree.ElementTree.fromstring` has no mechanism for recovering from error-inducing unicode (which is likely in randomly-generated strings). `lxml` has such a mechanism, but I'd hate to add a userland dependency for the sake of testing.

This issue records the TODO and acts as a place to brainstorm alternative mechanisms for testing roundtrip utf-8 encode/decodes in IWSLT.

**Comment by Nayef211** [comment]
I think this should be resolved by #1642. Let's reopen this issue if we start seeing test failures again
