### ISSUE TITLE
Does torchtext.vocab support onnx export?

### ISSUE THREAD

**Issue by jiwidi** [pytorch/text#1621]
## ❓ Questions and Help

Hello!

Im interested in using the torch.nn module [vocab](https://pytorch.org/text/stable/vocab.html) but I have doubts whether it supports the ONNX format. If I export a model where a layer is:

```
embedding_layer nn.Sequential(
         torchtext.vocab.Vocab(vocab),
         nn.embedding(num_embeddings = len(vocab), embedding_dim =128)
)
```

Would this be exportable to ONNX? Accepting string as input and doing the vocab lookup to index on runtime.

Edit: I tried myself and I couldnt export models to onnx as the sample request sent to ONNX needs to be a string but there is not string acceptance in pytorch

Thanks,

**Comment by Nayef211** [comment]
cc @abhinavarora @parmeet

**Comment by mthrok** [comment]
Looking at https://onnxruntime.ai/docs/reference/operators/add-custom-op.html, to run a custom operator on ONNX, the operator needs to be registered on C-level. As far as I am aware, none of torchtext's custom C++ implementation mentions ONNX, so I do not think it can work in ONNX.

One of the example from the same ONNX page says 

> [Custom op shared library with Python API](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/python/onnxruntime_test_python.py): `testRegisterCustomOpsLibrary` uses the Python API to register a shared library with custom op kernels. Currently, the only supported Execution Providers (EPs) for custom ops registered via this approach are CUDA and CPU.

so it seems plausible to make the vocab work with ONNX via torchtext shared library. However, for the sake of ease of use, I think this will require splitting the kernel implementation into library files with and without Python linkage, which has not accomplished in torchtext yet.

**Comment by Nayef211** [comment]
Hey @jiwidi, let me know if you have any further questions. I'm going to go ahead and close out this issue for now.
