### ISSUE TITLE
Using torchtext vocab with torchscript

### ISSUE THREAD

**Issue by jiwidi** [pytorch/text#1623]
Hi!

I'm trying to use the torchtext vocab layer along with torchscript but I'm getting some errors and I was wondering if someone here has made it work.

My current model is 

```
class VocabText(torch.nn.Module):

    def __init__(self):

        super(VocabText, self).__init__()

        self.embedding = torch.nn.Embedding(10,128)

        vocab = ['This', 'is', 'a', 'test']

        counter = Counter(vocab)

        self.lookup = text.vocab.vocab(counter)

        self.tensor = torch.Tensor

    def forward(self, x: str):

        x_mapped = self.lookup(x)

        x_mapped = self.tensor(x_mapped).int()

        x_mapped = self.embedding(x_mapped)

        

        return x
```
That works when I do a pass of the model like this:

```
example_str = ["is"]

model(example_str)
```

But when I try to compile it with torchscript it fails:

```
model_scripted = torch.jit.script(model)   

model_scripted.save('model_scripted.pt')
```
With the following error:
![image|690x265](upload://kkF8ueMBXldUeEH46r8RhFofAdR.png)

I think is due to typing as the vocab layer expects strings as input but the embedding layer will use tensors. Im doing a cast in the middle of the forward.

I have a working notebook in colab to reproduce this issue if anybody wants: https://colab.research.google.com/drive/14nZF5X8rQrZET_7iA1N2MUV3XSzozpeI?usp=sharing

**Comment by Nayef211** [comment]
Hi @jiwidi. I see that you closed this issue. In order to help resolved similar issues in the future, I'm wondering if you were able to figure out what your error was caused by and what fixed it?

**Comment by jiwidi** [comment]
> Hi @jiwidi. I see that you closed this issue. In order to help resolved similar issues in the future, I'm wondering if you were able to figure out what your error was caused by and what fixed it?

It was actually due to a problem with the function I was using to cast to tensor, following https://discuss.pytorch.org/t/unknown-builtin-op-aten-tensor/62389 I could fix it.

But I have another issue at this repos still that I havent been able to figure out https://github.com/pytorch/text/issues/1621
