### ISSUE TITLE
Internal error: confirm_token was not found in Google drive link.

### ISSUE THREAD

**Issue by dongqi-liu** [pytorch/text#1638]
```python
import os
import torch
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator
from torchtext.datasets import IWSLT2017
train_iter = IWSLT2017(split='train', language_pair=('en', 'de'))
```

Traceback (most recent call last):
  File "/Users/darcy/opt/anaconda3/envs/supar/lib/python3.7/site-packages/torchtext/data/datasets_utils.py", line 257, in wrapper
    return func(root=new_root, *args, **kwargs)
  File "/Users/darcy/opt/anaconda3/envs/supar/lib/python3.7/site-packages/torchtext/data/datasets_utils.py", line 219, in new_fn
    result.append(fn(root, item, **kwargs))
  File "/Users/darcy/opt/anaconda3/envs/supar/lib/python3.7/site-packages/torchtext/datasets/iwslt2017.py", line 194, in IWSLT2017
    dataset_tar = download_from_url(SUPPORTED_DATASETS['URL'], root=root, hash_value=SUPPORTED_DATASETS['MD5'], path=os.path.join(root, SUPPORTED_DATASETS['_PATH']), hash_type='md5')
  File "/Users/darcy/opt/anaconda3/envs/supar/lib/python3.7/site-packages/torchtext/utils.py", line 116, in download_from_url
    _DATASET_DOWNLOAD_MANAGER.get_local_path(url, destination=path)
  File "/Users/darcy/opt/anaconda3/envs/supar/lib/python3.7/site-packages/torchtext/_download_hooks.py", line 50, in get_local_path
    response, filename = _get_response_from_google_drive(url)
  File "/Users/darcy/opt/anaconda3/envs/supar/lib/python3.7/site-packages/torchtext/_download_hooks.py", line 29, in _get_response_from_google_drive
    raise RuntimeError("Internal error: confirm_token was not found in Google drive link.")
RuntimeError: Internal error: confirm_token was not found in Google drive link.

**Comment by Nayef211** [comment]
Hi @dongqi-liu. Can you provide more details as to the version of `torchtext` you are using? I just tried running your code on the latest `master` branch and it seems to be working fine for me.

**Comment by maulberto3** [comment]
I am on kaggle.com and have the exact same problem.

**Comment by parmeet** [comment]
> Can you provide more details as to the version of `torchtext` you are using? 

This may likely not be an issue with any particular version of torchtext. This is caused typically due to some issues connecting with google drive servers (likely some form of quota limits or so)..I have seen some other users also raising the same issue with IWSLT2016/2017 datasets.

**Comment by austinvhuang** [comment]
Having a related discussion here:

https://github.com/pytorch/text/issues/1620
https://github.com/pytorch/text/issues/1359

**Comment by Nayef211** [comment]
@NivekT @ejguan I think these errors are all coming from the GDriveReader in torchdata. Do you think this issue may be related to https://github.com/pytorch/data/issues/204 and/or https://github.com/pytorch/data/issues/167?

**Comment by NivekT** [comment]
> @NivekT @ejguan I think these errors are all coming from the GDriveReader in torchdata. Do you think this issue may be related to [pytorch/data#204](https://github.com/pytorch/data/issues/204) and/or [pytorch/data#167](https://github.com/pytorch/data/issues/167)?

I don't think it is related. The error is raised by the follow line of code in `torchtext`:
https://github.com/pytorch/text/blob/142b1ef32d04a46a46de92853d7a45d512be5e09/torchtext/_download_hooks.py#L36

I suspect users may have an older version of `torchtext` where the functions in `_download_hooks.py ` are still being used instead of `torchdata`.

Note that in `torchdata`, `confirm_token` is optional and doesn't raise an exception:

https://github.com/pytorch/data/blob/fbf097d43c9643fb9ca9ddcb7e2891630aac84ac/torchdata/datapipes/iter/load/online.py#L76-L78

**Comment by Nayef211** [comment]
Closing because updating to torchtext version `0.12.0` resolves the error
