### ISSUE TITLE
Can't get SST2

### ISSUE THREAD

**Issue by shawnjhenry** [pytorch/text#1659]
## 🐛 Bug

When I follow the instructions to get the SST2 dataset I get the error:

"/torch/utils/data/datapipes/utils/common.py:24: UserWarning: Lambda function is not supported for pickle, please use regular python function or functools.partial instead.
  warnings.warn(
/torch/utils/data/datapipes/iter/selecting.py:54: UserWarning: Lambda function is not supported for pickle, please use regular python function or functools.partial instead.
  warnings.warn("Lambda function is not supported for pickle, please use "

**To Reproduce** Steps to reproduce the behavior:

from torchtext.datasets import SST2

train_datapipe = SST2(split='train')

- PyTorch Version (e.g., 1.0): 1.11.0
- OS (e.g., Linux): MacOS 11.6
- How you installed PyTorch (`conda`, `pip`, source): pip
- Build command you used (if compiling from source): n/a
- Python version: 3.8
- CUDA/cuDNN version: n/a
- GPU models and configuration: n/a
- Any other relevant information: n/a

**Comment by shawnjhenry** [comment]
When I went into the code I noticed the DILL_AVAILABLE flag.  Installing dill solved the issue, but it seems like that should be installed by default if it's a required dependency.

**Comment by Nayef211** [comment]
Hi @shawnjhenry. I believe the output you are seeing is just a warning message rather than an actual error. I just tried reproing your code and it works fine within a MacOS environment. Here is the exact snippet of code I'm running. 

```
>>> from torchtext.datasets import SST2
>>> train_datapipe = SST2(split='train')
/Users/nayef211/opt/miniconda3/envs/torchtext/lib/python3.9/site-packages/torch/utils/data/datapipes/utils/common.py:24: UserWarning: Lambda function is not supported for pickle, please use regular python function or functools.partial instead.
  warnings.warn(
/Users/nayef211/opt/miniconda3/envs/torchtext/lib/python3.9/site-packages/torch/utils/data/datapipes/iter/selecting.py:54: UserWarning: Lambda function is not supported for pickle, please use regular python function or functools.partial instead.
  warnings.warn("Lambda function is not supported for pickle, please use "
>>> next(iter(train_datapipe))
('hide new secretions from the parental units', 0)
```

Can you try doing the same within your dev environment and see if you get any errors?

**Comment by parmeet** [comment]
Since this is just a user-warning, closing this issue for now.
