### ISSUE TITLE
what's is the replacement of legacy?

### ISSUE THREAD

**Issue by 1152545264** [pytorch/text#1661]
## ❓ Questions and Help

**Description**

in torchtext0.12.0, the module legacy has been removed, so how to implement the same functions as the class legacy.Field?
thanks for your help.

**Comment by Nayef211** [comment]
The legacy module has been deprecated since torchtext 0.11 and has been deleted in 0.12.0. If you want to use `legacy.Field` class or associated functions, feel free to downgrade your version of torchtext or copy over the functions/classes to your own project!

**Comment by pandya6988** [comment]
Why pytorch should remove such a useful functions? specially when it was already developed.

**Comment by Nayef211** [comment]
Refer to https://github.com/pytorch/text/issues/664 for the plans to revamp the torchtext library (which contains the motivation behind why these features were deprecated).
