### ISSUE TITLE
Importing torchtext in Kaggle notebook

### ISSUE THREAD

**Issue by maulberto3** [pytorch/text#1682]
## 🐛 Bug

**Describe the bug** A clear and concise description of what the bug is.

There is a bug just by following PyTorch's SST-2 tutorial online.

**To Reproduce** Steps to reproduce the behavior:

1. Go to [the demo online](https://pytorch.org/text/main/tutorials/sst2_classification_non_distributed.html)
2. Just following the steps, code fails on `import torchtext.transforms as T` with torchtext==0.12.0
3. Error:

```
----> 1 import torchtext.transforms as T
      2 from torch.hub import load_state_dict_from_url
      3 
      4 padding_idx = 1
      5 bos_idx = 0

/opt/conda/lib/python3.7/site-packages/torchtext/transforms.py in <module>
      4 import torch
      5 from torchtext.data.functional import load_sp_model
----> 6 from torchtext.utils import get_asset_local_path
      7 from torchtext.vocab import Vocab
      8 from torchtext._torchtext import GPT2BPEEncoder as GPT2BPEEncoderPyBind, CLIPEncoder as CLIPEncoderPyBind

ImportError: cannot import name 'get_asset_local_path' from 'torchtext.utils' (/opt/conda/lib/python3.7/site-packages/torchtext/utils.py)
```

**Expected behavior**

The tutorial should work as it is.

**Additional context** 

I'm on kaggle.com

**Comment by Nayef211** [comment]
So it looks like the default `torchtext` version in this tutorial is `0.11.0`. I verified this using the following lines
```
import torchtext
torchtext.__version__
```

After installing torchtext `0.12.0` using `!pip install torchtext==0.12.0`, we are able to get past the code failure. @parmeet  do you know how we can update the default `torchtext` and `torch` versions for this tutorial?

**Comment by parmeet** [comment]
I just went ahead and look at the default version of torch on google Colab. It is 1.10 on my side and hence the torchtext version as 0.11. Seem like they haven't upgraded to newer version yet? @mthrok Do you know the path to upgrade the PyTorch libraries on Colab, is there someone on our end have to manually request? 

@maulberto3 meanwhile, the resolution would be to upgrade the library version on Colab to fix this issue.

**Comment by maulberto3** [comment]
Hi @parmeet thank you for the attention.

Do you reckon Colab as kaggle.com? Also, note that as per explained, I am using version 12.

**Comment by mthrok** [comment]
You can track the Google Colab's update request at https://github.com/googlecolab/colabtools/issues/2668.

But if torchtext 0.12 is installed on (Kaggle) notebook, the tutorial should work as is.
@maulberto3 Can you run the following in the notebook, and share what it reports ?

```python
import torch.utils.collect_env

torch.utils.collect_env.main()
```

**Comment by maulberto3** [comment]
@mthrok 

Hi, it reports the following:
```
Collecting environment information...
PyTorch version: 1.10.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.10

Python version: 3.7.10 | packaged by conda-forge | (default, Sep 13 2021, 19:43:44)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.107+-x86_64-with-debian-buster-sid
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.7.1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.19.5
[pip3] pytorch-ignite==0.4.7
[pip3] pytorch-lightning==1.4.4
[pip3] torch==1.10.0
[pip3] torchaudio==0.9.1
[pip3] torchmetrics==0.5.0
[pip3] torchtext==0.11.0
[pip3] torchvision==0.10.1+cpu
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] msgpack-numpy             0.4.7.1                  pypi_0    pypi
[conda] mypy_extensions           0.4.3            py37h89c1867_3    conda-forge
[conda] numpy                     1.19.5           py37h038b26d_2    conda-forge
[conda] pytorch-ignite            0.4.7                    pypi_0    pypi
[conda] pytorch-lightning         1.4.4                    pypi_0    pypi
[conda] torch                     1.10.0                   pypi_0    pypi
[conda] torchaudio                0.9.1                    pypi_0    pypi
[conda] torchmetrics              0.5.0                    pypi_0    pypi
[conda] torchtext                 0.11.0                   pypi_0    pypi
[conda] torchvision               0.10.1+cpu               pypi_0    pypi
```

**Comment by mthrok** [comment]
So the version of `torchtext` recognized by Python interpreter is 0.11.
I am not sure if Kaggle notebook is exactly same as Colab, or even close, but 
one typical scenario this happens on Colab is that one imports the module first, and then update the package.
In this case the package installed after the module is not reflected.

Did you, or could you restart your session after installing `torchtext 0.12`?

**Comment by maulberto3** [comment]
@mthrok 

I think that the notebook restarting session suggestion played me this time, as upon doing it before importing the module, it does not show the mentioned error.

**Comment by mthrok** [comment]
@maulberto3 Great. 

FYI: the combination of domain libraries and PyTorch in the report look strange.
If they are installed from official channel, then the combination that would work is either

```
torch=1.10, torchaudio=0.10, torchvision=0.11, torchtext=0.11
torch=1.11, torchaudio=0.11, torchvision=0.12, torchtext=0.12
```

**Comment by maulberto3** [comment]
@mthrok 

Nice to know the correct combination of libraries. Will be happy to report if anything else. Thanks a lot. Lastly, hopefully this will help other people too.
