### ISSUE TITLE
Want to find a solution for different version of torchtext when using the code in `https://pytorch.org/tutorials/beginner/transformer_tutorial.html`

### ISSUE THREAD

**Issue by PolarisRisingWar** [pytorch/text#1686]
## ❓ Questions and Help

**Description**

The link of code is: https://pytorch.org/tutorials/beginner/transformer_tutorial.html

The code is:
```python
from torchtext.datasets import WikiText2
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

train_iter = WikiText2(split='train')
tokenizer = get_tokenizer('basic_english')
vocab = build_vocab_from_iterator(map(tokenizer, train_iter), specials=['<unk>'])
```

My torchtext version is 0.9.2 (As recommended as my torch version is 1.8.1), and I got this error:
```
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_48994/2019529097.py in <module>
      5 train_iter = WikiText2(split='train')
      6 tokenizer = get_tokenizer('basic_english')
----> 7 vocab = build_vocab_from_iterator(map(tokenizer, train_iter), specials=['<unk>'])
      8 vocab.set_default_index(vocab['<unk>'])
      9 

TypeError: build_vocab_from_iterator() got an unexpected keyword argument 'specials'
```
I found that in https://github.com/pytorch/text/blob/master/torchtext/vocab/vocab_factory.py this function get this keyword argument, but in 0.9.2 version in torchtext/vocab.py it doesn't. So I wonder what should I do? Is it just OK to upgrade torchtext version? Or can I get some alternating solutions (like change some code) for this problem?

**Comment by parmeet** [comment]
Hi @PolarisRisingWar, I would suggest to upgrade the torchtext version. The tutorials are meant to be compatible with latest release and are not guaranteed to be Backward compatible.

**Comment by Nayef211** [comment]
@PolarisRisingWar let me know if the issue wasn't fixed by upgrading your torchtext version. Going to close the issue for now!
