### ISSUE TITLE
Per word weighted features

### ISSUE THREAD

**Issue by ahhegazy** [pytorch/text#169]
My dataset has a field that represents weighted dictionary membership features for each word stored as a json object. For example: 

label       text_field                 dict_features
pos         Seattle is good        {"wIdx": 0, "features" : {"city": 0.7}}

In the model I have an embedding table for the dict_features that I am learning its weights as part of the model. 

I am wondering what is the best way to implement this field, specifically, what the preprocessing/postprocessing/numericalize functions should look like?

**Comment by jekbradbury** [comment]
Here you probably want to write a custom `Dataset` class that has the logic to unpack the json object and turn it into a list of floats, then use a `RawField` to encode those floats?
