### ISSUE TITLE
Torchtext 0.12.0 Legacy

### ISSUE THREAD

**Issue by pourfazl** [pytorch/text#1691]
Hi and kind regards,

It seems that "Legacy" folder was removed from Torchtext 0.12.0. Is it temporarily or I should use older versions? Lots of thanks.

**Comment by VirgileHlav** [comment]
Hi @pourfazl, it was removed permanently from TorchText. We will not support fixes in the `legacy` folder moving forward. This [thread](https://github.com/pytorch/text/pull/1689#issuecomment-1112502958) might also be relevant. 

Feel free to re-open the issue if you have more questions.
