### ISSUE TITLE
Add TorchData as a required dependency in TorchText for 0.13.0 release

### ISSUE THREAD

**Issue by Nayef211** [pytorch/text#1702]
## 🚀 Feature

TorchData is currently an optional dependency which means users have to `pip install torchdata` if they want to be able to use our datasets. Since datasets are a core feature of TorchText, we want to improve the user experience by making TorchData a required dependency.

After the next `torch` and `torchdata` branch cuts for version `1.12`, we want to take a hard dependency on the `torchdata` nightlies.

**Comment by Nayef211** [comment]
cc @atalman @malfet @parmeet @ejguan @seemethere

**Comment by Nayef211** [comment]
@atalman @malfet @ejguan do you guys know if we have the go ahead to make TorchData as a required dep moving forward? I know we were aiming to do this with the last release but it got pushed back to the 0.13 release instead.

**Comment by ejguan** [comment]
Yeah, it would be great if we TorchData are aware of the requirements/criteria to make this happen. Then, we can investigate if we have any step missing.

**Comment by ejguan** [comment]
After #1979 is fixed, could we start to make torchdata as a hard dependency in the main branch? Then, we will be able to spend time on figuring out what's wrong with the installation script.

**Comment by Nayef211** [comment]
Closed by #1985
