### ISSUE TITLE
Add support for all datasets of the GLUE benchmark

### ISSUE THREAD

**Issue by VirgileHlav** [pytorch/text#1710]
## 🚀 Feature

Add support for all 8 remaining datasets (SST-2 is already supported) of the [GLUE benchmark](https://gluebenchmark.com/): CoLA, MRPC, QQP, STS-B, MNLI, QNLI, RTE, WNLI.

**Motivation**

In itself adding support for all GLUE datasets has a lot of value: GLUE is one of the most widely used benchmark in the NLP community. Furthermore, our planned effort to develop a cohesive API for Multi-Task Learning requires us to enhance our suite our datasets, starting with GLUE.

**Additional context**

We have already created a streamlined dataset API, with a consistent use of DataPipes for dataset download and load operations, as well as a testing methodology relying on mock data (see #1493). This feature will only require to add support for these 8 datasets following that methodology.

## Datasets
 - [x] CoLA #1711
 - [x] MRPC #1712
 - [x] QQP #1713
 - [x] STS-B #1714
 - [x] MNLI #1715
 - [x] QNLI #1717
 - [x] RTE #1721
 - [x] WNLI #1724

**Comment by parmeet** [comment]
Thanks @VirgileHlav  for creating this issue! Just a general comment regarding dataset implementation: let's avoid usage of lambda functions, please refer issue https://github.com/pytorch/text/issues/1716 for details.

**Comment by Nayef211** [comment]
Thanks for creating this issue to keep track of the new datasets we are adding! One suggestion from my end would be to update our documentation for each new dataset we add [here](https://github.com/pytorch/text/blob/main/docs/source/datasets.rst).

**Comment by parmeet** [comment]
Let's also make sure we add shuffle and sharding filters: Reference Issue: https://github.com/pytorch/text/issues/1727. Reference PR #1729

**Comment by VirgileHlav** [comment]
Solved lint issues and added documentation + shuffle/sharding on all PRs.
