### ISSUE TITLE
TabularDataset

### ISSUE THREAD

**Issue by JustM57** [pytorch/text#1719]
## ❓ Questions and Help

**Replacement of torchtext.data.TabularDataset**

 As the change of API in version 1.9.0 many things have changed and deprecated modules moved to torchtext.legacy. There is nice migration tutorial how to replace Field & BucketIterator, but there is no information what to with the DataSet. In version 0.12.0 legacy module does not exist. Does current API support loading datasets from files or it supposed, maybe, to move to torchdata? What should be the replacement of TabularDataset?

**Comment by Nayef211** [comment]
TorchText as a whole is moving away from map style datasets and migrating to iterable style datasets ([doc](https://pytorch.org/docs/stable/data.html#map-style-datasets) explaining the differences between the two). The current API doesn't support loading datasets from a file, but we are thinking of adding a generic dataset class that allows users to do this (i.e. read from a csv/tsv file stored locally or on the web). 

In the meantime, you can create a copy of one of our dataset implementations (i.e. [`EnWik9`](https://github.com/pytorch/text/blob/main/torchtext/datasets/enwik9.py#L22)) and repurpose it for your use case with the use of datapipes from torchdata. If you are still interested in a map style dataset (similar to TabularDataset) you can make copy of the implementation from [here](https://github.com/pytorch/text/blob/71065192f529a886b27704ef5e7a3d2c700cba7b/torchtext/data/dataset.py#L217) to your local repo and work with that.

cc @parmeet

**Comment by parmeet** [comment]
@JustM57 would be great if you can also share your use-case bit in details. As @Nayef211 , we would potentially like to add utilities to support loading user dataset from files or web..Thanks!
