### ISSUE TITLE
How shall I install torchtext with pytorch version 1.10.1? Seems torchtext 0.12 and 0.11 only support 1.11.0 and 1.10.0 respectively

### ISSUE THREAD

**Issue by yingqichao** [pytorch/text#1723]
Dear developers,

How shall I install torchtext with pytorch version 1.10.1? Seems torchtext 0.12 and 0.11 only support 1.11.0 and 1.10.0 respectively. When I run either "pip install torchtext==0.11.0" or "pip install torchtext" (==0.12.0 omitted). The system will download a new pytorch version for me, which is annoying.

Thanks!

**Comment by mthrok** [comment]
Hi @yingqichao 

`TorchText v0.11.1` should work with `PyTorch 1.10.1`.

https://github.com/pytorch/text/releases/tag/v0.11.1

**Comment by yingqichao** [comment]
Thanks a lot mthrok!
