### ISSUE TITLE
Update MACOSX_DEPLOYMENT_TARGET to 10.13

### ISSUE THREAD

**Issue by ejguan** [pytorch/text#1725]
## 🚀 Feature

**Motivation**

TorchData is trying to enable AWSSDK to binary by default. However, the AWSSDK requires at least 10.13 for MacOS. Since TorchText is currently using `MACOSX_DEPLOYMENT_TARGET=10.9`, TorchData has to postpone enable AWSSDK in MacOS by default.

**Pitch**

Could we update the minimum version of `MACOSX_DEPLOYMENT_TARGET` in TorchText?

@atalman recommended me to post an issue to see if this is an option for TorchText.

**Alternatives**

**Additional context**

**Comment by mthrok** [comment]
I am not macOS expert and I do not really know what it does, but from [what I have been told](https://fburl.com/zhn6rcws) and [have done in audio](https://github.com/pytorch/audio/pull/1880), there should be no issue removing `MACOS_DEPLOYMENT_TARGET`.

**Comment by ejguan** [comment]
Thanks @mthrok for your input! That would be perfect for TorchData.

@parmeet wdyt?

Note: We don't necessarily make it into this coming release. I can disable C++ extension for TorchData on MacOS for the coming release.

**Comment by parmeet** [comment]
Yes, I agree with what @mthrok  said. I don't think this is an issue..Will make PR similar to Audio to remove it from TorchText.

**Comment by ejguan** [comment]
@parmeet Do you think it's going to be shipped before release?

**Comment by ejguan** [comment]
Closing as the PR has been merged. Thank you @parmeet
