### ISSUE TITLE
wv_dir in WikiText2

### ISSUE THREAD

**Issue by rachtsingh** [pytorch/text#174]
> from torchtext.datasets import WikiText2
    > train, val, test = WikiText2.iters(batch_size=32)
    > TypeError: __init__() got an unexpected keyword argument 'wv_dir'

Looks like https://github.com/pytorch/text/pull/94 didn't catch this. Let me know and I'll make a PR.

**Comment by keon** [comment]
#166 fixes this problem, not merged yet

**Comment by rachtsingh** [comment]
great, thanks!
