### ISSUE TITLE
All the mock tests are failing on CI

### ISSUE THREAD

**Issue by parmeet** [pytorch/text#1747]
All the mock tests for datasets started failing recently on CI as well

So far only thing I could figure out is that all of them are just hanging when fetching the samples and then fail after a while. For eg: [here](https://github.com/pytorch/text/blob/d963bdb82b4c6c5170430fd7289b9dd0a2b9283a/test/datasets/test_agnews.py#L58) for AG_NEWS test.

Interestingly, there is no problem working with the actual datasets in IPython. 

cc: @Nayef211, @ejguan, @VitalyFedyunin

**Comment by ejguan** [comment]
Could you please link the CI?
TorchData doesn't have major function changes this week. This is weird to me.

**Comment by Nayef211** [comment]
> Could you please link the CI? TorchData doesn't have major function changes this week. This is weird to me.

@ejguan  Here are the test failures in CI
https://app.circleci.com/pipelines/github/pytorch/text/5614/workflows/a4124efa-3ac7-44c0-9d5d-a702555542e1

**Comment by parmeet** [comment]
> TorchData doesn't have major function changes this week. This is weird to me.

Ya, It may likely not be an issue from torchdata side, since the real datasets are working just fine. But quite strange, why mock tests start failing all of sudden.

**Comment by parmeet** [comment]
Looking at the commit history, looks like mock tests start failing at this merge https://github.com/pytorch/text/commit/70fc1040ee40faf129604557107cc59fd51c4fe2

**Comment by parmeet** [comment]
OK found the issue. Culprit is this line https://github.com/pytorch/text/blob/d963bdb82b4c6c5170430fd7289b9dd0a2b9283a/torchtext/data/datasets_utils.py#L190. The base directory in mock tests need to take this into account.
