### ISSUE TITLE
batch size

### ISSUE THREAD

**Issue by ysangj** [pytorch/text#175]
I am trying to train encoder decoder using ISWLT data in torch text. My OS is OS X.
It seems if I set the batch size, the 'edge case', the code fails with the following error
(I have called evaluation with batch size 5)
 
RuntimeError: Assertion `THIndexTensor_(size)(target, 0) == batch_size' failed.  at /Users/soumith/miniconda2/conda-bld/pytorch_1503975723910/work/torch/lib/THNN/generic/ClassNLLCriterion.c:54

I know that there are 1026 data points in the validation dataset, and if I manually set the batch size as 6, this error doesn't pop up.
Any idea how to fix this issue?

**Comment by jekbradbury** [comment]
I don't remember seeing this before, so we'd probably need a little more code or info to be able to reproduce.

**Comment by jekbradbury** [comment]
Closing as dup of #186, which has some more info that may make it easier to figure out the bug
