### ISSUE TITLE
Calling torchtext.data.Dataset slow after updating to 0.2.0

### ISSUE THREAD

**Issue by mataney** [pytorch/text#177]
After updating to tag 0.2.0 calling torchtext.data.Dataset is a lot slower (doesn't seem to stop for CNNDM dataset) when using dynamic_dict as in [here](https://github.com/OpenNMT/OpenNMT-py/blob/45d92297e40775d46c66df60c69060e63bfa4417/onmt/IO.py#L364-L378) (passing filter as well).

After downgrading back to 0.1.1 works well again.

Couldn't find any reason why this might happen.
Any advice?

**Comment by zhangguanheng66** [comment]
I will close this issue since we are now on 0.4.0. Feel free to reopen it if you still experience the slowdown.
