### ISSUE TITLE
'MapperIterDataPipe' object is not an iterator  --- Error encountered when iterating IMDB Dataset

### ISSUE THREAD

**Issue by rrmina** [pytorch/text#1796]
## 🐛 Bug

Encounters **TypeError**: `'MapperIterDataPipe' object is not an iterator` when taking the `next` example from the iterator returned b  IMDB Dataset

**To Reproduce** Steps to reproduce the behavior:

```
import torchtext
import torchtext.datasets as datasets
train_iter, test_iter = datasets.IMDB(root='data', split=('train', 'test'))
next(train_iter)
```

**Expected behavior** A clear and concise description of what you expected to happen.

yields tuple of label (1 to 5) and text containing the news title and contents

**Screenshots** If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/7788765/174519178-49cba3bc-c5b7-483e-ad94-5bb441486a8a.png)

**Environment**

- torchtext Version: 0.12.0
- PyTorch Version (e.g., 1.0): 1.11.0
- OS (e.g., Linux): Windows
- How you installed PyTorch (`conda`, `pip`, source): conda install pytorch torchvision torchaudio torchtext cudatoolkit=11.3 -c pytorch
- Build command you used (if compiling from source): N/A
- Python version: 3.7.7
- CUDA/cuDNN version: 11.3
- GPU models and configuration: RTX 2060 Mobile
- Any other relevant information:

**Additional context**

I have also tried other datasets, particularly Multi30k and instead of yielding tuples of Source and Target sentences, I get `TypeError: 'ZipperIterDataPipe' object is not an iterator`

**Comment by rrmina** [comment]
Seems like the errors are caused by deprecated API from the tutorial I am following. Closing this issue now.

Sorry for the trouble.

**Comment by OrangeForTangerine** [comment]
what,help why it is not an iterator . I have an same questions for you ,help

**Comment by rrmina** [comment]
> what,help why it is not an iterator . I have an same questions for you ,help

to use it, you need to turn into an iter with iter() before iterating.

```
train_iter, test_iter = datasets.IMDB(root='data', split=('train', 'test'))
train_iter = iter(train_iter)
next(train_iter)
```

**Comment by OrangeForTangerine** [comment]
Thank you for your reply，i try it but it have an error```Exception: OnDiskCache Exception: ./data\datasets\IMDB\aclImdb_v1.tar.gz expected to be written by different process, but file is not ready in 300 seconds.
This exception is thrown by __iter__ of MapperIterDataPipe()`  i can't find same question in stackflow or other web .
today i will commit this program,😭it's so terrible
If you meet this same question ,please tell me ,thank you very much, my hero

**Comment by OrangeForTangerine** [comment]
Thank you for your answers,there is my code
```
import torch
import torchtext
from torchtext.datasets import IMDB
train_iter, test_iter = iter(IMDB(split=('train', 'test')))
# this i don't no why the 'next(train_iter)' code is false
next( iter(IMDB(split=('train', 'test'))))
#output : ShardingFilterIterDataPipe
tokenizer = torchtext.data.utils.get_tokenizer('basic_english')
print(tokenizer('here is the an example!'))
# the question occur in the following code
def yield_tokens(data_iter):
    for _, text in data_iter:
        yield tokenizer(text)

vocab = torchtext.vocab.build_vocab_from_iterator(yield_tokens(train_iter), specials=["<pad>", "<unk>"])
vocab.set_default_index(vocab["<unk>"])

print(vocab(tokenizer('here is the an example <pad> <pad>')))
```
but i user other dateset

```
import torch
from torchtext.datasets import AG_NEWS
import torchtext
train_iter = iter(AG_NEWS(split='train'))
# but this is '(3,
 "Wall St. Bears Claw Back Into the Black (Reuters) Reuters - Short-sellers, Wall Street's dwindling\\band of ultra-cynics, are seeing green again.")'
next(train_iter)

tokenizer = torchtext.data.utils.get_tokenizer('basic_english')
print(tokenizer('here is the an example!'))

def yield_tokens(data_iter):
    for _, text in data_iter:
        yield tokenizer(text)

vocab = torchtext.vocab.build_vocab_from_iterator(yield_tokens(train_iter), specials=["<pad>", "<unk>"])
vocab.set_default_index(vocab["<unk>"])

print(vocab(tokenizer('here is the an example <pad> <pad>')))
```
😂Although the work is over that the other Colleagues user paddle to Implement it, only it leaves me with my doubts,I will keep looking for the answer. Thanks for everyone

**Comment by shiki214215** [comment]
File "E:\Ana\envs\pytorch\lib\site-packages\torchdata\datapipes\iter\util\cacheholder.py", line 300, in _wait_promise_fn
    raise Exception(
Exception: OnDiskCache Exception: C:\Users\shiki/.cache\torch\text\datasets\AG_NEWS\train.csv expected to be written by different process, but file is not ready in 300 seconds.
This exception is thrown by __iter__ of MapperIterDataPipe(datapipe=UnBatcherIterDataPipe, fn=functools.partial(<function _wait_promise_fn at 0x00000266AE1452D0>, 300), input_col=None, output_col=None)
