### ISSUE TITLE
IMDB dataset: how to find batch training example's index into dataset

### ISSUE THREAD

**Issue by jeffrey6557** [pytorch/text#180]
Hi,

Using IMDB, I would like to link (through a dictionary or something) each review sentence with the original Movie title / file that it comes from in the dataset. In the suggested IMDB loading workflow found in the Torchtext test directory, where is the right step for something like this?  **Basically, given a review in a batch, I need an absolute index into the dataset rather than something dependent on Iterator settings.**

I imagine that something like a dictionary should be built from information in the IMDB dataset object. Is there a suggested usage pattern for retrieving this kind of info at iteration time? Improvising a little by looking at torchtext/test and the source code.

As usual, the loading workflow would be something like the following.

Thank you!

[Sorry didn't see any better wiki/forum to ask a question on than to make an issue. Is it better to use the PyTorch forums for these kind of questions or to keep them local to the torchtext project?]

```
from torchtext import data
from torchtext import datasets
from torchtext.vocab import GloVe
import torch

# set up fields
TEXT = data.Field(lower=True, include_lengths=True, batch_first=True)
LABEL = data.Field(sequential=False)

train, test = datasets.IMDB.splits(TEXT, LABEL)

# build the vocabulary
TEXT.build_vocab(train ) #get rid of vectors=GloVe(name='6B', dim=300)
LABEL.build_vocab(train)

batch_size = 1000
train_iter, test_iter = data.BucketIterator.splits(
    (train, test), batch_sizes=(batch_size,batch_size),
    shuffle=False,device=-1)

print "train iter shuffle",train_iter.shuffle
print "test iter shuffle",test_iter.shuffle

for idx,batch in enumerate(train_iter):
    batch_size = batch.batch_size
    dataset_object = batch.dataset
    dataset_name = dataset_object.name
    is_train = batch.train
    
    # How do I get movie title / index into the dataset / file name here?
    
    for review,label in zip(batch.text[0],batch.label):
        print label
        print review
```

**Comment by jekbradbury** [comment]
You would want to create a custom `Dataset` that works like the existing `datasets.IMDB` but adds a `Field` for the additional metadata you need.
