### ISSUE TITLE
MultiNLI dataset

### ISSUE THREAD

**Issue by keon** [pytorch/text#187]
I am using MultiNLI dataset for a personal use by adding it on top of torchtext (by using the code borrowed from SNLI dataset).
Do you have plan to add the dataset? in that case I can make a PR :)
MultiNLI -> https://www.nyu.edu/projects/bowman/multinli/

**Comment by nelson-liu** [comment]
I think a MultiNLI dataset would be nice, especially since torchtext has SNLI.
