### ISSUE TITLE
Introduce max_len argument in Field?

### ISSUE THREAD

**Issue by windweller** [pytorch/text#190]
An easy to implement feature for `Field` class is to introduce a max_len argument: all text entries longer than a certain length can be thrown out. Seems trivial but good to have :)

Another small question, if we want to load in custom word vectors like from the [Polyglot project](https://sites.google.com/site/rmyeid/projects/polyglot) or [Bio-Medical embeddings](http://bio.nlplab.org/), then how should we pass them in?

```
TEXT.build_vocab(train, vectors="other_vectors")
```

**Comment by skurzhanskyi** [comment]
Adding `max_len` in `Field` sound like a great feature!
Are there any possibilities do throw out now?

**Comment by zhangguanheng66** [comment]
> Adding `max_len` in `Field` sound like a great feature!
> Are there any possibilities do throw out now?

what you mean throw out?

**Comment by skurzhanskyi** [comment]
I actually mean to add `man_len` to be sure, that your sequence no longer
than it. You often need it not to get memory error 😉

**Comment by zhangguanheng66** [comment]
But we don't want to accidentally set up a limit for the input text length, right? Users may not realize  that we automatically cut their inputs.

**Comment by skurzhanskyi** [comment]
Of, course. I just asked how I could do it manually. But it would be useful to have a possibility to set `max_len` in `Filed` constructor, as @windweller  wrote.

**Comment by skurzhanskyi** [comment]
Thanks, @mttk. As you wrote, I decided to manually redefine pad (to take into account `mal_len`). Seems to be useful to have the possibility to set it in `Field`.
