### ISSUE TITLE
torchtext.data.Field

### ISSUE THREAD

**Issue by pandya6988** [pytorch/text#1920]
## ❓ Questions and Help

**Field, TabularDataset, BucketIterator**

will you bring these features back? or is there any alternative functions for these?

**Comment by Nayef211** [comment]
Refer to https://github.com/pytorch/text/issues/664 for the plans to revamp the torchtext library (which contains the motivation behind why these features were deprecated). https://github.com/pytorch/text/issues/1661#issuecomment-1075786324 has alternatives if these features are a must for your usecase.
