### ISSUE TITLE
MacOS Nightly Failure with 2022-10-04 nightly release (258a3562b5f658ba945c43ad6406630c455176bc)

### ISSUE THREAD

**Issue by weiwangmeta** [pytorch/text#1926]
## 🐛 Bug

**Describe the bug** A clear and concise description of what the bug is.
The following unit test failed: 
torchtext_unittest/datasets/test_iwslt2016.py::TestIWSLT2016::test_iwslt2016_178_train FAILED [ 41%]

The error stack is long, but essentially: 
It seems to have parser issues https://app.circleci.com/pipelines/github/pytorch/text/6871/workflows/e488c26f-0ae6-4aaf-b3fa-6fffd0c36967/jobs/237395?invite=true#step-108-1736 

**To Reproduce** Steps to reproduce the behavior:

1. Go to this page: https://app.circleci.com/pipelines/github/pytorch/text/6871/workflows/e488c26f-0ae6-4aaf-b3fa-6fffd0c36967/jobs/237395 and errors are presented in the page

**Comment by Nayef211** [comment]
Hey @weiwangmeta, thanks for raising this issue. We are aware of this flaky test failure which is likely caused by randomness when generating test data. As a next step, I will try adding some sort of seed to see if that helps resolve the issue.

**Comment by weiwangmeta** [comment]
Thank you @Nayef211. Indeed, the failure is flaky. I can see latest nightly this test no longer fails (https://hud.pytorch.org/hud/pytorch/text/nightly). I am closing this issue now. Will re-open if needed.
