### ISSUE TITLE
TorchText nightly release is based on PyTorch 1.13.0 official release

### ISSUE THREAD

**Issue by ejguan** [pytorch/text#1979]
## 🐛 Bug

**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

```
pip install --pre torchtext -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
```

A `torch-1.13.0` binary will be installed.

**Expected behavior** A clear and concise description of what you expected to happen.

Expected `torch-1.14.0` installed

**Screenshots** If applicable, add screenshots to help explain your problem.

**Environment**

Empty environment and install from scratch

cc: @Nayef211 @abhinavarora @osalpekar

**Comment by xuzhao9** [comment]
I can reproduce this problem as it blocks torchbench nightly CI: https://github.com/pytorch/benchmark/actions/runs/3370045990/jobs/5596893302

**Comment by Nayef211** [comment]
@abhinavarora can you take a look?

**Comment by Nayef211** [comment]
Should be resolved by https://github.com/pytorch/text/pull/1981. Let's wait until the new nightly to confirm before closing this issue.

**Comment by ejguan** [comment]
I think this issue has been resolved based on the nightly CI from torchdata. Closing now
