### ISSUE TITLE
Informative __str__, __repr__ of Batch

### ISSUE THREAD

**Issue by mttk** [pytorch/text#198]
It might be useful to have a more verbose / formatted output of `str()` for a `Batch` object (when compared to using `vars()`).

To this end, I wrote a short update that produces this:
```
[torchtext.data.batch.Batch of size 16 from IMDB]
	[.text]:[torch.LongTensor of size 143x16]
	[.label]:[torch.LongTensor of size 16]
```
This deviates a bit from the standard output of `_tensor_str`, but is short & good enough. Open points where I'd like input:

1. Handling empty Batches (data == None) -- what's the str() output? ex. 'Empty torchtext.data.batch.Batch instance'
2. Display tensor summary (as in `_tensor_str`) forall fields? I find that this makes the output cluttered and the indentation gets messed up easily. 
3. Does this warrant a PR?

**Comment by jekbradbury** [comment]
I like this; a PR would be great! I agree with your proposal for empty batches in (1) and also agree with using only the type descriptors rather than the full tensor summaries.

**Comment by mttk** [comment]
Cool, I'm closing this, will get a PR up in a day & reference this.
