### ISSUE TITLE
Bug in tokenization during Field preprocessing

### ISSUE THREAD

**Issue by mupavan** [pytorch/text#20]
Refer to line - https://github.com/pytorch/text/blob/master/torchtext/data.py#L135. 

```python
        if self.sequential and isinstance(x, str):
```

Note that in python2, `isinstance(x, str)` returns `False` when x is `unicode`. Took a while to realize why tokenization was not happening for me. I guess a simple fix would be `isinstance(x, six.string_types)`. Shall I issue a PR (though this is an extremely tiny change)?

**Comment by soumith** [comment]
go ahead and issue a PR. thanks for tracking the bug down.
