### ISSUE TITLE
Torchtext nightly version not available for Linux from December 01, 2022

### ISSUE THREAD

**Issue by ajindal1** [pytorch/text#2005]
## 🐛 Bug

**Describe the bug**
Torchtext nightly 0.15.0 had a CPU version for linux released daily till 11/30, but has not been released since then. It can be checked on the pytorch nighly link(https://download.pytorch.org/whl/nightly/cu116/torch_nightly.html). Is there any plan to make this package available for Linux?

**To Reproduce**

1. Go to https://download.pytorch.org/whl/nightly/cu116/torch_nightly.html
2. Search for torchtext-0.15.0.dev20221209
3. You will only find win_amd64.whl, there are no linux_x86_64.whl files

**Expected behavior**
These files should be available:

torchtext-0.15.0.dev20221209%2Bcpu-cp310-cp310-linux_x86_64.whl
torchtext-0.15.0.dev20221209%2Bcpu-cp37-cp37m-linux_x86_64.whl
torchtext-0.15.0.dev20221209%2Bcpu-cp38-cp38-linux_x86_64.whl
torchtext-0.15.0.dev20221209%2Bcpu-cp39-cp39-linux_x86_64.whl

**Environment**
- PyTorch Version (e.g., 1.0): 1.14.0 (nightly)
- OS (e.g., Linux): Ubuntu 20.04
- How you installed PyTorch (`conda`, `pip`, source): python -m pip install --pre torchtext==0.15.0.dev20221209 -f https://download.pytorch.org/whl/nightly/cu116/torch_nightly.html
- Build command you used (if compiling from source):
- Python version: 3.8
- CUDA/cuDNN version: 11.6
- GPU models and configuration: Nvidia, Tesla M60
- Any other relevant information:

**Additional context** Add any other context about the problem here.
- THe below command used to work 10 days but stopped working since 12/01 for Ubuntu 20.04
python -m pip install --pre torchtext==0.15.0.dev{DATE-%YYYYMMDD} -f https://download.pytorch.org/whl/nightly/cu116/torch_nightly.html
- Example
python -m pip install --pre torchtext==0.15.0.dev20221209 -f https://download.pytorch.org/whl/nightly/cu116/torch_nightly.html

**Comment by Nayef211** [comment]
Hi @ajindal1. You should be able to find binaries for CPU builds within https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html. The link you posted earlier is generally meant for CUDA binaries. @osalpekar made a change recently so that the CPU nightlies are also published to https://download.pytorch.org/whl/nightly/cu116/torch_nightly.html moving forward.
