### ISSUE TITLE
Fix CodeQL failure in CI

### ISSUE THREAD

**Issue by Nayef211** [pytorch/text#2044]
## 🐛 Bug
The Code QL CI job has been failing for some time now with the following error:
```
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.1build1' (package: distro-info)
```

@osalpekar had thoughts on  some avenues of investigation
> It looks like the version is correct at first, but then ends up being invalid later on in the build. I'm not sure what the `--user` flag does so that could be one thing to look into, and setting `BUILD_VERSION` explicitly with the expected version could also be another thing to explore.

Example failure: https://github.com/pytorch/text/actions/runs/4076465993/jobs/7024236994

**Comment by rshraga** [comment]
Taking a look today
