### ISSUE TITLE
how to build  torchtext in cpp wiht  cmake?

### ISSUE THREAD

**Issue by mullerhai** [pytorch/text#2072]
HI, guys, I want to use torchtext with liborch  in cpp  like  cmake build torchvision in cpp, but I has try ,but meet some error in windows system,I don't know  why  some dependency subdirectory is empty, how to  build it  then include with cpp ?
thanks

````
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.20348.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.34.31942.0
-- The CXX compiler identification is MSVC 19.34.31942.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at third_party/CMakeLists.txt:8 (add_subdirectory):
  The source directory

    C:/Apps/text-main/third_party/re2

  does not contain a CMakeLists.txt file.


CMake Error at third_party/CMakeLists.txt:9 (add_subdirectory):
  The source directory

    C:/Apps/text-main/third_party/double-conversion

  does not contain a CMakeLists.txt file.


CMake Error at third_party/CMakeLists.txt:10 (add_subdirectory):
  The source directory

    C:/Apps/text-main/third_party/sentencepiece

  does not contain a CMakeLists.txt file.


CMake Error at third_party/CMakeLists.txt:11 (add_subdirectory):
  The source directory

    C:/Apps/text-main/third_party/utf8proc

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
PS C:\Apps\text-main\build>

````

**Comment by Nayef211** [comment]
Hey @mullerhai. Did you try running `git submodule update --init --recursive` after cloning the `torchtext` repo? We also have examples of how to build `libtorchtext` library in [this folder](https://github.com/pytorch/text/tree/main/examples/libtorchtext).

**Comment by mullerhai** [comment]
> Hey @mullerhai. Did you try running `git submodule update --init --recursive` after cloning the `torchtext` repo? We also have examples of how to build `libtorchtext` library in [this folder](https://github.com/pytorch/text/tree/main/examples/libtorchtext).

ohh,thanks ,does the libtorchtext has the full feature could use  like in python ?

**Comment by Nayef211** [comment]
> ohh,thanks ,does the libtorchtext has the full feature could use like in python ?

`libtorchtext` has all the components that are written in C++. You can find all included cpp files in the CMakeLists.txt file [here](https://github.com/pytorch/text/blob/main/torchtext/csrc/CMakeLists.txt#L4-L16).

**Comment by mullerhai** [comment]
> Hey @mullerhai. Did you try running `git submodule update --init --recursive` after cloning the `torchtext` repo? We also have examples of how to build `libtorchtext` library in [this folder](https://github.com/pytorch/text/tree/main/examples/libtorchtext).

these example  can not execute in windows,please show some example could  work in windows 11,thanks
