### ISSUE TITLE
Document BucketIterator sort_within_batch

### ISSUE THREAD

**Issue by bastings** [pytorch/text#209]
Hi there,

I'm wondering what would be a typical use of `BucketIterator` in combination with `torch.nn.utils.rnn.pack_padded_sequence`. It seems this should be a common use case.

For the encoder, the batch would have to be sorted e.g. like this:

```train_iter, val_iter = data.BucketIterator.splits(
        (train_data, val_data), batch_size=32, device=0,
        sort_key=lambda x: len(x.src), sort_within_batch=True)```

If this is indeed quite typical, shall we add it to either test/ or the README?

**Comment by jekbradbury** [comment]
Yes, that's right.

**Comment by abhinavarora** [comment]
Closing issue as we have gotten rid of iterators and the issue is no more relevant. 
#1537
