### ISSUE TITLE
TabularDataset not working with new lines in strings

### ISSUE THREAD

**Issue by pmandera** [pytorch/text#210]
`TabularDataset` breaks if there are new lines in strings.

This is a direct consequence of how the data is read:
https://github.com/pytorch/text/blob/c5ce46051508a919eb830deca4187c749727151b/torchtext/data/dataset.py#L164

Perhaps using `csv` from python standard library would be a solution?

**Comment by keitakurita** [comment]
I'm willing to file a pull request resolving this issue.

I have a question regarding [this line](https://github.com/pytorch/text/blob/db2e26c490d7d70db3edabf8ddc301275845d635/torchtext/data/example.py#L39) thought.
I don't quite understand what this comment means, as well as all the subsequent encoding and decoding. This doesn't appear in the `fromTSV` method either, so I'm not convinced that I need to replicate this functionality. 
Could someone tell me whether I can drop this, and if not, why?

**Comment by jekbradbury** [comment]
Closed in #214
