### ISSUE TITLE
Implementing __contains__ for vocab.Vectors class

### ISSUE THREAD

**Issue by saeeddhqan** [pytorch/text#2140]
## 🚀 Feature

Isn't it better to implement \_\_contains\_\_ for Vectors class? In this way, one can easily find out whether a vocab is in the self.itos or not.

**Comment by joecummings** [comment]
Thanks for opening an issue @saeeddhqan! If you want to propose this feature, we can help with testing and approving.

**Comment by saeeddhqan** [comment]
I created the PR. Looking forward to hear from you!
