### ISSUE TITLE
Loading vectors into a GPU

### ISSUE THREAD

**Issue by saeeddhqan** [pytorch/text#2145]
## 🚀 Feature

Is there any way for loading vectors based on device with torchtext.vocab.Vectors class?

**Comment by saeeddhqan** [comment]
So, we don't need to change the current implementation to do so, right?

**Comment by joecummings** [comment]
Nope! You can just do:

```
vectors = Vectors()
vectors.to(device="cuda")
```

**Comment by saeeddhqan** [comment]
thanks!
