### ISSUE TITLE
404 Client Error in IWSLT2017 and IWSLT2016

### ISSUE THREAD

**Issue by nonconvexopt** [pytorch/text#2189]
## 🐛 Bug

```
from torchtext.vocab import build_vocab_from_iterator

special_symbols = ['<unk>', '<pad>', '<bos>', '<eos>']

def yield_tokens(data_iter: Iterable) -> List[str]:
    for data_sample in data_iter:
        yield token_transform(data_sample)

train_iter = IWSLT2017(split="train")
build_vocab_from_iterator(yield_tokens(train_iter), min_freq=1, specials=special_symbols, special_first=True)
```

When I run above code, it shows below error:
`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://drive.google.com/uc?id=12ycYSzLIG253AFN35Y6qoyf9wtkOjakp`

I think some download link for the data is broken.

**Comment by rsonthal** [comment]
I just encountered this error on Google Colab.

`!pip install 'portalocker'`

`import torch`
`import torch.nn as nn`
`import numpy as np`
`import matplotlib.pyplot as plt`
`from tqdm import tqdm`

`import torchtext`

`dataset = torchtext.datasets.IWSLT2017(root='.data', split='train', language_pair=('de', 'en'))`

`next(iter(dataset))`

> HTTPError: 404 Client Error: Not Found for url: https://drive.google.com/uc?id=12ycYSzLIG253AFN35Y6qoyf9wtkOjakp
This exception is thrown by __iter__ of GDriveReaderDataPipe(skip_on_error=False, source_datapipe=OnDiskCacheHolderIterDataPipe, timeout=None)
