### ISSUE TITLE
Should SequenceTaggingDataset be merged with TabularDataset?

### ISSUE THREAD

**Issue by keitakurita** [pytorch/text#224]
I read the code concerning SequenceTaggingDataset and felt that the API implemented there was a subset of the API for the TabularDataset where one of the columns was the text and the other column was the tag for each word in the text.
Is there any reason to maintain the SequenceTaggingDataset as a separate class? I feel that an example of sequence tagging using the TabularDataset would provide more clarity for the user. 
If this change seems ok I would be happy to file a pull request for it :)

**Comment by jekbradbury** [comment]
If you can get a PR to work that doesn't break tests for either TabularDataset or SequenceTaggingDataset examples, that would be welcomed; as it is I think the key difference is that SequenceTaggingDataset separates words by newlines and examples/sentences by double-newlines, while TabularDatasets separate examples by newlines.

**Comment by abhinavarora** [comment]
Closing this issue as we have gotten rid of legacy datasets in the latest version.
#1537
