### ISSUE TITLE
Field.build_vocab breaks when using dict fields to load CSV

### ISSUE THREAD

**Issue by notnami** [pytorch/text#225]
Hi!

Using the master version of this repo, I tried to create a `TabularDataset` using a `dict` to load specific columns from a CSV (#217). While the `TabularDataset` object was initialised fine (unlike the PyPI version, where using a dict for fields ends in a crash), trying to build vocab using those fields does not in fact build the vocab.

Example:

```
sentence = data.Field(lower=True, eos_token='<END>',
                    include_lengths=True, batch_first=True,
                    tokenize=word_tokenize)
fields = {'sentence': ('sentence', sentence), 
              ... }  # some other fields here 
train_data = data.TabularDataset(path=str(train_path), format='csv',
                             fields=fields, skip_header=False)
sentence.build_vocab(train_data, max_size=80000,
                     vectors=GloVe(name='6B', dim=100))  # doesn't actually build the vocab
```

The resulting vocab only has the 3 tokens UNK, PAD, and EOS, and nothing else.

I have found other bugs on the master version, so perhaps this functionality is still in progress and I shouldn't attempt to use it yet?

**Comment by keitakurita** [comment]
Thanks for the notice! The functionality should be complete, but since this feature was only created a few days ago, there might be a few rough edges.
I'll try and fix this bug, and any other bugs you find ASAP, so it would be great if you could raise the bugs you have found as issues! Sorry for the inconvenience, and thanks for the help!

**Comment by keitakurita** [comment]
@notnami 
Could you try building the vocabulary using the current master branch? I tested building the vocabulary for a small synthetic example and confirmed that it worked. 
If the current master doesn't work, could you provide a minimal, self-contained working example (including data)?

**Comment by notnami** [comment]
Yes, it works. Sorry it took me over a month to get back.
