### ISSUE TITLE
error super(type, obj) with imdb.py after solving encoding 'utf-8' issue 

### ISSUE THREAD

**Issue by iamyihwa** [pytorch/text#226]
Hello, 
when loading the imdb dataset, since i am using python 3, have replaced the  open to open(file, encoding = 'utf8'). 
However after that this error arises. 
I have no idea on how to solve this issue. 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-46-30850761a448> in <module>()
      1 IMDB_LABEL = data.Field(sequential=False)
----> 2 splits = torchtext.datasets.IMDB.splits(TEXT, IMDB_LABEL, 'data/')

~/anaconda3/envs/fastai/lib/python3.6/site-packages/torchtext/datasets/imdb.py in splits(cls, text_field, label_field, root, train, test, **kwargs)
     50                 Dataset.
     51         """
---> 52         return super(IMDB, cls).splits(
     53             root=root, text_field=text_field, label_field=label_field,
     54             train=train, validation=None, test=test, **kwargs)

TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by keon** [comment]
Did you change any environment or code besides `encoding='utf8'`?
I  am having trouble reproducing this error.

**Comment by keitakurita** [comment]
@iamyihwa 
Are you running the code in a Jupyter notebook and have not restarted the kernel? If so, there's a chance that your kernel is referencing the wrong IMDB dataset class when super(IMDB, self) is being called, causing an error.

**Comment by shirishr** [comment]
I am experiencing exact same errors.
From a FastAi notebook a cell executes:
splits = torchtext.datasets.IMDB.splits(TEXT, IMDB_LABEL, 'data/')
This caused the encoding issue at line 32 of the imdb.py which was:

with open(fname, 'r') as f:

I changed this line to 

**with open(fname, ''r', encoding="utf-8") as f:**

Thereafter I got same error that @iamyihwa got

**TypeError: super(type, obj): obj must be an instance or subtype of type**

I confirm that I had restarted the kernel.

**Comment by shirishr** [comment]
@iamyihwa  and all others who may read this.

To fix this error, clone this repository i.e. https://github.com/pytorch/text

and install torchtext from here (python setup.py install --force)

It has updates that release 2.0.1 does not cover. (updates about encoding are not limited to imdb.py but involve dataset.py, field.py etc.)

I can can confirm that after this install all my errors encoding as well as **TypeError: super(type, obj): obj must be an instance or subtype of type**  went away

**Comment by zhangguanheng66** [comment]
Feel free to re-open the issue if you still have question.
