### ISSUE TITLE
Load data from a list of lists and build a vocabulary

### ISSUE THREAD

**Issue by Spider101** [pytorch/text#23]
I have a dataset in which each sample is essentially a sequence of sentences. I have parsed the data to form a list of lists (which if I convert to a numpy array would give an ndarray of shape (M,N) ). Most of the functionality from what I could see is for loading dataset directly from files. Is there any way I could load the data from such a list of lists or a numpy array/pytorch Tensor and then use the build_vocab method on that?

**Comment by jekbradbury** [comment]
Is the number of sentences in each sample fixed? Because if not, torchtext doesn't have a good way to do this right now (if yes, use Example.from_list in a custom Dataset). There might be a way to hack up something that would work for the variable-number-of-sentences case, but it would involve subclassing Field, Example, _and_ Dataset and that's probably not worth it.

**Comment by Spider101** [comment]
Yes, the number of sentences in each sequence is fixed but the number of words in each sentence is variable. So once I convert the list into Examples, is there any streamlined way to convert the Examples into, say, a TabularDataset that I can iterate over?

**Comment by jekbradbury** [comment]
OK, if the number of sentences per example is fixed, then use a single `Example` object per sequence with one column for each sentence. You can subclass `Batch` like this:
```
class SequentialBatch(data.Batch):
    def __getitem__(self, index):
        return getattr(self, 'sentence' + str(index))
```
then create `Example`s like this:
```
ex = SequentialExample.fromlist(raw_list_of_sentences, [text_field] * len(raw_list_of_sentences))
```
then build an iterator as normal and use the batches like this
```
for sentence_index in range(num_sentences):
    do_something(batch[sentence_index])
```

**Comment by erip** [comment]
I think this can be closed. As of 0.9.0 there's a `build_vocab_from_iterator` which accepts a `List[List[str]]`.

**Comment by Nayef211** [comment]
> I think this can be closed. As of 0.9.0 there's a `build_vocab_from_iterator` which accepts a `List[List[str]]`.

Thanks for identifying stale issues @erip. Moving forward, we should make an effort to clean up non-relevant issues and PRs. I will create an issue for this soon 😃
