### ISSUE TITLE
AssertionError:  Found no NVIDIA driver on your system.

### ISSUE THREAD

**Issue by Coolnesss** [pytorch/text#236]
Hey, I'm working on machine with no GPU, trying to load one of the Amazon reviews sentiment datasets into torchtext. With the following MCVE 

```python
filepath = './data/reviews_Amazon_Instant_Video_5.json'
TEXT = data.Field(sequential=True, lower=True)

dataset = data.TabularDataset(
    path=filepath, format='json',
    fields={'reviewText': ('text', TEXT),
            'overall': ('labels', data.Field(sequential=False, use_vocab=False, tensor_type=torch.DoubleTensor))})

TEXT.build_vocab(dataset)
iterator = data.Iterator(dataset, 128, shuffle=True)

next(iter(iterator))
```

I get 

```
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
```

I feel like the default assumption should be to use the CPU, right? Since I didn't specify a device anywhere.

I can fix this by explicitly setting the device to `-1` in the `Iterator`:
```python
iterator = data.Iterator(dataset, 128, device=-1, shuffle=True)
```

Is this intended behavior?

**Comment by jekbradbury** [comment]
Yeah, the default assumption is to use `device=0`, but it should probably gate that behind a `torch.cuda.is_available()`.

**Comment by Coolnesss** [comment]
Maybe change this line https://github.com/pytorch/text/blob/c839a7934930819be7e240ea972e4d600966afdc/torchtext/data/iterator.py#L92 

to something like 

```python
self.device = device
if not torch.cuda.is_available() and self.device is None: 
  self.device = -1
```

Up for a pull request for this, or is the solution incomplete?

**Comment by jekbradbury** [comment]
Yes, that would be great.

**Comment by kamrankausar** [comment]
preprocessed data was found and loaded
Traceback (most recent call last):
  File "train_word_embeddings_2.py", line 61, in <module>
    neg_loss = neg_loss.cuda()
  File "/home/kamran/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 305, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/kamran/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 202, in _apply
    module._apply(fn)
  File "/home/kamran/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in _apply
    param_applied = fn(param)
  File "/home/kamran/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 305, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/kamran/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 192, in _lazy_init
    _check_driver()
  File "/home/kamran/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 102, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
