### ISSUE TITLE
Error on loading json data

### ISSUE THREAD

**Issue by Spider101** [pytorch/text#24]
The following code is giving me an `AttributeError: 'list' object has no attribute 'items'` error:

```python
sent_feats = data.Field()
sequences = data.TabularDataset(path=captions_path, format="json", \
                    fields=[{'caption' : ("sentences", sent_feats)}])
```

My dict has the following structure:

```{ seq_id : { caption_id : { caption: "" } } }```

Is there any syntactical error I am making?

**Comment by jekbradbury** [comment]
Yeah, as mentioned in the other thread torchtext doesn't currently support samples which consist of a variable number of variable-length sequences, so you can't easily load a nested JSON like this.

**Comment by Spider101** [comment]
Ok, thank you. I think I will use the list of lists approach mentioned in the other thread.
