### ISSUE TITLE
A batch object created by fromvars does not have "fields" attribute

### ISSUE THREAD

**Issue by jihunchoi** [pytorch/text#247]
When making a batch object, the value of the `fields` attribute is set in its `__init__` method.
However, when created with `fromvars` class method, `fields` attribute is not set since the method first creates an empty object and then add information.
It should be modified to be analogous with the one created by `__init__` method.
It can be simply done by adding the following after https://github.com/pytorch/text/blob/master/torchtext/data/batch.py#L36:
```
batch.fields = dataset.fields.keys()
```

This kind of object creation is found when using BPTT iterator. Without `fields` attribute, printing a batch object is not possible due to https://github.com/pytorch/text/blob/master/torchtext/data/batch.py#L49.

**Comment by jihunchoi** [comment]
I've sent a quick PR #248 to solve this issue.

**Comment by jekbradbury** [comment]
Closed in #248
