### ISSUE TITLE
data.Iterator() does not support cpu operation

### ISSUE THREAD

**Issue by minghao-wu** [pytorch/text#249]
I was testing https://github.com/pytorch/text/blob/master/test/sequence_tagging.py on my macbook air.

I found that this script always terminates at Line 44.

The reason why this happens is that the data.Iterator() only support the machine with CUDA installed. If your computer is CPU-only, some error will be reported.

I ran this script on my GPU server (Titan X, CUDA 8, cuDNN 6) and everything works.

The version of torchtext on both machines is 0.2.1

Hopefully someone can fix it.

> ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-eb15e61c2f5f> in <module>()
----> 1 batch = next(iter(train_iter))
      2 
      3 print("words", batch.word)
      4 print("udtags", batch.udtag)
      5 print("ptbtags", batch.ptbtag)

~/anaconda3/lib/python3.6/site-packages/torchtext/data/iterator.py in __iter__(self)
    178                         minibatch.sort(key=self.sort_key, reverse=True)
    179                 yield Batch(minibatch, self.dataset, self.device,
--> 180                             self.train)
    181             if not self.repeat:
    182                 raise StopIteration

~/anaconda3/lib/python3.6/site-packages/torchtext/data/batch.py in __init__(self, data, dataset, device, train)
     20                 if field is not None:
     21                     batch = [x.__dict__[name] for x in data]
---> 22                     setattr(self, name, field.process(batch, device=device, train=train))
     23 
     24     @classmethod

~/anaconda3/lib/python3.6/site-packages/torchtext/data/field.py in process(self, batch, device, train)
    185         """
    186         padded = self.pad(batch)
--> 187         tensor = self.numericalize(padded, device=device, train=train)
    188         return tensor
    189 

~/anaconda3/lib/python3.6/site-packages/torchtext/data/field.py in numericalize(self, arr, device, train)
    314                 arr = arr.contiguous()
    315         else:
--> 316             arr = arr.cuda(device)
    317             if self.include_lengths:
    318                 lengths = lengths.cuda(device)

~/anaconda3/lib/python3.6/site-packages/torch/_utils.py in _cuda(self, device, async)
     59         if device is None:
     60             device = -1
---> 61     with torch.cuda.device(device):
     62         if self.is_sparse:
     63             new_type = getattr(torch.cuda.sparse, self.__class__.__name__)

~/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py in __enter__(self)
    205         if self.idx is -1:
    206             return
--> 207         self.prev_idx = torch._C._cuda_getDevice()
    208         if self.prev_idx != self.idx:
    209             torch._C._cuda_setDevice(self.idx)

AttributeError: module 'torch._C' has no attribute '_cuda_getDevice'

**Comment by mttk** [comment]
Can you please try setting `device=-1` in line 42: https://github.com/pytorch/text/blob/master/test/sequence_tagging.py#L42 and re-running?

**Comment by ykasimov** [comment]
I have a similar issue.
`AssertionError                            Traceback (most recent call last)
<ipython-input-14-b346936090f4> in <module>()
----> 1 for batch in train_iter:
      2     print(batch)
      3     break

/usr/local/lib/python3.6/site-packages/torchtext/data/iterator.py in __iter__(self)
    178                         minibatch.sort(key=self.sort_key, reverse=True)
    179                 yield Batch(minibatch, self.dataset, self.device,
--> 180                             self.train)
    181             if not self.repeat:
    182                 raise StopIteration

/usr/local/lib/python3.6/site-packages/torchtext/data/batch.py in __init__(self, data, dataset, device, train)
     20                 if field is not None:
     21                     batch = [x.__dict__[name] for x in data]
---> 22                     setattr(self, name, field.process(batch, device=device, train=train))
     23 
     24     @classmethod

/usr/local/lib/python3.6/site-packages/torchtext/data/field.py in process(self, batch, device, train)
    185         """
    186         padded = self.pad(batch)
--> 187         tensor = self.numericalize(padded, device=device, train=train)
    188         return tensor
    189 

/usr/local/lib/python3.6/site-packages/torchtext/data/field.py in numericalize(self, arr, device, train)
    307                 arr = self.postprocessing(arr, None, train)
    308 
--> 309         arr = self.tensor_type(arr)
    310         if self.sequential and not self.batch_first:
    311             arr.t_()

/usr/local/lib/python3.6/site-packages/torch/cuda/__init__.py in _lazy_new(cls, *args, **kwargs)
    382 @staticmethod
    383 def _lazy_new(cls, *args, **kwargs):
--> 384     _lazy_init()
    385     # We need this method only for lazy init, so we can remove it
    386     del _CudaBase.__new__

/usr/local/lib/python3.6/site-packages/torch/cuda/__init__.py in _lazy_init()
    139         raise RuntimeError(
    140             "Cannot re-initialize CUDA in forked subprocess. " + msg)
--> 141     _check_driver()
    142     torch._C._cuda_init()
    143     torch._C._cuda_sparse_init()

/usr/local/lib/python3.6/site-packages/torch/cuda/__init__.py in _check_driver()
     60 Found no NVIDIA driver on your system. Please check that you
     61 have an NVIDIA GPU and installed a driver from
---> 62 http://www.nvidia.com/Download/index.aspx""")
     63         else:
     64             # TODO: directly link to the alternative bin that needs install

AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx`

 
I have set the `device=-1`.

Here is how I create iterator:
option 1:
`dataset_iter = data.Iterator(
        dataset, batch_size=batch_size, device=-1,
        train=train, shuffle=shuffle, repeat=repeat,
        sort=False, sort_within_batch=True, sort_key=lambda x: len(x.comment_text)
    )`

Option 2:
`train_iter, val_iter, test_iter = data.Iterator.splits(
        (train_tabular, validation_tabular, test_tabular), sort_key=lambda x: len(x.comment_text), 
        batch_sizes=(32, 256, 256), device=-1, 
        sort_within_batch=True, repeat=False)`

**Comment by mttk** [comment]
@ykasimov Could you please paste your pytorch version? Also, did you install pytorch-cpu? In case you don't have a GPU / NVIDIA drivers, I'd assume that's what you want.

**Comment by ykasimov** [comment]
@mttk  Pytorch version: 0.3.1.post2
I was running RNN without using torchtext on CPU. It worked fine. 
I removed pytorch and installed pytorch-cpu. I reinstalled torchtext, but I still have the same error.

**Comment by jekbradbury** [comment]
I believe this has been fixed in torchtext master? Can you try downloading the source for this repository and running `python setup.py develop` inside?

**Comment by ykasimov** [comment]
@jekbradbury I cannot install it this way. After I try to import I get an error 'no such module'
Is it the same as if I install with 'pip install git+https://github.com/pytorch/text.git' ?

**Comment by minghao-wu** [comment]
@mttk 
problem fixed, thank you.
