### ISSUE TITLE
load_vectors does not fail gracefully when the requested #dimensions is not available

### ISSUE THREAD

**Issue by mattmacy** [pytorch/text#25]
While testing out my [SQUAD loader](https://github.com/mattmacy/text/blob/squad/torchtext/datasets/squad.py) I discovered that no matter what dimension is requested  for glove.42B load_vectors will download the 300d vectors. And if it's not 300 it will download it over and over ad infinitum:

downloading word vectors from http://nlp.stanford.edu/data/glove.42B.300d.zip
extracting word vectors into .data_cache
downloading word vectors from http://nlp.stanford.edu/data/glove.42B.300d.zip
extracting word vectors into .data_cache
downloading word vectors from http://nlp.stanford.edu/data/glove.42B.300d.zip
extracting word vectors into .data_cache
downloading word vectors from http://nlp.stanford.edu/data/glove.42B.300d.zip

If you're busy I can fix it myself, but it seems pretty silly to have an option to the API that doesn't actually work.

**Comment by mattmacy** [comment]
For some reason I thought that < 300d vectors were available.

**Comment by jekbradbury** [comment]
<300d word vectors are available for other glove vector datasets, I think. I'll look into this tomorrow though; you're right that this is clearly not the right behavior.

**Comment by mattmacy** [comment]
glove.6B has 50/100/200/300
