### ISSUE TITLE
epoch() of BPTTIterator?

### ISSUE THREAD

**Issue by shihan9** [pytorch/text#256]
hi, it seems the `__iter__` in `BPTTIterator` doesn't increment `self.iterations` so function `epoch` returned is always 0.

**Comment by mttk** [comment]
Will be fixed when #259 gets merged.

**Comment by shihan9** [comment]
thanks. this BPTTIterator looks like specially designed for RNN-based language modeling. is it possible to have it include a NGramIterator, which could be used for CNN-based LM? i would like to help if it sounds right.

**Comment by mttk** [comment]
Paging @jekbradbury
