### ISSUE TITLE
wordvec of unk token

### ISSUE THREAD

**Issue by ruotianluo** [pytorch/text#275]
https://github.com/pytorch/text/blob/master/torchtext/vocab.py#L242

When the word is in the dictionary, the returned is a one-dim vector, while unk vector is a two-dim vector.

I assume this is not expected, right?

**Comment by jekbradbury** [comment]
Probably the one-dim vector. Does nothing else in the codebase currently rely on this `__getitem__` method?

**Comment by domaala** [comment]
@jekbradbury I've been searching through the codebase, but I wasn't able to find anything. It seems that after the vectors are finally loaded, it's up to user's model to deal with it. I'll see whether something breaks when I change this.
