### ISSUE TITLE
Feature: input, target = batch

### ISSUE THREAD

**Issue by keitakurita** [pytorch/text#285]
Thanks, as always, for the amazing work on this library!

I've noticed that various libraries (including fast.ai and torchsample) expect to be able to iterate over each batch generated from a DataLoader like
```python
for batch in dataloader:
    input, target = batch
```
where `input` is the input to a model and `target` is the target variable(s).

I thought it would be nice if the batches generated by the torchtext data loaders could more easily and intuitively interface with this kind of functionality. This would also make code using torchtext more independent of the dataset. 
The question is, how to distinguish between input and target variables.
Here's my idea: specify whether each field is a target field using a keyword argument `target_field` (or something to that effect) when initializing the `Field` object for each field. This will enable the batch object to know which fields to return as inputs and which to return as targets.

My question is, does this seem like a reasonable feature/API? If so, I would be happy to implement it.

**Comment by mttk** [comment]
There's a `LabelField` implementation, however it's currently just a shallow wrapper (setting `unk_init` and `sequential` to None. It would be reasonable to extend it with a `target` flag.

What's your idea of combining multi-input datasets (e.g. SNLI)? `input` could be a tuple / namedtuple, or the batch could unpack into multiple variables.

Anyway, all in all seems reasonable to me.

**Comment by keitakurita** [comment]
(If I'm understanding your question correctly) I think returning a tuple would be the most consistent with the expectations of the APIs I mentioned earlier and would be the easiest to deal with.
For a batch with input variables `x1`, `x2`, and `x3` and a target variable of `y`, I am thinking the batch should behave like
```python
(x1, x2, x3), y = b
```

The order of the variables will be the same as the order of the fields in the dataset.

**Comment by mttk** [comment]
Closing as #285 has landed.
