### ISSUE TITLE
A Hint? A Clue as to how to use the 'Pre-built loaders for common NLP datasets'

### ISSUE THREAD

**Issue by MotorCityCobra** [pytorch/text#297]
Could I please have an example for how to use the code to load a dataset?

    torchtext.datasets.WikiText2()

It requires 2 required positional arguments: 'path' and 'text_field'  
The text_field is "The field that will be used for text data." -What? What field, please?

**Comment by mttk** [comment]
You can find usage examples at https://github.com/pytorch/text/tree/master/test, for example at https://github.com/pytorch/text/blob/master/test/language_modeling.py for `WikiText2`

In short, `Fields` are different _columns_ of your dataset. In the case of language modelling, you just have one -- you are predicting the shifted input text from text. Inside the Field classes you define how do to preprocessing, tokenization and the transformation to tensors. They are later used to build the vocabularies for that columns as well.

**Comment by MotorCityCobra** [comment]
Okay. I tried the example code and it DOES download the desire dataset.  
Eureka.  

Is '.splits' the 'path' part of the function?  
From trying to read the code itself I thought 'path', like the local path the dataset was going would have to be specified by me.

**Comment by mttk** [comment]
If you load WikiText2 with the basic constructor, it will actually default to the constructor of the LanguageModellingDataset, which is not what you want (this behavior is not really logical tbh). 

WikiText2, PTB etc have pre-defined splits, and the `.splits()` or `.iters()` class methods are the way to load them -- both of the methods download the data to the folder specified by `root` (which defaults to `.data`), then unpack to the train/dev/test splits and load them by using the LanguageModellingDataset constructor.

Kinda convoluted, but I hope you got it. This class contains most of the relevant code: https://github.com/pytorch/text/blob/master/torchtext/datasets/language_modeling.py

**Comment by gissemari** [comment]
What's the value I should use in 'text_field'?
