### ISSUE TITLE
Example of an embedding loader?

### ISSUE THREAD

**Issue by AjayTalati** [pytorch/text#30]
Hi,

is the any chance of an example of a pretrained word embeddings loader? 

A single example of how to quickly load say, `word2vec` or `glove`, would be really cool. I guess once, people see a common example and use it, it should be straightforward to adapt the loader to other pretrained embeddings.

Thanks a lot :+1:   

PS - I saw this [thread](http://forum.opennmt.net/t/simple-guide-for-custom-pre-trained-embeddings/203) on the opennmt forum, but I couldn't get it to work?

**Comment by jekbradbury** [comment]
The `Vocab` objects in torchtext `Field`s have the built-in ability to load word2vec-formatted word vectors (including pretrained GloVe embeddings from Stanford). See (for instance) the SNLI example.

**Comment by AjayTalati** [comment]
I see it , https://github.com/pytorch/text/blob/master/torchtext/vocab.py, 

This is repo is really cool :+1: thanks for writing it :) Be great if it was linked to the NLP tutorials

**Comment by mataney** [comment]
Something I wrote that might help:
Assuming you have a `model` variable that is the word2vec or the glove embedding lookup dictionary.
This model is probably a word->vec mapping, and we want to create a index->vec, mapping let's call this `pretrained_embeddings_matrix`.
(Just loop over the word indices for insert the vec in the index location)

Now let's say you have you embedding in a variable called `embedding` you can just:
`embedding.weight.data.copy_(torch.from_numpy(pretrained_embeddings))`

**Comment by AjayTalati** [comment]
Hi Mataney, @mataney 

thanks a lot for the hint :)

I just saw this repo which seems to do what I want, just thought it would helpful to post it here,

https://github.com/iamalbert/pytorch-wordemb

**Comment by michaelcapizzi** [comment]
This is a bit of a hack until `from_pretrained()` shows up in an official version, but it's not complicated.

There is an attribute `.weight` that contains the `<Parameter>` class with the embedding values.  You can overwrite that with you own.

```
pretrained_embeddings = torch.FloatTensor([
    [1,1,1,1],
    [2,2,2,2]
])
embeddings = torch.nn.Embedding(2,4)
embeddings_pretrained.weight    # would be the "randomized" values
embeddings_pretrained.weight = torch.nn.Parameter(pretrained_embeddings, requires_grad=False)  # if True, then the embeddings will be updated, otherwise they are "frozen"
```

**Comment by jiangyangbo** [comment]
you can see the web in the following: 
https://github.com/pytorch/examples/blob/master/snli/train.py
in the line 29:  inputs.vocab.load_vectors(args.word_vectors)

**Comment by jiangyangbo** [comment]
https://github.com/pytorch/examples/blob/master/snli/train.py 

inputs.vocab.load_vectors(args.word_vectors)
