### ISSUE TITLE
Add more functions to initialize the <unk> token word vectors in build_vocab()

### ISSUE THREAD

**Issue by nh007cs** [pytorch/text#317]
In function build_vocab(), the default initializer for token "unk" is torch.Tensor.zero_, but there is no funtion that can be used for initializing <unk> with specified normal distributions or uniform distributions. 

torch.Tensor.normal and torch.nn.init.normal_ can't be passed here.

**Comment by phizaz** [comment]
https://github.com/pytorch/text/blob/7f0ed40229d680e64dc3fefbb39f2dccc255eb07/torchtext/vocab.py#L31

class `Vocab` accepts `unk_init` as a callback function.

```
                unk_init (callback): by default, initialize out-of-vocabulary word vectors
                to zero vectors; can be any function that takes in a Tensor and
                returns a Tensor of the same size. Default: torch.Tensor.zero_
```

Could you send this argument into the `Field.build_vocab` ?

**Comment by nh007cs** [comment]
torch.Tensor.zero_ can be sent to Field.build_vocab, but i don't know how to intialize the <unk> with a specified normal distribution or uniform distribution.

**Comment by mttk** [comment]
You should be able to use `torch.nn.init.uniform_/normal_`. If you want to preset the mean / std, check out partial https://docs.python.org/3/library/functools.html#functools.partial

**Comment by nh007cs** [comment]
Thank you very much! You solved my problem!
