### ISSUE TITLE
Is there an alternative way to get the length of sequence besides explicit "include_lengths" ? 

### ISSUE THREAD

**Issue by phizaz** [pytorch/text#318]
Since `Field` will pad the sequence by default, after getting padded sequence is there a way to know the original sequence length? Or the only practical way is to use `include_lengths` ? 

And If so, this means that I cannot have the lengths for IMDB dataset, since it doesn't care parametized fields.

**Comment by mttk** [comment]
`include_fieds` is the best way, and you can also use it in `IMDB` (see my answer in #319 )
