### ISSUE TITLE
Should "iters" method accept fields esp. in predefined datasets?

### ISSUE THREAD

**Issue by phizaz** [pytorch/text#319]
For example in IMDB dataset, however this should apply to all predefined datasets:

https://github.com/pytorch/text/blob/7f0ed40229d680e64dc3fefbb39f2dccc255eb07/torchtext/datasets/imdb.py#L58

If I put `fields` as an argument here it would cause `TypeError: __init__() got multiple values for argument 'fields'` error, because it is fighting with the existing `TEXT` and `LABEL`. 

Should users have access to change those fields? I could think of a scenario in which I want have the return length of the input (before being padded), it would be impossible without changing the `fields`, I presume ?

**Comment by mttk** [comment]
There's two approaches to loading a dataset, for IMDB both are demonstrated in the test file: https://github.com/pytorch/text/blob/master/test/imdb.py

1. You run `iters` and everything is predefined (https://github.com/pytorch/text/blob/master/test/imdb.py#L37)
2. You set up the fields, load the dataset via `splits` and define your own iterator (https://github.com/pytorch/text/blob/master/test/imdb.py#L6)

**Comment by phizaz** [comment]
@mttk That test file is a gold! It would be great as an example as well. Love you :heart:
