### ISSUE TITLE
Randomly initialising word vectors

### ISSUE THREAD

**Issue by Henry-E** [pytorch/text#32]
There doesn't seem to be the option to initialise word vectors without using pretrained embeddings. There's an option to fill in vectors for tokens missing from the pretrained embeddings with normally distributed values. It would be cool if there was a built in option to initialise embeddings from a uniform distribution without having to specify a word embedding file.

**Comment by jekbradbury** [comment]
You'd do that in your model class's `__init__` by using `nn.init` or some other weight initializer rather than passing the weight matrix from `torchtext`.

**Comment by Henry-E** [comment]
Thanks for the recommendation, a bit new to this. The initialised vectors would still go into TEXT.vocab.vectors?

**Comment by jekbradbury** [comment]
No, you don’t need to put them there -- the only place where your embeddings actually need to be is in your model; TEXT.vocab.vectors offers a way to get pretrained vectors corresponding to your vocabulary and then use those to initialize your model's embeddings.

**Comment by jeremy-rutman** [comment]
> ....There's an option to fill in vectors for tokens missing from the pretrained embeddings with normally distributed values....

how do i find that option??

**Comment by zhangguanheng66** [comment]
We have new vector class in `torchtext/experimental/vectors.py`. See here https://github.com/pytorch/text/blob/master/torchtext/experimental/vectors.py#L219

**Comment by jeremy-rutman** [comment]
Is there an example for this somewhere?

**Comment by jeremy-rutman** [comment]
Can I do the following: 
```

    TEXT.build_vocab(train_data, vectors=GloVe(name='6B', dim=300))
    word_embeddings = torch.FloatTensor(np.random.rand(len(ETXT.vocab),embedding_length)
    self.word_embeddings = nn.Embedding(vocab_size, embedding_length)
    self.word_embeddings.weight = nn.Parameter(word_embeddings, requires_grad=True)

```
if I am after randomly-initialized embeddings ?

**Comment by zhangguanheng66** [comment]
you don't need the last line.
```
word_embeddings = nn.Embedding(vocab_size, embedding_length)
```
should set the vector randomly.
