### ISSUE TITLE
Pytorch 0.4 / torchtext 0.2.3

### ISSUE THREAD

**Issue by vince62s** [pytorch/text#321]
Has the following been fixed in master ? if so can you release 0.2.4 ?

/usr/local/lib/python3.6/dist-packages/torchtext/data/field.py:321: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  return Variable(arr, volatile=not train), lengths
/usr/local/lib/python3.6/dist-packages/torchtext/data/field.py:322: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  return Variable(arr, volatile=not train)

**Comment by shihan9** [comment]
it has been fixed on the master branch. for now, `pip install git+git://github.com/pytorch/text`.

**Comment by vince62s** [comment]
it's fine, but there are really some breaking changes since the pytorch 0.4 support.
it would be good to bump a sub version.
what do you think ?

**Comment by zhangguanheng66** [comment]
@vince62s if this is still an issue, feel free to reopen it.
