### ISSUE TITLE
how to set unk to the last of the vocab?

### ISSUE THREAD

**Issue by caolusg** [pytorch/text#322]
When I build vocab, I fount the <unk> is the first word in the vocab, is it possible set it to the last word of the vocab?

**Comment by AveryLiu** [comment]
The vocab is actually a dict, you could manually modify it to the way you want if needed. Wish to know if there's another elegant torchtext way to do it.

**Comment by mttk** [comment]
@AveryLiu @caolusg there's unfortunately no other elegant way to do it, those values are currently hardcoded. This would be a reasonable change.

**Comment by mttk** [comment]
Fixed in #400
