### ISSUE TITLE
`batch_first` doesn't work correctly

### ISSUE THREAD

**Issue by psubnwell** [pytorch/text#342]
Hi I try to build a `BPTTIterator` with the batch on the first dimension:
```
from torchtext.data import Field
from torchtext.datasets import LanguageModelingDataset
from torchtext.data import BPTTIterator

TEXT = Field(batch_first=True)
train = LanguageModelingDataset(path='./train.txt', text_field=TEXT)  # train.txt can be any text file with word separated by space, e.g. PTB corpus.
train_iter = BPTTIterator(dataset=train, batch_size=64, bptt_len=30, device='cuda')
TEXT.build_vocab(train)
print(next(iter(train_iter)).text.size())
```
It outputs:
```
torch.Size([30, 64])  # Should be [64, 30]
```
Do I use it wrongly? Please help, thanks!

**Comment by liuzhishan** [comment]
Hi,

According to the  code in `BPTTIterator.__iter__`:

```
data = TEXT.numericalize([text], device=self.device, train=self.train)
data = data.view(self.batch_size, -1).t().contiguous()
```

It will always transpose the data no matter what the `batch_first` is, before the iter returned. 
Not sure why processed this way.

**Comment by vin-ivar** [comment]
Fixed in #462, seems to run fine.

**Comment by zhangguanheng66** [comment]
@vin-ivar Thanks for the contribution. Please close the issue after fixing it.

**Comment by vin-ivar** [comment]
I can't close the issue, I didn't open it, and it isn't my repository.

**Comment by zhangguanheng66** [comment]
@psubnwell Feel free to reopen the issue if you still have a question.
