### ISSUE TITLE
How to share vocabulary across fields?

### ISSUE THREAD

**Issue by ymfa** [pytorch/text#346]
I'm new to torchtext. I want to use two fields which should have the same vocabulary. The only difference is that `field2` prepends an `<sos>` token to every sequence. I have the following code:

    field1 = ReversibleField(torch.LongTensor, tokenize=tokenizer)
    field2 = ReversibleField(torch.LongTensor, tokenize=tokenizer, init_token='<sos>')
    dataset = TabularDataset(path='train.json', format='json',
                             fields={'x': ('x', field1),  'y': ('y', field2)})
    field1.build_vocab(dataset, max_size=30000)

Now I want `field2` to use the `vocab` of `field1`. I tried `field2.vocab = field1.vocab`, but this results in an error in later processing. According to documentation, the only way to force the same vocabulary seems to be to use the same field, but setting the `init_token` dynamically isn't possible when the `dataset` is read by a `BucketIterator`.

My current workaround is to first save `field1`, and then load it also as `field2`:

    field1 = ReversibleField(torch.LongTensor, tokenize=tokenizer, init_token='<sos>')
    # ... build vocab as before
    torch.save(field1, 'field1.pt')
    field2 = torch.load('field1.pt')
    field1.init_token = None

However, I don't know if this will also work if the fields are associated with word vectors. Since the `vocab` of `field1` and `field2` are essentially two independent copies, updates to the word embeddings will have to be performed on both fields. Alternatively, I can manually create a vocabulary `dict` and use it to initialize two copies of `Vocab`, but how can I make the two fields to use them?

Is there a recommended way to share vocabulary?

**Comment by hohoCode** [comment]
Exactly the same question, is there any official way to share vocabulary ACROSS fields? Thanks!

**Comment by hohoCode** [comment]
Update: I think I got the answer. There is no official way to do so but we can do so on our own way.

**Comment by Runingtime** [comment]
@hohoCode can you please tell me  the solution?

**Comment by hohoCode** [comment]
@Runingtime I think it is possible to basically hack into the codes, and make the Vocab sharable across all fields. I am still on this and havn't made it working yet. Hopefully will be there.

**Comment by yyHaker** [comment]
> @Runingtime I think it is possible to basically hack into the codes, and make the Vocab sharable across all fields. I am still on this and havn't made it working yet. Hopefully will be there.

Hi, I have the same question, do you have any good ideas?

**Comment by zhangguanheng66** [comment]
feel free to reopen the issue if you have any questions.

**Comment by madaanpulkit** [comment]
> I think this maybe is a method!
> ![image](https://user-images.githubusercontent.com/18585628/50390201-16651b80-076f-11e9-8fc6-d62ea26d2c9e.png)

It throws error at
`a_text.vocab = text.vocab`
Field object has no attribute vocab

**Comment by zhangguanheng66** [comment]
a_text doesn't have the vocab attribute until you call build_voca()

**Comment by madaanpulkit** [comment]
> a_text doesn't have the vocab attribute until you call build_voca()

Changed the code for `Field` class to declare `self.vocab=None` in the constructor. Seemed to work.

**Comment by zhangguanheng66** [comment]
> > a_text doesn't have the vocab attribute until you call build_voca()
> 
> @zhangguanheng66 I changed the code for `Field` class to declare `self.vocab=None` in the constructor. Seemed to work.

You could use vars(a_text) to check if there is an attribute vocab. If so, the error message doesn't make sense.
