### ISSUE TITLE
BucketIterator class method splits bug

### ISSUE THREAD

**Issue by prashantbudania** [pytorch/text#352]
When creating train/dev/test iterators using BucketIterator.splits(), the dev and the test iterators returned are not correct.

--
This dataset that I am working with is 'Yelp 13 Review dataset'. It has two fields: Statement and Score. In my development data split, if I set train=False, the generated batch has incorrect dimensions. (I am returning both documents and document_lengths). As you can see from the screenshot, the batch returned has length of 1 but if the flag is set to True (train=True), it returns the correct dimensions. (lengths of 68,67 etc.)
--

![screen shot 2018-07-18 at 12 23 54 pm](https://user-images.githubusercontent.com/16194274/42894701-8fd6ed66-8a85-11e8-9d8a-241901ff544d.png)
.

**Comment by AveryLiu** [comment]
Can you elaborate what is the correct behavior? I can't tell from the picture. Do the two consecutive calls return different dimensions?

**Comment by prashantbudania** [comment]
This dataset that I am working with is 'Yelp 13 Review dataset'. It has two fields: Statement and Score. In my development data split, if I set train=False, the generated batch has incorrect dimensions. (I am returning both documents and document_lengths). As you can see from the screenshot, the batch returned has length of 1 but if the flag is set to True (train=True), it returns the correct dimensions. (lengths of 68,67 etc.)
