### ISSUE TITLE
FEATURE REQUEST: Remove undesired words from vocabulary

### ISSUE THREAD

**Issue by manuelsh** [pytorch/text#354]
When building the vocabulary, it would be great to be able to pass a list of undesired words (e.g. punctuation marks, stop words, etc) and they will not belong to the vocabulary (hence, will be '<unk>' when "numericalizing").

**Comment by domaala** [comment]
Not sure if this helps you, but you could pass your own preprocessing/postprocessing pipeline to the `Field` constructor that would handle the removal of unwanted tokens.

**Comment by manuelsh** [comment]
Yes, I actually did that, thanks!

However, being such a common thing to do in NLP, possibly makes sense to add it in the library?

**Comment by domaala** [comment]
Possibly, yes!

**Comment by mttk** [comment]
Added in #397

**Comment by manuelsh** [comment]
Amazing, thanks!
