### ISSUE TITLE
ModuleNotFoundError: No module named 'torchtext'

### ISSUE THREAD

**Issue by trtm** [pytorch/text#360]
Hello 👋

I get the following error message, when I want to `import torchtext`:

> ----> 1 import torchtext
> 
> ModuleNotFoundError: No module named 'torchtext'

The issue is the same as already asked on [Stackoverflow](https://stackoverflow.com/questions/51452412/cant-import-torchtext-module-in-jupyter-notebook-while-using-pytorch) by another torchtext user! 

I run `torch==0.4.0` with `python==3.6.5`.

This error occurs while importing the library from within Jupyter (Notebook & Lab), with `jupyter==1.0.0` and `jupyterlab==0.33.4`.

Importing the same library form the terminal within the Python prompt works (in the same env).

I tried the following options and got the same error message:
1.  with [Anaconda3](https://anaconda.org/) and this command `conda install -c derickl torchtext`
2. with my own Python3 [virtualenv](https://virtualenv.pypa.io/en/stable/) and several options like `pip install https://github.com/pytorch/text/archive/master.zip` for resulting torchtext version **0.3.0**, with `pip install torchtext` for torchtext version **0.2.3** and all other versions up until **0.2.1**.

After each run I completely reset the env I worked in, so there I exclude this as an possible error.

Can someone replicate this issue?
How should I proceed?
Is this maybe caused by Jupyter itself?

All the best! ✌️

**Comment by trtm** [comment]
After the help from the [jupyterlab](https://github.com/jupyterlab/jupyterlab/issues/5025) project, I think I finally got it!

I needed to adapt the sys.path and to include my own `torch_dev` env, which is this one `/home/trtm/torch_dev/lib64/python3.6`

This issue can be closed!

**Comment by xuwang278** [comment]
Thanks so much for trtm's help! 

In a little bit detailed, on your Jupiter Notebook, please try:
import sys
sys.path.append("/Users/.../opt/anaconda3/envs/.../lib/python3.7/site-packages")

import torchtext
