### ISSUE TITLE
iterator.py file error: TypeError: '>' not supported between instances of 'int' and 'tuple'

### ISSUE THREAD

**Issue by ashleyliu31** [pytorch/text#365]
Versions: pytorch  0.4.1, torchtext   0.2.3
Error message:
File "C:\Users\ashle\conda\envs\tensorflow\lib\site-packages\torchtext\data\iterator.py", line 257, in batch
    elif size_so_far > batch_size:
TypeError: '>' not supported between instances of 'int' and 'tuple'

Code:
for epoch in range(1, epochs + 1):
    running_loss = 0.0
    running_corrects = 0
    model.train()
    for x, y in tqdm.tqdm(train_dl): 
        opt.zero_grad()
 
        preds = model(x)
        loss = loss_func(y, preds)
        loss.backward()
        opt.step()
 
        running_loss += loss.data[0] * x.size(0)
 
    epoch_loss = running_loss / len(train)

Is there something wrong with the iterator.py file? Spyder console is pointing me to the iterator.py file rather than my own code. Is this a torchtext bug? I upgraded both pytorch and torchtext and still get the same error. Thanks in advance for any insight!

**Comment by mttk** [comment]
Could you provide the arguments which you pass to the constructor of the Iterator? & are you using a custom dataset?

The error isn't a torchtext bug, but it happens when an unexpected argument is passed to the iterator. The arguments need to be torchtext datasets.

**Comment by ashleyliu31** [comment]
train_iter, valid_iter = BucketIterator.splits((train,valid),
                                               batch_size=64,
                                               device=0,
                                               sort_key=lambda x: len(x.TEXT),
                                               sort_within_batch=False,
                                               repeat=False)

I set the batch_size to a tuple before; now that it's an integer, the problem disappeared =) thanks!

**Comment by mttk** [comment]
Ah, that can be the case as well :)

If you want to set different batch sizes for train / test / valid, use the "batch_sizes" argument.
