### ISSUE TITLE
How to share vocabulary ACROSS fields? Thanks!

### ISSUE THREAD

**Issue by hohoCode** [pytorch/text#367]
I think this question was asked before but got no responses.. Wondering is there any official way to share vocabulary ACROSS fields? How to do this?

Thank you!

**Comment by domaala** [comment]
@hohoCode I think that if those two (or more) fields are preprocessed in the same way, then you don't need two (or more) different fields, but only a single one. For example, if there are two text columns in your `TabularDataset` and, let's say, a label column, you could use a single text field **twice** and a single label field once in the specification. That is:

```
TEXT  = data.Field(tokenize=data.get_tokenizer("moses"), lower=True)
LABEL  = data.Field(sequential=False, use_vocab=False)

FIELDS = [
    ("sentence1", TEXT),
    ("sentence2", TEXT),
    ("label", LABEL)
]

dataset = data.TabularDataset(path="something.csv", format="tsv", fields=FIELDS)
```

Now, you need to build the vocabulary only once. Let me know if this helped (and worked).

**Comment by hohoCode** [comment]
Thanks for help! But my fields have very different formats, some in (nested) list, others in plain text sequence, or with special tokens (which requires extra parsing/tokenization). All I want is just to share the vocab among them. So it would be difficult to reuse the field twice..

**Comment by domaala** [comment]
@hohoCode Seems that case is not supported yet, unfortunately. Take a look at #253. Maybe you could build vocabularies for each field separately, then merge them using the function given on link, and then finally set them manually to both fields. I am just tossing ideas around; maybe they don't make any sense. :)

**Comment by hohoCode** [comment]
Thanks for the clarification.
