### ISSUE TITLE
Consider Adding --user to README Install Commands

### ISSUE THREAD

**Issue by soaxelbrooke** [pytorch/text#374]
The README contains bare commands that by default will look like they need escalated permissions.  Many people are not experts in Python package management, and the `Permission denied` shown at the end of a failing `pip install` or `spacy download` will steer a lot of people towards running the commands as root, which for most is the wrong path to go down.  It would be good to add `--user` to these commands to help them go down the right path, a'la:

```bash
$ pip install --user torchtext
$ python -m spacy download en --user
```

**Comment by soaxelbrooke** [comment]
(I can put up a PR for this if it would be helpful)

**Comment by zhangguanheng66** [comment]
@soaxelbrooke would you like to create a PR for this issue?

**Comment by soaxelbrooke** [comment]
@zhangguanheng66 Done! See #544
