### ISSUE TITLE
how to retrain the glove or other word vectorize algorithms?

### ISSUE THREAD

**Issue by Blusea** [pytorch/text#379]
how to retrain the glove or other word vectorize algorithms?
Armed in search an sequence-based model for protain-protain binding prediction, it need to retain charactor vectorize model for amino acid sequence. In this repo, I just found the pretrained api.

**Comment by mttk** [comment]
This repository only contains data loaders (for vectors and common datasets).

If you want to train the vectors from scratch on a different corpus, I'd suggest you take a look at the official implementations of word2vec / GloVe / FastText.

If you want to fine-tune the pre-trained vectors which can be loaded via torchtext, you need to define a model with pytorch.

**Comment by zhangguanheng66** [comment]
@Blusea feel free to reopen the issue if you still have questions.
