### ISSUE TITLE
Consider adding: spacy tokenizer in other languages

### ISSUE THREAD

**Issue by pablogps** [pytorch/text#380]
Currently a field may take "tokenize='spacy'" to use spacy (English) as tokenizer. This is really convenient. Unfortunately, it only works in English. Other languages (Spanish) would be much appreciated, and should be a small update.

Thanks!

**Comment by mttk** [comment]
This seems reasonable, if you could formulate this in a PR, it would be great.

**Comment by pablogps** [comment]
I'll give it a try and report back!

**Comment by mttk** [comment]
This should work now in master. You can pass the argument `tokenizer_language=es` for example and it should load the spacy spanish tokenizer.

**Comment by pablogps** [comment]
Oh! I've been busy but meaning to do this myself. Sorry I took too long, and thanks a lot for the improvement, it will be appreciated!

**Comment by zhangguanheng66** [comment]
@mttk Thanks for fixing it. I will just close the issue.
