### ISSUE TITLE
Translation splits error when not downloading dataset first

### ISSUE THREAD

**Issue by rumaak** [pytorch/text#384]
Thanks @AngusMonroe for finding this! The problem is that the absence of dataset is not addressed when creating splits. Minimal example:

```

from torchtext.datasets import Multi30k
from torchtext.data import Field
EN = Field()
DE = Field()
ds = Multi30k.splits(('.de','.en'),[('de',DE),('en',EN)],'data/multi30k')
```

**Comment by rumaak** [comment]
I am currently busy and can't work on it (possibly for a few days) so if anyone wants to submit PR, go for it. Otherwise, I will take a look at it as soon as possible.

**Comment by mttk** [comment]
#385 fixes this. 
Unrelated, but note the `root` should be the `.data` or `data`, or whichever folder _contains_ the `multi30k` folder as the name gets appended automatically.
