### ISSUE TITLE
Serializing Fields

### ISSUE THREAD

**Issue by nelson-liu** [pytorch/text#41]
Is there a canonical way to serialize `Fields` for later use? (e.g. if you want to load a model, preprocess/numericalize some test data, and then run the model on the test data)?

`torch.save` won't work on it out of the box since `Pipeline` and `Vocab` both have un-pickleable lambda locals. I hackily got around it by just redefining these lambdas as named functions (happy to clean it up and send a PR if you want), but I'm wondering if there's a better way.

Thanks!

**Comment by jekbradbury** [comment]
Well, even if we clean up all the builtin lambdas there are still several arguments that users would most naturally provide as lambdas -- I'm honestly not sure there's a great solution to this; users that need to pickle Fields could maybe use `import dill as pickle` but I know that has its limitations too...

**Comment by nelson-liu** [comment]
Fair enough -- I do think there's an argument for keeping the torchtext side serializable by default, and recommending `dill` to users who want to pass in their own lambdas, etc. What do you think?

**Comment by jekbradbury** [comment]
Sure, that sounds reasonable.

**Comment by jekbradbury** [comment]
Closing in favor of #73
