### ISSUE TITLE
SOS and EOS tokens are not recognized when Field is used by multiple TabularDataset

### ISSUE THREAD

**Issue by ksurya** [pytorch/text#414]
I have a data file that already contains SOS and EOS tokes. There are multiple files but I need to maintain common vocabulary.

I create a field object `text_field = torchtext.data.Field(sequential=True, batch_first=True)`

Use the field object with two TabularDataset instances.

```
fields = ( ("text", text_field), )
ds1 = torchtext.data.TabularDataset(path=ds_file_path1, format="tsv", fields=fields)
ds2 = torchtext.data.TabularDataset(path=ds_file_path2, format="tsv", fields=fields)

text_field.build_vocab(ds1)
text_field.build_vocab(ds2)
```

The `text_field.vocab.stoi` dictionary does not contain SOS and EOS tokes that are in the files.

If I just build vocabulary with just one dataset, it contains the tokens.

**Comment by mttk** [comment]
`build_vocab` always constructs a new vocab from scratch (and doesn't extend the old one).
However, you can pass multiple datasets to it. Can you try running `text_field.build_vocab(ds1, ds2)`?

**Comment by ksurya** [comment]
Thank you, its working.
