### ISSUE TITLE
Feature request: add ELMo vectors

### ISSUE THREAD

**Issue by manuelsh** [pytorch/text#419]
They are new state-of-the-art word embeddings. 

See: https://allennlp.org/elmo

Thanks!

**Comment by mttk** [comment]
ELMo works on sentence level (and requires loading a pretrained model, not only a dictionary), which is _currently_ out of scope of the library. Adding ELMo and CoVe would be nice, but I'm not sure when it's going to happen.

**Comment by mttk** [comment]
It does, but it produces those vectors through a BiLSTM, which requires the whole sentence as context.

Quote from the blog post: "Embeddings from Language Models (ELMos) use language models to obtain embeddings for individual words while taking the entire sentence or paragraph into account."

and

"Concretely, ELMos use a pre-trained, multi-layer, bi-directional, LSTM-based language model and extract the hidden state of each layer for the input sequence of words. Then, they compute a weighted sum of those hidden states to obtain an embedding for each word."

To obtain ELMo embeddings for each word, you pass the sentence through a pretrained BiLSTM. The weights available online are the weights of those BiLSTMs, not the word vectors.

**Comment by manuelsh** [comment]
Hi @mttk 

That's the same case with other embeddings, like word2vec, where they are obtained from a model that takes context into account (e.g. n-grams) and then one can use the pre-trained vectors in other model.

I believe in https://allennlp.org/elmo there are weights from pre-trained ELMos vectors, taken with models trained with wikipedia corpus.

**Comment by manuelsh** [comment]
So when it says: "Then, they compute a weighted sum of those hidden states to obtain an embedding for each word."  this is how the embeddings for each word are obtained, I think. :-)

**Comment by mttk** [comment]
It's not the same case as the other word embedding models such as word2vec generate a "word : vector" dictionary. ELMo produces a model which produces those weights. This requires, at some point, loading the model as a pytorch module.

You can read [this](https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md) tutorial and also download and open the [weights](https://allennlp.org/elmo) to validate this yourself.

**Comment by manuelsh** [comment]
I see your point now... the phrase "Then, they compute a weighted sum of those hidden states to obtain an embedding for each word." confused me.  Thanks @mttk !

**Comment by raheelqader** [comment]
@davidalbertonogueira: is there a chance you can share the code of your BERT supported field?

**Comment by zhangguanheng66** [comment]
If ELMo is still needed, please propose in PyTorch core library since it is relevant to the embedding module.
