### ISSUE TITLE
Feature request: add Roten Tomatoes and AGNews datasets

### ISSUE THREAD

**Issue by manuelsh** [pytorch/text#420]
Would be fantastic to have these two datasets, as they would make the new model testing faster!

Datasets available here:

Roten Tomatoes (sentiment analysis):
https://www.kaggle.com/c/sentiment-analysis-on-movie-reviews

and

AGNews (text classification):
https://www.di.unipi.it/~gulli/AG_corpus_of_news_articles.html

Thanks!

**Comment by anmolsjoshi** [comment]
@zhangguanheng66 @mttk AGNews has been incorporated. 

I wanted to add Rotten Tomatoes Dataset but noticed it was hosted on Kaggle. Is it ok to host the data on Google Drive and submit a PR for that dataset?

**Comment by zhangguanheng66** [comment]
@anmolsjoshi Thanks. Rather than hosting data, we prefer to download the data with a link. So to your question, yes and Google Drive should be fine (actually several existing datasets uses the data from Google drive).

**Comment by zhangguanheng66** [comment]
AG_NEWS available in the 0.4.0 [release](https://github.com/pytorch/text/releases/tag/0.4.0). More supervised learning datasets are available there as well.

**Comment by anmolsjoshi** [comment]
@zhangguanheng66 on further inspection, it seems that Kaggle has rules against sharing datasets, they prefer it is hosted on their website. If you know any different, I'd be happy to send a PR for this.
