### ISSUE TITLE
What's the meaning of "repeat" parameter of torchtext.data.Iterator?

### ISSUE THREAD

**Issue by jueliangguke** [pytorch/text#422]
In Docs, this parameter is described as "Whether to repeat the iterator for multiple epochs.". But how to understand "repeat the iterator"?

**Comment by mttk** [comment]
It means that instead of iterating for one epoch, the iterator continues infinitely until stopped (in cases where you measure performance after # iterations and not # epochs).
The default will soon be changed to `False` (so the iterator will stop after one epoch).

**Comment by jueliangguke** [comment]
@mttk I see, thanks for your answer!
