### ISSUE TITLE
What is "parse_field" for?

### ISSUE THREAD

**Issue by jueliangguke** [pytorch/text#424]
In torchtext.datasets.SNLI.splits, there is a parameter named "parse_field". I found if setting this field with a "datasets.snli.ShiftReduceField" object, the vocabulary becomes much smaller and SNLI accuracy always improves (compared with default value). It is amazing! But I can't find any description about it...

**Comment by rumaak** [comment]
https://github.com/pytorch/text/blob/master/torchtext/datasets/nli.py#L57

I am not familiar wit the corpus itself, but quick search found me this, so you might want to check it out.
