### ISSUE TITLE
io.UnsupportedOperation: not readable

### ISSUE THREAD

**Issue by AngusMonroe** [pytorch/text#427]
I got  this error when I loading data.

```
File "site-packages/torchtext/datasets/translation.py", line 36, in __init__
    for src_line, trg_line in zip(src_file, trg_file):
io.UnsupportedOperation: not readable
```

It seems like the mode of `src_file` and `trg_file` is incorrect.

Maybe change the code in `translation.py` like this would fix the problem.

```
with io.open(src_path, mode='w+', encoding='utf-8') as src_file, \
                io.open(trg_path, mode='w+', encoding='utf-8') as trg_file:
```

**Comment by mttk** [comment]
whoops, fixing immediately, an error while c/ping that didn't get caught by tests.

**Comment by mttk** [comment]
Can you please check if this is ok after #429 lands?

**Comment by AngusMonroe** [comment]
Thx. This commit is work for me.
