### ISSUE TITLE
How to filter low frequency words?

### ISSUE THREAD

**Issue by fuzihaofzh** [pytorch/text#431]
I wonder how to filter the low-frequency words or is there any way to constrain the size of the vocabulary?

**Comment by mttk** [comment]
you pass these as arguments to the `build_vocab` method, ex:

```python
 TEXT.build_vocab(train, test, val, vectors=vectors, max_size=30000, min_freq=2) 
```

**Comment by fuzihaofzh** [comment]
It solved by that. Thanks.
