### ISSUE TITLE
Large vocabulary for model deployment

### ISSUE THREAD

**Issue by MFajcik** [pytorch/text#434]
Hi,
I am still confused about using vocabs in torchtext. Assume that my model is perfectly trained and I want to deploy it. The model can work with much larger vocabulary, than it has seen in the training data.
How do I create field with vocabulary as big as possible?
Thanks.

**Comment by mttk** [comment]
If you're loading word vectors, then your vocab will (by default) keep all those vectors which are loaded from the vector file. 
Could you elaborate your concrete use-case?

**Comment by MFajcik** [comment]
Assume that

**Comment by MFajcik** [comment]
Okay, yesterday I thought I have found the solution but... I did not.
To elaborate, assume the following example:

1. I have a field `contexts` which contains vocabulary put together from training and validation data `contexts.build_vocab(train_data, val_data, vectors="fasttext.en.300d", vectors_cache=config["vectors_cache"])`.
2. I train my model (vectors are fed to `torch.nn.Embedding` via `embeddings.weight.data.copy_(contexts.vocab.vectors)`) and save it via `torch.save`.
3. Now I want to use my model in practice. The model will be probably used on much larger vocabulary than it was trained on. Also my vocabulary is not in the model, so I do not know which index of `torch.nn.Embedding` represents which word.

**My problems**
What is a 'correct' way to dealing with this? Should I save dictionaries from `i2s`, and `s2i `respectively available inside `context.vocab`? And how do I extend dictionaries and torch.nn.Embedding to include embeddings, which were available in downloaded embedding vectors `"fasttext.en.300d"`, but were not in the training data?

> If you're loading word vectors, then your vocab will (by default) keep all those vectors which are loaded from the vector file. 
    
I am not quite sure how this was meant, for example as I now tested doing `contexts.build_vocab(val_data,...)` gives in my case for `len(contexts.vocab.itos)` value `9773`
whether `contexts.build_vocab(train_data, val_data,...)` gives value `19346`.

Thank you for your answer.

**Comment by MFajcik** [comment]
To include all the embeddings, I do the following 
```
    specials = ["<pad>", "<num>", "<eos>"]
    with open(os.path.join(config["vectors_cache"], "glove.6B.100d.txt.pt"), mode="rb") as f:
        m = torch.load(f)
    for i in specials:
        m[1][i] = 1
    v = tt.vocab.Vocab(m[1], specials=specials, vectors="glove.6B.100d",
                       vectors_cache=config["vectors_cache"])
    contexts.vocab = v
```
But I guess this is a bit hackish.

**Comment by zhangguanheng66** [comment]
If my understanding is correct, you should load the deployment vocabulary and probably re-train the model. Feel free to reopen the issue and add more discussions.
