### ISSUE TITLE
Character level CNN-based embeddings

### ISSUE THREAD

**Issue by MFajcik** [pytorch/text#435]
Hi,
are there any plans for adding character CNN-based embeddings into torchtext? (Popularized by Kim et al. https://arxiv.org/abs/1508.06615).

**Comment by mttk** [comment]
Doing that is the responsibility of the model -- right now, you can obtain character level vocabularies for Fields w/ one-hot vectors (via NestedField), and you can feed those into a nn.Embedding, as you usually do with word embeddings.
