### ISSUE TITLE
No argument `max_vectors` in torchtext.vocab.Vectors.__init__()

### ISSUE THREAD

**Issue by CoderINusE** [pytorch/text#436]
No argument `max_vectors` in torchtext.vocab.Vectors.__init__() for torchtext 0.2.3. Why there is not information about the 0.3 version in README? Pip is not able to find the version 0.3.0 with error: "Could not find a version that satisfies the requirement torchtext==0.3.0 (from versions: 0.1.1, 0.2.0, 0.2.1, 0.2.3)". What should I do?

I'm using PyTorch 0.4.1 and Python 3.6.

**Comment by mttk** [comment]
I believe 3.0 is not yet released. For now, you can install from master (clone the repo and run `python setup.py`).

**Comment by CoderINusE** [comment]
I knew that but the official docs give information about new features so it is a little misleading.

**Comment by mttk** [comment]
Agreed, we'll release 3.0 to pypi sometime next week. The docs had some issues up until recently so there's unfortunately no versions of docs for previous releases.

**Comment by zhangguanheng66** [comment]
@CoderINusE feel free to reopen the issue if you still have questions.
