### ISSUE TITLE
Does `BucketIterator` support `num_workers` argument?

### ISSUE THREAD

**Issue by seilna** [pytorch/text#437]
At docs for [`BucketIterator`](https://torchtext.readthedocs.io/en/latest/data.html#bucketiterator),
```
class torchtext.data.BucketIterator(
    dataset, 
    batch_size, 
    sort_key=None, 
    device=None, 
    batch_size_fn=None, 
    train=True, 
    repeat=False, 
    shuffle=None, 
    sort=None, 
    sort_within_batch=None)
```

It seems that there no options for setting `num_workers`. Is there anything I missed? or Is it the case?

**Comment by mttk** [comment]
This is correct, `BucketIterator` at the current state does not support multithreading.

**Comment by zhangguanheng66** [comment]
@seilna feel free to reopen the issue if you still have questions.
