### ISSUE TITLE
batch_szie changed

### ISSUE THREAD

**Issue by cswangjiawei** [pytorch/text#438]
In an epoch training process, the size of batch suddenly changed, why？
![error](https://user-images.githubusercontent.com/33107884/46568404-ed569b00-c976-11e8-81e3-2a5ffe5ecb88.jpg)

**Comment by mttk** [comment]
If the length of your dataset is not divisible with your defined `batch_size`, the last batch in an epoch will contain the overflow examples.

So, if you have a batch size of 32 and 100 examples, the last 4 examples (after 3 size-32 batches) will be the last batch. This will be changed so you can control it with an argument in the near future, for now I'd recommend to check whether the tensor batch size fits your predefined batch size upon iteration.

**Comment by cswangjiawei** [comment]
When my batch_size is set to 128, the dataset has a total of 313 batches, but why in the 305th batch, the size of the batch becomes 64. I have done two experiments before, and in the 312th and 301th batches, the size of the batch has changed to 64. Why did not the size of the batch change when the 313th batch is used? Shouldn't the size of the last batch change?

**Comment by zhangguanheng66** [comment]
@cswangjiawei if you could provide a script to reproduce the error, I'm happy to take a look at the issue. Feel free to reopen the issue and assign to me.
