### ISSUE TITLE
Splitting up torchtext/data.py into files for each class

### ISSUE THREAD

**Issue by nelson-liu** [pytorch/text#44]
As it currently stands, [torchtext/data.py](https://github.com/pytorch/text/blob/master/torchtext/data.py) has a _lot_ of functionality in one file. I think it'd be nice to split the file into pieces separated by individual functionality, e.g. a file for `Fields`, a file for `Datasets` (and their subclasses, of course), a file for `Iterators`, etc. In particular, I think the structure of [torch.nn](https://github.com/pytorch/pytorch/tree/master/torch/nn) would work well here.

I think doing this would be a lot clearer in terms of organization of the codebase, but the biggest issue I have with it is that it changes the syntax for the import from `from torchtext import data` to `import torchtext.data as data` (much as one would do `import torch.nn as nn`), rendering the code backwards-incompatible. But i'm not sure how much weight is placed on this, considering the repo isn't on pypi yet and there's a big WIP on the readme...what do you all think?

**Comment by jekbradbury** [comment]
Wait, why does it require the import change? E.g. I always import nn using `from torch import nn`.

**Comment by nelson-liu** [comment]
Whoops, it doesn't you're right. Sorry, was too late and wasn't thinking properly :)
