### ISSUE TITLE
How to bypass downloading dataset?

### ISSUE THREAD

**Issue by yiqiaoc11** [pytorch/text#445]
I had some customized dataset and a glove.840B at hands. How can I use the dataset and interpret it by the  
glove.840B without downloading?

**Comment by yiqiaoc11** [comment]
Actually, I’d like to use an unzipped dataset and parse it by glove.6B. Could you give an example? Thanks.




________________________________

**Comment by yiqiaoc11** [comment]
I'd like to split unzipped SNLI dataset at hands. Is there a way similar to datasets.SNLI.splits(), but not downloading again? Thanks.

**Comment by zhangguanheng66** [comment]
@yiqiaoc11 feel free to re-open the issue if you still have questions.
