### ISSUE TITLE
How to save a Field object

### ISSUE THREAD

**Issue by cswangjiawei** [pytorch/text#451]
Field objects can't be saved by pickle or json, how to save Field objects？

**Comment by cswangjiawei** [comment]
Field objects can be saved by dill . dill extends python’s pickle module for serializing and de-serializing python objects to the majority of the built-in python types. Serialization is the process of converting an object to a byte stream, and the inverse of which is converting a byte stream back to on python object hierarchy.

**Comment by mttk** [comment]
When #453 lands, this will be possible to do even without `dill`.
