### ISSUE TITLE
[Feature request] Reading compressed (e.g. gzipped) datasets?

### ISSUE THREAD

**Issue by eugene-kharitonov** [pytorch/text#454]
Hello,
I wonder if there could be a support for reading zipped/gzipped torchtext.data.TabularDataset-s? 
In our case the dataset is small enough that we want to store its versions in the repo alongside with the code.
I understand it's not a mainstream use-case.  Happy to make a PR myself, if it makes sense.
A relevant snippet https://github.com/pytorch/text/blob/master/torchtext/data/dataset.py#L251

**Comment by mttk** [comment]
This sounds as a reasonable addition. I believe the gist of the change would be changing `open` to some variant of `zipfile`, `gzipfile` etc., as I believe you intended with the referenced line.

A PR would be appreciated!
