### ISSUE TITLE
`input, target = batch` syntax is not working if the batch is created by BPTTIterator

### ISSUE THREAD

**Issue by ikorolev93** [pytorch/text#491]
Minimal reproduction code:
```
import torchtext.datasets as datasets

train, valid, test = datasets.WikiText2.iters()
input, target = next(iter(train))
```

Expected: no errors
Actual result:
```
Traceback (most recent call last):
  File ".../main.py", line 4, in <module>
    input, target = next(iter(train))
  File ".../venv/lib/python3.7/site-packages/torchtext/data/batch.py", line 78, in __iter__
    yield self._get_field_values(self.input_fields)
AttributeError: 'Batch' object has no attribute 'input_fields'
```
---
Looking at the code, `BPTTIterator` calls `Batch.fromvars` that creates a `Batch`, but never defines the `input_fields` and `target_fields` (unless it's passed in `**kwargs`, which is not the case). Copying the appropriate initialization code from constructor, it starts working.
So either `Batch.fromvars` should calculate `input_fields` and `target_fields` from `dataset`, or `BPTTIterator` should pass them in `**kwargs`.

**Comment by mttk** [comment]
Thanks for reporting, will fix this ASAP.

**Comment by zhangguanheng66** [comment]
Hi @mttk just wondering if there are any progress for this issue. Thanks.

**Comment by mttk** [comment]
Hey @zhangguanheng66, I've (re)identified the problem, and I have a quick and dirty solution. I'll open a PR right away (#542), but the language modelling pipeline needs a large restructure.

**Comment by Nayef211** [comment]
We have migrated all datasets to torchdata datapipes and should not be seeing this issue any longer.
