### ISSUE TITLE
Inconsistent fields initialization in Dataset and Example fromdict.

### ISSUE THREAD

**Issue by samurous** [pytorch/text#492]
In the Documentation on [Dataset and Fields](https://torchtext.readthedocs.io/en/latest/data.html#dataset) it states that fields

> fields (dict[str, Field]) – Contains the name of each column or field, together with the corresponding Field object. Two fields with the same Field object will have a shared vocabulary.

While in the __init__() method description it states:

> fields (List(tuple(str, Field))) – The Fields to use in this tuple. The string is a field name, and the Field is the associated field.

But `data.Example.fromdict` won't work either way since it is expecting a dict with a tuple in the dict value like `Dict[str, ('str', 'Field')]` here: 

https://github.com/pytorch/text/blob/c4f746f91abf97bdaca5bc7ade8b33b3bc8e183f/torchtext/data/example.py#L27

When initiallizing a Dataset this way, it will break, since when Iterating the Dataset `dataset.fields.items()` is expected to return a Field as value 

https://github.com/pytorch/text/blob/c4f746f91abf97bdaca5bc7ade8b33b3bc8e183f/torchtext/data/batch.py#L26-L27

**Comment by mttk** [comment]
Regarding your first point, the difference in documentation is between the attribute and the argument of the constructor. When constructing a raw `Dataset`, the expected datatype of `fields` is `List(tuple(str, Field))`. Then, inside the constructor, the argument is converted to the format of the class attribute `dict[str, Field])`. So, while those two variables share names, they are not the same.

Your second point is correct -- the format of `Dataset.fields` isn't compatible with the `Example.fromdict` constructor, _however_, that constructor is never called from the raw `Dataset` class. The `examples` in the argument of the Dataset class (`__init__(self, examples, fields, filter_pred=None)`) are the already constructed (by a subclass) list of examples.

What roughly happens is:

1. A subclass of `Dataset` is instantiated (ex. TabularDataset)
2. `TabularDataset` (and any other class inheriting from `Dataset`) contains the logic for creating a list of `Example`'s from data files
3. Once the list of examples is created, the constructor of the superclass (`Dataset`) is called (the `Example.fromdict` has already been called with the proper `fields` format here)
4. In that constructor, we merely assign arguments to class attributes _after_ re-formatting the `fields` argument for easier processing (essentially, flattening it into a dict)

**Comment by Nayef211** [comment]
Closing this since `torchtext.data.Field` has been deleted and is no longer available in the latest releases of our library. Additionally, we have migrated all datasets to torchdata datapipes.
