### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by aatkinson** [pytorch/text#496]
I've noticed a long period of inactivity on this project and I'm curious if it's still being actively developed?

Also is this library going to be merged with PyText - or vice-versa - since it is a dependency? (See https://github.com/facebookresearch/pytext)

**Comment by aatkinson** [comment]
Hi Martin, sorry I didn't see that issue. Thanks for the update, get well soon!

**Comment by soumith** [comment]
@cpuhrsch will also be helping out / revamping things starting probably in a few weeks. We'll reach out to you Martin, to co-ordinate this.
