### ISSUE TITLE
initializing the vectors at vocab.py is random

### ISSUE THREAD

**Issue by ReactiveCJ** [pytorch/text#497]
At the vocab.py,   
for this line self.vectors = torch.Tensor(len(self), tot_dim) 
we want to initialize the element of  self.vectors by zero, but when the len(self) or tot_dim is small, this initialization results is random.
Correct 
self.vectors = torch.Tensor(len(self), tot_dim)  
to
 self.vectors = torch.zeros(len(self), tot_dim)

**Comment by mttk** [comment]
Correct, however the undefined data is going to get overwritten in the loop over `itos` in any case.

The vector loading code is long overdue a cleanup, and I'll also remove the `torch.Tensor` calls.
