### ISSUE TITLE
add stopwords to Field

### ISSUE THREAD

**Issue by ReactiveCJ** [pytorch/text#500]
At the __init__ function of class Field,
    if stop_words is not None:
            try:
                self.stop_words = set(stop_words)
            except TypeError:
                raise ValueError("Stop words must be convertible to a set")
        else:
            self.stop_words = stop_words
        self.stop_words = stop_words
we try to convert stop_words to set, but at the end, we duplicately assign stop_words to self.stop_words, therefore the upper code doesn't work.

**Comment by mttk** [comment]
This has been fixed in master AFAIK 

https://github.com/pytorch/text/blob/master/torchtext/data/field.py#L169

**Comment by zhangguanheng66** [comment]
@ReactiveCJ please feel free to close the issue if it's fixed.
