### ISSUE TITLE
what's the meaning of the 1 in ShiftReduceField?

### ISSUE THREAD

**Issue by brbzjl** [pytorch/text#509]
the following code is what i used. i know the 2 and 3 in transitions vector are respectively means 'reduce' and 'shiftthe'. the  question is, there also exist some 1 and 0. i am confused, what kind of roles plays these 0 and 1?

inputs = datasets.nli.ParsedTextField(lower=args.lower)
transitions = datasets.nli.ShiftReduceField()
answers = data.Field(sequential=False)
train, dev, test = datasets.SNLI.splits(inputs, answers, transitions)   
inputs.build_vocab(train, dev, test)
answers.build_vocab(train)
train_iter, dev_iter, test_iter = data.BucketIterator.splits(  (train, dev, test), batch_size=args.batch_size,   
    device=device)

**Comment by Nayef211** [comment]
Closing the issue as we no longer maintain the `Field` class in our library.
