### ISSUE TITLE
How can I filter out too high frequency words

### ISSUE THREAD

**Issue by sheepover96** [pytorch/text#513]
Hi!

Now I want to filter out too frequency words when i call build_vocab() method like a following manner.
```
TEXT = Field(sequential=True, lower=True)
TEXT.build_vocab(lang, max_freq=40)
```
Is there any method to do this or do I need to implement it by my self?

**Comment by zhangguanheng66** [comment]
For now, please implement it as needed. If we continuously receive such feature request, we will add it via a PR.

**Comment by Nayef211** [comment]
I don't believe we plan to add any features about high frequency words (only low frequency words are supported for the time being). Closing this for now but will reopen if we continue getting requests for this feature.
