### ISSUE TITLE
torchtext 0.4.0 not available

### ISSUE THREAD

**Issue by Americanwallace0** [pytorch/text#517]
$ pip install torchtext==0.4.0
Collecting torchtext==0.4.0
  Could not find a version that satisfies the requirement torchtext==0.4.0 (from versions: 0.1.1, 0.2.0, 0.2.1, 0.2.3, 0.3.1)
No matching distribution found for torchtext==0.4.0

**Comment by bebound** [comment]
Latest version released on pypi is 0.3.1
You can install the github version by `pip install git+https://github.com/pytorch/text`, which is 0.4.0

**Comment by mttk** [comment]
0.4 is coming up tomorrow, merging some final fixes.
