### ISSUE TITLE
Dataset.split with stratified=True is not reproducible

### ISSUE THREAD

**Issue by DianeBouchacourt** [pytorch/text#532]
When using TabularDataset.split with stratified = True, the sampling is not reproducible. After inspection, it looks like it is because of this line:
https://github.com/pytorch/text/blob/499e327ea53bdf67c648f5747ed26764283b968a/torchtext/data/dataset.py#L318

Indeed, the set of unique_strata returned is not always in the same order. Therefore, even though the samples drawn in rationed_split are the same, the different group in strata will be looked at in a different order :
https://github.com/pytorch/text/blob/499e327ea53bdf67c648f5747ed26764283b968a/torchtext/data/dataset.py#L329

A simple fix could be to add in stratify() the following line:
unique_strata = sorted(unique_strata)

**Comment by mttk** [comment]
This sounds reasonable, could you send a PR?

**Comment by Nayef211** [comment]
Closing the issue as we no longer maintain the `TabularDataset` in our library.
