### ISSUE TITLE
Numericalize torch.FloatTensor and torch.DoubleTensor

### ISSUE THREAD

**Issue by shafiul** [pytorch/text#535]
Hi,

I was unable to use floating-point labels using the following field declaration:

    LABEL = data.Field(sequential=False, use_vocab=False, is_target=True, dtype=torch.DoubleTensor)

Got this error: "Specified Field dtype <class 'torch.DoubleTensor'> can not be used with use_vocab=False because we do not know how to numericalize it"

Would it be straight-forward to numericalize such fields?

Thanks!

**Comment by mttk** [comment]
Hi, instead of using a concrete class for the `dtype` argument, you should use torch dtypes, ex:
`LABEL = data.Field(sequential=False, use_vocab=False, is_target=True, dtype=torch.float64)`

**Comment by zhangguanheng66** [comment]
@shafiul if the issue is resolved, please feel free to close the issue. Thanks.

**Comment by shafiul** [comment]
Hi, sorry for the late response. Thank you for the feedback.
