### ISSUE TITLE
Cache build_vocab; Shared vocabulary 

### ISSUE THREAD

**Issue by PetrochukM** [pytorch/text#54]
`src.build_vocab(mt_train, max_size=80000)
trg.build_vocab(mt_train, max_size=40000)`

In the README example, it looks like build_vocab is used twice on the same dataset. For large datasets this could take awhile.

**Comment by jekbradbury** [comment]
The two calls iterate through entirely separate data: the semantics of `field.build_vocab(dataset)` are to build the vocab for the field from every column in the provided dataset that is associated with that field.

**Comment by Deepblue129** [comment]
Shoot! Misread the code.

Can you explain this comment a bit more `# mt_dev shares the fields, so it shares their vocab objects`? Looks like the Vocab object is not shared between them as they created two separate Vocab objects.

What would be the intended way to build a shared vocabulary between target and source?

**Comment by jekbradbury** [comment]
Create a single field and use it for both sides. It’s a little confusing, but a single field instance is meant to mean a single vocabulary. So in the example sharing a `SRC` field between `train` and `dev` datasets means the source side in train and dev uses the same vocab; if you share a `TEXT` field between source and target for both train and dev the same vocab will be used all around.

**Comment by Deepblue129** [comment]
Thank you! Updated the title to reflect the comments better.

**Comment by Deepblue129** [comment]
Ok! Working more with shared vocabularies. 

The source field needs to not have SOS and EOS but it needs to share a vocabulary with the target field. Using torchtext, what is the best way to achieve that?

Reference: https://github.com/pytorch/text/issues/74#issuecomment-315914012

**Comment by Deepblue129** [comment]
@jekbradbury How should a dictionary be shared but have different specials?

Looking to build a input and output dictionary that is the same for seq2seq. But the output dictionary has EOS and SOS and input does not.

**Comment by jekbradbury** [comment]
What about explicitly sending the two vocal constructors the data from both source and target:
```
SRC.build_vocab(train.src, train.trg)
TRG.build_vocab(train.src, train.trg)
```
I'm not 100% sure that'll do what you're looking for (I think you really want a way to decouple the specials included in the tensors from the specials included in the vocab), but it's worth a try first.

**Comment by Deepblue129** [comment]
I think that'll work. 

Worried about performance where I am building the same vocab twice just with different specials.

**Comment by joecummings** [comment]
Closing as stale.
