### ISSUE TITLE
iterator epoch property can cause error

### ISSUE THREAD

**Issue by vincentzlt** [pytorch/text#540]
https://github.com/pytorch/text/blob/9902e793a0c5f5f0a8fccee09684c5cd4a86afea/torchtext/data/iterator.py#L132

when batch_size_fn is implemented, self(len) is not implemented. thus the epoch property will raise an error.

**Comment by zhangguanheng66** [comment]
@vincentzlt if you create a PR, we will accept it. Really appreciate it.

**Comment by anmolsjoshi** [comment]
@zhangguanheng66 where is the epoch property used?

**Comment by Nayef211** [comment]
I believe this issue can be closed as torchtext's datasets have now been migrated to TorchData datapipes in https://github.com/pytorch/text/issues/1494. We no longer use `batch_size_fn` in our datasets.
