### ISSUE TITLE
How to set the max length for batches?

### ISSUE THREAD

**Issue by XinDongol** [pytorch/text#572]
Is there a way to use something like `max_len` argument: all text entries in a dataset longer than a certain length can be thrown out.

**Comment by zhangguanheng66** [comment]
After batching, I guess you can just sent the batches within the "max_len"  value to the model.

**Comment by XinDongol** [comment]
@zhangguanheng66 
You mean something like this?
```Python
if batch_size(batch) > max_len:
   batch = next(batch_iter)
```

**Comment by zhangguanheng66** [comment]
I think I misunderstand your request. If the text entries are longer than a certain length, you can pad the text (maybe with 'unk' token) and then ignore them. You need some kinds of pre-processing depending on a specific dataset.

**Comment by XinDongol** [comment]
Thanks. 

The length of my sentences is
![image](https://user-images.githubusercontent.com/15049780/62087581-15213300-b217-11e9-98cf-6b947220e309.png)

I only want to use len<=30 sentences to form batches. Is there any solution that allows me to do this without changing my txt data file?

**Comment by anmolsjoshi** [comment]
@XinDongol can you override the [__iter__ method](https://github.com/pytorch/text/blob/master/torchtext/data/dataset.py#L147) here like this

```python
def __iter__(self):
    for x in self.examples:
        if len(x) <= 30:
            yield x
```

**Comment by kylase** [comment]
You can pass in a `Callable` as `filter_pred` to `Dataset` (https://torchtext.readthedocs.io/en/latest/data.html#torchtext.data.Dataset). I have used this to remove certain examples that are not necessary.

**Comment by XinDongol** [comment]
> You can pass in a `Callable` as `filter_pred` to `Dataset` (https://torchtext.readthedocs.io/en/latest/data.html#torchtext.data.Dataset). I have used this to remove certain examples that are not necessary.

Could you please provide more hints about this method (I am familiar with `Callback`)?
Thanks a lot
