### ISSUE TITLE
why IMDB could not work? 

### ISSUE THREAD

**Issue by meshiguge** [pytorch/text#581]
```python
from torchtext import data
from torchtext import datasets
TEXT = data.Field(lower=True, include_lengths=True, batch_first=True)
LABEL = data.Field(sequential=False)

train, test = datasets.IMDB.splits(TEXT, LABEL)
print ( len ( train ))
```
This returns a length of **0** .

**Comment by zhangguanheng66** [comment]
I check the downloaded file and there are no text files in the training folder. I guess the online file is broken. Unfortunately, we don't host data. But I will reach out to them and see what happen there.

**Comment by zhangguanheng66** [comment]
I try the script above on the latest master branch. The dataset works for me (the output len of train is 25000). Just be patient for data loading, and it may stuck for a while.

**Comment by AMNAALMGLY** [comment]
I observed yeah many times it get me a train data of zero length unless I restart the runtime  if working with colab
