### ISSUE TITLE
Building docs

### ISSUE THREAD

**Issue by nelson-liu** [pytorch/text#59]
It'd be nice to actually get docs built for people to reference, even while this is still WIP. I'm happy to set up a Sphinx project, but i noticed that pytorch/vision doesn't have docs within the repo, but rather in the main pytorch repo.

Thus, is it preferable to:
1. Set up a Sphinx project in this repo (and move it over to the main repo when this is less WIP)?
2. Set up a Sphinx project in the main repo?
3. Don't even bother with building docs yet?

cc @jekbradbury (@soumith @apaszke may have things they want to say about this as well)

**Comment by keon** [comment]
@nelson-liu 
I used torchvision docs as a template for basic documentation #179

**Comment by nelson-liu** [comment]
I was just about to comment on your PR --- let's move the conversation over there. Thanks for taking this on!

**Comment by tomekkorbak** [comment]
Is there any work going on the docs or do you guys have any plans how should the docs look like? I'd love to contribute.

@jekbradbury
