### ISSUE TITLE
SubwordField documentation is absent

### ISSUE THREAD

**Issue by Guitaricet** [pytorch/text#599]
## 📚 Documentation

**Description**

It is not clear how (and when) to use `SubwordField` from the documentation. And it is hard to find usage examples. It would be great if someone who used it would add at least a few lines to its doc.

For example, if I am using github.com/VKCOM/YouTokenToMe tokenizer - should I create `SubwordField` or `Field`. And what is the difference between them?

**Comment by ZhuBaohe** [comment]
[Referring to the example of the original PR](https://github.com/pytorch/text/pull/107)

**Comment by Nayef211** [comment]
Closing the issue as we no longer maintain `Field` or `SubwordField` in our library.
