### ISSUE TITLE
SNLI dataset does not support extra_fields or multiple fields per json entry

### ISSUE THREAD

**Issue by bentrevett** [pytorch/text#607]
First, the `SNLI.splits` method does not accept an `extra_fields` argument. This seems fair enough as the other fields in there aren't really useful.

This, however, leads to a problem when trying to use multiple torchtext fields for each key in the SNLI dataset - such as getting both words and characters for the premise and hypothesis.

The main issue seems to be [here](https://github.com/pytorch/text/blob/master/torchtext/datasets/nli.py#L82) where any key that appears in `extra_fields` overwrites the field that already exists. 

I propose that instead of overwriting a key that exists, it should append to that key, creating multiple fields per key.

A quick fix, in order to get 2 fields per json key:
```python
        for key in extra_fields:
            if key not in fields.keys():
                fields[key] = extra_fields[key]
            else:
                new_field = [fields[key], extra_fields[key]]
                fields[key] = new_field
```

Along with adding the `extra_fields` argument to `SNLI.splits` this now allows you to do:

```python
WORDS = data.Field(tokenize='spacy')
NESTING_CHARS = data.Field(tokenize=list)
CHARS = data.NestedField(NESTING_CHARS, tokenize='spacy')
LABEL = data.LabelField()

extra_fields = {'sentence1': ('premise_chars', CHARS), 'sentence2': ('hypothesis_chars', CHARS)}

train_data, valid_data, test_data = SNLI.splits(WORDS, LABEL, extra_fields=extra_fields)
```

This will now get you a premise and hypothesis processed as both words and characters.

```python
{'premise': ['A', 'person', 'on', 'a', 'horse', 'jumps', 'over', 'a', 'broken', 'down', 'airplane', '.'], 
'premise_chars': [['A'], ['p', 'e', 'r', 's', 'o', 'n'], ['o', 'n'], ['a'], ['h', 'o', 'r', 's', 'e'], ['j', 'u', 'm', 'p', 's'], ['o', 'v', 'e', 'r'], ['a'], ['b', 'r', 'o', 'k', 'e', 'n'], ['d', 'o', 'w', 'n'], ['a', 'i', 'r', 'p', 'l', 'a', 'n', 'e'], ['.']], 
'hypothesis': ['A', 'person', 'is', 'training', 'his', 'horse', 'for', 'a', 'competition', '.'], 
'hypothesis_chars': [['A'], ['p', 'e', 'r', 's', 'o', 'n'], ['i', 's'], ['t', 'r', 'a', 'i', 'n', 'i', 'n', 'g'], ['h', 'i', 's'], ['h', 'o', 'r', 's', 'e'], ['f', 'o', 'r'], ['a'], ['c', 'o', 'm', 'p', 'e', 't', 'i', 't', 'i', 'o', 'n'], ['.']], 
'label': 'neutral'}
```

I'm submitting this as an issue as I'm unsure if this is the intended use for `extra_fields` or if it is to only handle the fields within the NLI datasets that aren't used by the default fields as `extra_fields` always overwrites the default fields as it currently stands. 

Thus, instead of using the `extra_fields` argument a new one could be added?

**Comment by thak123** [comment]
@bentrevett is thing fixed available now ?

**Comment by Nayef211** [comment]
Closing the issue as we no longer maintain the `Field` class in our library. We have migrated our dataset implementation on top of torchdata's datapipes.
