### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by Hravan** [pytorch/text#611]
## ❓ Questions and Help

I would like to contribute to torchtext and therefore I decided to learn more about the internals of the library. Is there any guide that introduces into torchtext? I mean something that presents the core assumptions, classes, functionalities, etc., so that a person can learn how to use torchtext incrementally. If not and the only way to learn more about torchtext is to read the source code, maybe making such a document is a good first issue.

**Comment by zhangguanheng66** [comment]
Besides the source code, you could also read our docs [here](https://pytorch.org/text/). We also have some examples in [pytorch/tutorials](https://pytorch.org/tutorials/beginner/text_sentiment_ngrams_tutorial.html).

Please keep in mind that we plan to change the structure of torchtext significantly soon so you will see a lot of variations for the codebase. 

Of course, we are always welcome the contributions from the open source community.
