### ISSUE TITLE
can't download dataset from drive.google.com

### ISSUE THREAD

**Issue by yonghangzhou** [pytorch/text#628]
## 🐛 Bug
**Describe the bug**

when i run train_dataset,test_dataset = text_classification.DATASETS['AG_NEWS'](root = './data/text_classcification',ngrams=NGRAMS,vocab=None)

it will be error ：
ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=0Bz8a_Dbh9QhbUDNpeUdjb0wxRms (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f475c8403c8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by zhangguanheng66** [comment]
Cannot reproduce the issue? Feel free to re-open it if you still have questions.
