### ISSUE TITLE
Custom Dataset class in Torchtext with variable number of Fields 

### ISSUE THREAD

**Issue by LeenaShekhar** [pytorch/text#633]
## ❓ Questions and Help

**Description**
A custom dataset in Torchtext where each data is (text1, text2, and label) can be written something like below:

```
class CustomDataset(ttdata.Dataset):
    'Reads a JSON file. Each line has text1, text2, and the associated label.'

    def __init__(self, path, max_seq_length=100, min_seq_length=3, add_eos=True):

        text1_field = Field(lower=True, tokenize='spacy')
        text2_field = Field(lower=True, tokenize='spacy')
        label_field = ttdata.Field(sequential=False, use_vocab=False)
        fields = [('text1', text1_field), ('text2', text2_field), ('label', label_field)]

        examples = []

        with open(path, 'r') as f:
            for item in f:
                item = json.loads(item)
                text1, text2, label = item['text1'], item['text2'], item['label']
                examples.append(ttdata.Example.fromlist([text1, text2, label], fields))


        super(CustomDataset, self).__init__(examples, fields)
```

But in my case rather than text1 and text2, I have 2 lists of strings of variable length (text1 = ["some text", "some text", ...] and text2 = ["yet some text", "yet some text", ...])and a label for the 2 lists. 

How can I write a dataset class in this case? I think the main problem is now I cannot define fixed number of Field objects. Can NestedField be used in some way?

**Comment by mttk** [comment]
Yeah, you would want to use NestedField here. I would concatenate the lists of strings with some delimiter (so text1 and text2 will have these texts as a single string), define a `NestedField` which knows how to split these merged texts to obtain the lists, and the `nesting_field` which would know how to process each element.

I can't produce the code right now, but this should be straightforward to implement.

**Comment by LeenaShekhar** [comment]
Thank you @mttk!
I actually tried something similar: defined a NestedField with a custom tokenizer (I concatenated my list of strings with the custom delimiter) and passed NestingField to it as well. It as still splitting everything at character level. May be I made some error so I will try that again.

**Comment by mttk** [comment]
If you don't manage to fix it within some reasonable time, feel free to paste a minimal reproduction and I'll look at it. I won't get a lot of time over this weekend though.

**Comment by LeenaShekhar** [comment]
I think I made some mistake first time because NestedField works just fine. Thank you for confirming it though in the first place.
