### ISSUE TITLE
How to skip last batch that has a different batch size?

### ISSUE THREAD

**Issue by Hans0124SG** [pytorch/text#643]
## ❓ Questions and Help

**Description**

Sorry if this is a newbie question.
In `torch.nn.utils.data.dataloader` we can drop the last batch by specifying `drop_last=True`.
Do we have something equivalent for our `Iterator`? Currently I continue the training loop if I see the current `batch_size` is different from my preset `batch_size`. Is there something built-in?

Thank you very much!

**Comment by mttk** [comment]
Unfortunately, there is nothing of the sort built-in right now.

**Comment by zhangguanheng66** [comment]
Could you check and skip the last batch if the batch size is different from the normal?

Close this issue for now and suggest to ask the question in [pytorch/issues](https://github.com/pytorch/pytorch/issues)
