### ISSUE TITLE
Length of a dataset

### ISSUE THREAD

**Issue by antgr** [pytorch/text#647]
## ❓ Questions and Help

Hello, how could I calculate the length of a default dataset like imdb etc,  With length I mean the number of its examples.

**Comment by mttk** [comment]
`len(dataset)` should do it.

**Comment by zhangguanheng66** [comment]
Feel free to re-open it if you still have questions.

**Comment by antgr** [comment]
Yes! Thank you... In the mean time I figured it out, and I was ready to post it as well.

**Comment by antgr** [comment]
OK, I have one more question. 
If I take a slice of the dataset, will this keep its properties?
I would like to take a small version of a dataset  for example
train_data_nli_small = train_data_nli[:len(train_data)]
but then I think that it is not iterable any more.
