### ISSUE TITLE
LanguageModelingDataset is not recognizing special tokens

### ISSUE THREAD

**Issue by h56cho** [pytorch/text#653]
Hello,

When I define my Fields and perform split like below, under `train_Wiki2.examples[0].text`, `val_Wiki2.examples[0].text`, `test_Wiki2.examples[0].text`, I see that the end-of-sentence token `<eos>`,etc. are correctly recognized as a single token as a whole, but for some reason the unknown-token `<unk>` is not recognized as a single token as a whole:

```js
# define the English text field
TEXT_Wiki2 = Field(tokenize = "spacy",
             init_token = '<sos>',
             eos_token = '<eos>',
             unk_token = '<unk>',
             pad_token = '<pad>',
             tokenizer_language = 'en',
             lower = True)

# load WikiText2 dataset and split it into train and test set
train_Wiki2, val_Wiki2, test_Wiki2 = torchtext.datasets.WikiText2.splits(TEXT_Wiki2)

train_Wiki2.examples[0].text
 [ ...
# <unk> NOT recognized as a single token
 '<',
 'unk',
 '>',
 ...
# <eos> recognized as a single token
 '<eos>',
...]
```
How can I make LanguageModelingDataset to recognize all of the special tokens such as `<sos>`,`<eos>`,`<unk>`,`<pad>`, and so on?

Thanks,

**Comment by mttk** [comment]
Wikitext2 is already pre-tokenized and stored in a space-separated format (thus the `<unk>` tokens). In this case, you are using the spacy english tokenizer, which incorrectly splits the `<unk>` token.
For such pre-tokenized datasets, you should simply not define a tokenizer, and then the default `string.split` will be used, which is intended for these cases.

So -- simply remove the `tokenizer` and `tokenizer_language` arguments.

**Comment by h56cho** [comment]
Thank you!
