### ISSUE TITLE
How to prefetch data?

### ISSUE THREAD

**Issue by speedcell4** [pytorch/text#660]
Currently, the bottleneck of my model training is on the data loading part, is there any example about how to prefetch data? Like the `pin_memory` and `num_workers` arguments of `torch.utils.data.DataLoader`

**Comment by zhangguanheng66** [comment]
which dataset are you using now? We have re-writed language modeling and text classification datasets to make them more compatible with `torch.utils.data.DataLoader`.

**Comment by Nayef211** [comment]
@speedcell4 lmk if you're still seeing these bottlenecks. There's also dataloader v2 coming out soon which should have some improvements on data loading perf.

**Comment by speedcell4** [comment]
a "coming out soon" without reference but + closing issue before confirming
really good manner! @Nayef211

**Comment by Nayef211** [comment]
> a "coming out soon" without reference + closing issue without confirming really good manner! @Nayef211

@speedcell4 we are currently going through the backlog of issues and responding to/closing out issues that we think are legacy and may no longer be relevant as we've made a lot of updates to our library over the last couple of years. Feel free to keep the issue open if you're still running into the performance bottlenecks.
