### ISSUE TITLE
torchtext.data.Iterator loading data too slow

### ISSUE THREAD

**Issue by zml24** [pytorch/text#668]
## ❓ Questions and Help

**Description**
Hey Dude, I am running a machine translation task with `torchtext.datasets.IWSLT`. However, I found that the CPU usage is always high and GPU usage is always low. When using `torch.utils.data.dataloader`, I can use `num_workers` and `pin_memory` to deal with this problem. But I can't deal with this problem with `torchtext.data.Iterator` or `torchtext.data.BucketItertor`.

How can I accelerate my data loading speed via `torchtext`?

**Comment by zhangguanheng66** [comment]
Yes, we will re-write the translation datasets later so they will be compatible with `torch.utils.data.dataloader` (see some discussions https://github.com/pytorch/text/issues/664)

**Comment by lizitong67** [comment]
How to solve this problem？？

**Comment by Nayef211** [comment]
Closing this since `torchtext.data.Iterator` has been deleted and is no longer available in the latest releases of our library.
