### ISSUE TITLE
Why the size of stoi and itos are not equal?

### ISSUE THREAD

**Issue by ElderWanng** [pytorch/text#670]
## ❓ Questions and Help

**the len of stoi and itos are not same**
When I try to reconstruct a sentence and a error shown up:
`list index out of range`
the I check the **vocab** 
`len(TEXT.vocab.itos)-len(TEXT.vocab.stoi)`
the output is not zero???

Ahhhh, Is there anybody can tell me why they are not equal? I can't figure out.
THX!!!

**Comment by Phlogiston90** [comment]
For some reason this does not happen if no words are excluded when building the vocabulary, i.e. if one constructs a vocabulary with
`SRC.build_vocab(train_data, min_freq=1)`
instead of 
`SRC.build_vocab(train_data, min_freq=2)`
where SRC is a torchtext.data.Field.

**Comment by mttk** [comment]
Could you post the scripts for data loading and vocab construction?
The `stoi` code literally only copies `itos`, so unless you are doing some modifications to either, this should not happen.

**Comment by Nayef211** [comment]
Going to close this as I wasn't able to repro the issue. Feel free to open if you're still seeing inconsistencies in the size.
