### ISSUE TITLE
similar to nli dataset, best format to parse

### ISSUE THREAD

**Issue by antgr** [pytorch/text#674]
## ❓ Questions and Help

**Description**

Hi, I want to parse and create a dataset, that is similar to snli etc. Specifically it has pair of sentences and a label. 

Which is the best format in order to load it more easily with torchtext?
en example could be
"this is sentence one", "This is sentence 2", label

**Comment by zhangguanheng66** [comment]
To me, you could take a look at the text classification datasets [here](https://github.com/pytorch/text/blob/master/torchtext/datasets/text_classification.py).

**Comment by Nayef211** [comment]
We have migrated our datasets on top of [torchdata datapipes](https://github.com/pytorch/data). Feel free to compose datapipes together to load in your custom data following the examples of how torchtext datasets are implemented!
