### ISSUE TITLE
Getting the erorr: AttributeError: 'Field' object has no attribute 'vocab' when setting `use_vocab` to `False` in a `Field`

### ISSUE THREAD

**Issue by abdullah-alnahas** [pytorch/text#675]
## ❓ Questions and Help
How to set `use_vocab` to `False` in a `Field` without getting the error: `AttributeError: 'Field' object has no attribute 'vocab'`?
**Description**
I am trying to use my own tokenization function in `torchtext.data.Field`. I am setting the `tokenize` argument to a custom function, and `use_vocab` to `False`. Then, after creating a dataset and an iterator I try to iterate through the dataset, however, I get the following error: 
`AttributeError: 'Field' object has no attribute 'vocab'`.
How to get over that?
I get this error on my own machine as well as on a [colab notebook](https://colab.research.google.com/drive/1e008bRC1hhFpV0p9NbRfhwe0dus5ZnaG). 
Is it a bug? or me missing something?

**Comment by uzaymacar** [comment]
How did you solve this issue?

**Comment by abdullah-alnahas** [comment]
As I remember, I was calling `.build_vocab()` by mistake or something similar to this.
