### ISSUE TITLE
Unsure of the dimension of the nested field

### ISSUE THREAD

**Issue by thak123** [pytorch/text#689]
I am trying to implement character embeddings on the multi30k dataset using the following code but the dimension of the objects that I get is not making sense to me
for ex if source words is of .Size([8, 13])
then character Size([8, 12, 19]) is displayed in this fashion.

is everything fine with my code ?

import spacy

spacy_en = spacy.load('en_core_web_sm') 
import de_core_news_sm
spacy_de = de_core_news_sm.load()
# spacy_de = spacy.load('de_core_news_sm')
from torchtext.data import Field,BucketIterator
from torchtext import data
from torchtext.datasets import TranslationDataset, Multi30k
def tokenize_de(text):
    """
    Tokenizes German text from a string into a list of strings
    """
    return [tok.text for tok in spacy_de.tokenizer(text)]

def tokenize_en(text):
    """
    Tokenizes English text from a string into a list of strings
    """
    return [tok.text for tok in spacy_en.tokenizer(text)]

SRC = Field(tokenize=tokenize_de,
            init_token='<sos>',
            eos_token='<eos>',
            lower=True,
            batch_first=True,include_lengths=False)

TRG = Field(tokenize=tokenize_en,
            init_token='<sos>',
            eos_token='<eos>',
            batch_first=True,
            lower=True,include_lengths=False)

CHAR_NESTING = data.Field(tokenize=list,batch_first=True)

CHAR = data.NestedField(CHAR_NESTING, init_token="<sos>", eos_token="<eos>")

train_data, valid_data, test_data = Multi30k.splits(exts=('.de', '.en'),
                                                    fields=((('src', 'char_src'), (SRC, CHAR)),
                                                            (('trg', 'char_trg'), (TRG, CHAR))))

SRC.build_vocab(train_data.src,min_freq=2)
CHAR.build_vocab(train_data.char_src)

TRG.vocab = SRC.vocab

BATCH_SIZE = 8

train_iterator, valid_iterator, test_iterator = BucketIterator.splits(
    (train_data, valid_data, test_data),
    batch_size=BATCH_SIZE,
    sort_key=lambda x: len(x.src),
    sort_within_batch=True)
for i, batch in enumerate(train_iterator):
  src, trg,  =  batch.src, batch.trg
  char_src, char_trg = batch.char_src, batch.char_trg

torch.Size([8, 13]) torch.Size([8, 12, 19]) torch.Size([8, 17]) torch.Size([8, 16, 9])
  print([SRC.vocab.itos[j]  for i in src for j in i])
  print([CHAR.vocab.itos[j]  for i in char_src[0] for j in i])

  print(src.shape,char_src.shape,trg.shape, char_trg.shape)

  break
`

**Comment by zhangguanheng66** [comment]
@mttk any ideas?

**Comment by thak123** [comment]
@mttk any idea ? You from Zagreb ?

**Comment by mttk** [comment]
The lengts are different because the tokenization is different between CHAR and SRC/TRG. SRC/TRG use spacy en/de and CHAR uses `string.split()` as the tokenizer is not defined. 

You could define two different CHAR fields (CHAR_SRC, CHAR_TRG) with the same nesting field which _should_ work.

```python
CHAR_SRC = data.NestedField(tokenize=tokenize_de, CHAR_NESTING, init_token="", eos_token="")
CHAR_TRG = data.NestedField(tokenize=tokenize_en, CHAR_NESTING, init_token="", eos_token="")
```

**Comment by thak123** [comment]
Worked like a charm. Thank You
