### ISSUE TITLE
builtins.PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by LiangTiger** [pytorch/text#694]
## ❓ Questions and Help

**Description**

TEXT=torchtext.data.Field(lower=True)

train,test=torchtext.data.TabularDataset(path='data',train='train.csv',test='test.csv',format='csv',skip_header=True,fields=[('id',None),('keyword',None),('location',None),('text',TEXT),('target',None)])

error:

Traceback (most recent call last):
  File "F:/TF and Torch/kaggle2/kaggle2.py", line 16, in <module>
    train,test=torchtext.data.TabularDataset(path='data',train='train.csv',test='test.csv',format='csv',skip_header=True,fields=[('id',None),('keyword',None),('location',None),('text',TEXT),('target',None)])
  File "C:\Users\Tiger\AppData\Local\Programs\Python\Python37\Lib\site-packages\torchtext\data\dataset.py", line 251, in __init__
    with io.open(os.path.expanduser(path), encoding="utf8") as f:
**builtins.PermissionError: [Errno 13] Permission denied: 'data'**

**Comment by zhangguanheng66** [comment]
@mttk Any ideas?

**Comment by LiangTiger** [comment]
> @mttk Any ideas?

Do you have any basic courses? I don't quite understand

**Comment by zhangguanheng66** [comment]
You can take a look at two tutorials:
https://pytorch.org/tutorials/beginner/torchtext_translation_tutorial.html
https://pytorch.org/tutorials/beginner/text_sentiment_ngrams_tutorial.html

**Comment by rajan-blackboxes** [comment]
@LiangTiger  How did you solve thus problem?
Thanks

**Comment by m1styLife** [comment]
You may want to use `torchtext.data.TabularDataset.splits` instead of `torchtext.data.TabularDataset`.
