### ISSUE TITLE
Windows and Sentence Piece

### ISSUE THREAD

**Issue by achapkowski** [pytorch/text#703]
## 🐛 Bug
**Describe the bug**

It appears one of the requirements sentencepiece is not built for windows machines.

This causes an import error:

```python
     1 import torch
----> 2 import torchtext
      3 import numpy as np
      4 import pandas as pd

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\torchtext\__init__.py in <module>
----> 1 from . import data
      2 from . import datasets
      3 from . import utils
      4 from . import vocab
      5 from . import experimental

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\torchtext\data\__init__.py in <module>
      8 from .pipeline import Pipeline
      9 from .utils import get_tokenizer, interleave_keys
---> 10 from .functional import generate_sp_model, \
     11     load_sp_model, \
     12     sentencepiece_numericalizer, \

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\torchtext\data\functional.py in <module>
----> 1 import sentencepiece as spm
      2 import re
      3 
      4 __all__ = [
      5     "generate_sp_model", "load_sp_model",

ModuleNotFoundError: No module named 'sentencepiece'
```

**Expected behavior**
module imports without issue.

**Environment**

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/text/master/torchtext/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
python -c "import torchtext; print(\"torchtext version is \", torchtext.__version__)"
```

 - PyTorch Version (e.g., 1.0): latest
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):N/A
 - Python version:3.6
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information: Install torchtext from conda.

**Comment by zhangguanheng66** [comment]
@achapkowski AFAIK, Windows is not officially supported for torchtext. I will reach out to our Windows partner and see if they would like to add it sooner or later.

**Comment by peterjc123** [comment]
It seems the sentencepiece packages are hosted on PyPI. https://pypi.org/project/sentencepiece/0.1.85/#files

**Comment by zhangguanheng66** [comment]
https://github.com/pytorch/text/pull/733 reminds people to install sentencepiece if they use torchtext wheels from conda.

**Comment by zhangguanheng66** [comment]
> It seems the sentencepiece packages are hosted on PyPI. https://pypi.org/project/sentencepiece/0.1.85/#files

@peterjc123 Can you sync us with a plan to unblock the Windows package for torchtext. Thanks.

**Comment by peterjc123** [comment]
Could you please tell me what is currently blocking that?

**Comment by achapkowski** [comment]
You don't have a Windows build on conda.

**Comment by peterjc123** [comment]
@achapkowski @zhangguanheng66 Is this still a Python-only package? If yes, then you could compile it as a noarch package.

**Comment by zhangguanheng66** [comment]
> @achapkowski @zhangguanheng66 Is this still a Python-only package? If yes, then you could compile it as a noarch package. See [here ](https://docs.anaconda.com/anaconda-repository/user-guide/tasks/pkgs/use-noarch-pkgs/)for more details.

Yes. It's currently python-only package but we may expand it with some cpp soon. And a noarch package is what we are doing now.

**Comment by peterjc123** [comment]
Please let me know if you need some help.
