### ISSUE TITLE
for _, batch in enumerate(train_iter): KeyError: None

### ISSUE THREAD

**Issue by gumowangfei** [pytorch/text#705]
TEXT = data.Field(batch_first=True, lower=True, include_lengths=True)
SLOT_LABEL = data.Field(batch_first=True, is_target=True, unk_token=None, pad_token=None)
INTENT_LABEL = data.Field(batch_first=True, is_target=True, unk_token=None, pad_token=None)

fields = [('text', TEXT), ('slot', SLOT_LABEL), ('intent', INTENT_LABEL)]

train, val, test = data.TabularDataset.splits(
    path=path,
    format='csv',
    train=train_path,
    validation=dev_path,
    test=test_path,
    skip_header=True,
    fields=fields
)

TEXT.build_vocab(train)
SLOT_LABEL.build_vocab(train)
INTENT_LABEL.build_vocab(train)

train_iter, val_iter, test_iter = data.BucketIterator.splits(
    (train, val, test),
    batch_sizes=(32, 32, 1),
    device=device,
    sort_key= lambda x: len(x.text),
    sort_within_batch=True,
    repeat=False
)

for _, batch in enumerate(train_iter):
    print('---')

---
---
---
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-92-b8ca9a142d50> in <module>
      1 ngram = 4
      2 # edges_itos = ['<unk>']
----> 3 for _, batch in enumerate(train_iter):
      4     print('---')
      5 #     text_padded_batch, text_included_length_batch = batch.text

/opt/conda/lib/python3.6/site-packages/torchtext/data/iterator.py in __iter__(self)
    154                     else:
    155                         minibatch.sort(key=self.sort_key, reverse=True)
--> 156                 yield Batch(minibatch, self.dataset, self.device)
    157             if not self.repeat:
    158                 return

/opt/conda/lib/python3.6/site-packages/torchtext/data/batch.py in __init__(self, data, dataset, device)
     32                 if field is not None:
     33                     batch = [getattr(x, name) for x in data]
---> 34                     setattr(self, name, field.process(batch, device=device))
     35 
     36     @classmethod

/opt/conda/lib/python3.6/site-packages/torchtext/data/field.py in process(self, batch, device)
    235         """
    236         padded = self.pad(batch)
--> 237         tensor = self.numericalize(padded, device=device)
    238         return tensor
    239 

/opt/conda/lib/python3.6/site-packages/torchtext/data/field.py in numericalize(self, arr, device)
    334         if self.use_vocab:
    335             if self.sequential:
--> 336                 arr = [[self.vocab.stoi[x] for x in ex] for ex in arr]
    337             else:
    338                 arr = [self.vocab.stoi[x] for x in arr]

/opt/conda/lib/python3.6/site-packages/torchtext/data/field.py in <listcomp>(.0)
    334         if self.use_vocab:
    335             if self.sequential:
--> 336                 arr = [[self.vocab.stoi[x] for x in ex] for ex in arr]
    337             else:
    338                 arr = [self.vocab.stoi[x] for x in arr]

/opt/conda/lib/python3.6/site-packages/torchtext/data/field.py in <listcomp>(.0)
    334         if self.use_vocab:
    335             if self.sequential:
--> 336                 arr = [[self.vocab.stoi[x] for x in ex] for ex in arr]
    337             else:
    338                 arr = [self.vocab.stoi[x] for x in arr]

KeyError: None

**Comment by bentrevett** [comment]
Are you trying to do some sort of PoS tagging? 

It looks like either the slot or intent is needed to unk/pad but you've set both tokens to None so it throws the KeyError.

**Comment by gumowangfei** [comment]
ok, thanks

**Comment by gumowangfei** [comment]
> Are you trying to do some sort of PoS tagging?
> 
> It looks like either the slot or intent is needed to unk/pad but you've set both tokens to None so it throws the KeyError.

but, we should not add unk/pad to the label.

**Comment by gumowangfei** [comment]
> Are you trying to do some sort of PoS tagging?
> 
> It looks like either the slot or intent is needed to unk/pad but you've set both tokens to None so it throws the KeyError.

ok, thanks. I forget to set sequence to False.

**Comment by gumowangfei** [comment]
> It looks like either the slot or intent is needed to unk/pad but you've set both tokens to None so it throws the KeyError.

but,  slot label should not unk/pad.

**Comment by bentrevett** [comment]
I don't know what a "slot label" is, but TorchText is trying to either pad it or unk it. 

I'd try changing either unk_token or pad_token not to be None and seeing which one is giving you the error, then try and use that information to solve your problem.

**Comment by gumowangfei** [comment]
> I don't know what a "slot label" is, but TorchText is trying to either pad it or unk it.
> 
> I'd try changing either unk_token or pad_token not to be None and seeing which one is giving you the error, then try and use that information to solve your problem.

Thanks, I found out what's wrong.

**Comment by zhangguanheng66** [comment]
> > I don't know what a "slot label" is, but TorchText is trying to either pad it or unk it.
> > I'd try changing either unk_token or pad_token not to be None and seeing which one is giving you the error, then try and use that information to solve your problem.
> 
> Thanks, I found out what's wrong.

@gumowangfei Could you share what you found in this issue?

**Comment by gumowangfei** [comment]
> > > I don't know what a "slot label" is, but TorchText is trying to either pad it or unk it.
> > > I'd try changing either unk_token or pad_token not to be None and seeing which one is giving you the error, then try and use that information to solve your problem.
> > 
> > 
> > Thanks, I found out what's wrong.
> 
> @gumowangfei Could you share what you found in this issue?

I found out that I can use <unk>/<pad> in slot label.
