### ISSUE TITLE
unk_token cannot be cutomized

### ISSUE THREAD

**Issue by gumowangfei** [pytorch/text#706]
TEXT = data.Field(batch_first=True, lower=True, include_lengths=True, unk_token='unk')

TEXT.vocab.stoi['sss']

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-151-abc1c2595368> in <module>
----> 1 TEXT.vocab.stoi['sss']

KeyError: 'sss'

**Comment by zhangguanheng66** [comment]
Could you leave a code snippet here? The `unk` should work for `vocab`. I'm wondering if there are some bugs with `data.Field`.

**Comment by bentrevett** [comment]
The below code causes the error:

```python
from torchtext.datasets import IMDB
from torchtext.data import Field, LabelField

custom_unk = '<UnK>'
oov_token = '<zzz>'

TEXT = Field(unk_token=custom_unk)
LABEL = LabelField()

train_data, test_data = IMDB.splits(TEXT, LABEL)

TEXT.build_vocab(train_data)

print(TEXT.vocab.stoi[oov_token])
```

Basically, the vocab does not know how to handle a custom unk token as it is hard coded [here](https://github.com/pytorch/text/blob/master/torchtext/vocab.py#L34).

IMO, the unk token should not be part of specials but it's own argument as it has a unique use case.

**Comment by zhangguanheng66** [comment]
OK, I think the error happens when we pass the custom_unk from Field to Vocab. Then, can we have a function method in `Vocab` class to change the default unk token, like
```
def change_default_unk(self, custom_unk):
     self.unk = custom_unk
```

**Comment by BartekRoszak** [comment]
It could be solved by adding that method to Vocab:

> 
    def change_default_unk(self, custom_unk):
        self.unk_index = self.stoi[custom_unk]
        self.stoi.default_factory = self._default_unk_index

And add following lines to the Field.build_vocab method:

> 
        if self.unk_token is not None:
            self.vocab.change_default_unk(self.unk_token)

Should I make a PR?

**Comment by zhangguanheng66** [comment]
I'd wait since we have a plan to change the Vocab class.

**Comment by aryopg** [comment]
Is there any new update regarding this? I think it's related to other OOV issues regardless of using custom OOV token or not

**Comment by Nayef211** [comment]
Closing this since `torchtext.data.Field` has been deleted and is no longer available in the latest releases of our library. The `torchtext.vocab.Vocab` class should be able to support any special tokens including a custom `<unk>` token.
