### ISSUE TITLE
KeyError in `torchtext.utils.download_from_url`

### ISSUE THREAD

**Issue by ehoelzl** [pytorch/text#709]
## 🐛 Bug
**Describe the bug**
When downloading the dataset gzip form a google-drive (e.g. WMT14 dataset), the following error pops up: 
`KeyError: 'content-disposition'` at `torchtext.utils:54`

**To Reproduce**
```
from torchtext.utils import download_from_url
path = "../../Data/wmt16_en_de.tar.gz"
url = "https://drive.google.com/uc?export=download&id=0B_bZck-ksdkpM25jRUN2X2UxMm8"
download_from_url(url, path=path) <-- KeyError: 'content-disposition'
```

**Expected behavior**
Download and extract dataset

**Screenshots**

**Environment**

 - PyTorch Version (e.g., 1.0):1.0.0
 - OS (e.g., Linux): Linux Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): 
 - Python version: 3.6.6
 - CUDA/cuDNN version: 9.0, 7.3.0
 - GPU models and configuration: None
 - Any other relevant information: None

**Comment by ehoelzl** [comment]
Issue comes from google drive

**Comment by phase** [comment]
> Issue comes from google drive

But how does one fix this???

**Comment by Nayef211** [comment]
> But how does one fix this???

Are you seeing this on the latest torchtext nightly or on `0.12.0`?
