### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by anweshpanda** [pytorch/text#724]
I am trying to execute the following code in google colab:::
.................................................
TEXT = data.Field(tokenize = 'spacy', lower = True)
LABEL = data.LabelField()
train_data, valid_data, test_data = datasets.SNLI.splits(TEXT, LABEL)
....................................................
However, I am getting the following error:::
....................................................
FileNotFoundError Traceback (most recent call last)
in ()
----> 1 train_data, valid_data, test_data = datasets.SNLI.splits(TEXT, LABEL)

3 frames
/usr/local/lib/python3.6/dist-packages/torchtext/data/dataset.py in init(self, path, format, fields, skip_header, csv_reader_params, **kwargs)
249 'tsv': Example.fromCSV, 'csv': Example.fromCSV}[format]
250
--> 251 with io.open(os.path.expanduser(path), encoding="utf8") as f:
252 if format == 'csv':
253 reader = unicode_csv_reader(f, **csv_reader_params)

FileNotFoundError: [Errno 2] No such file or directory: '.data/snli/snli_1.0/snli_1.0_train.jsonl'
.....................................................

Can anyone please help?

**Comment by zhangguanheng66** [comment]
@mttk @bentrevett Any ideas? Thanks.

**Comment by bentrevett** [comment]
This happens when the download cuts out halfway through downloading the dataset. The solution is to remove the `.data/snli` folder, reset the Colab notebook and run everything again.

However, it looks like the link to the dataset is down, as I cannot download the dataset directly from http://nlp.stanford.edu/projects/snli/snli_1.0.zip.

**Comment by anweshpanda** [comment]
yes..It is working now..thanks @bentrevett
