### ISSUE TITLE
BLEU Score example does not work

### ISSUE THREAD

**Issue by aigagror** [pytorch/text#727]
For the `torchtext.data.metrics.bleu_score` [documentation](https://pytorch.org/text/data_metrics.html)
The example does not work.
If you run their example:
```
from torchtext.data.metrics import bleu_score
candidate_corpus = [['I', 'ate', 'the', 'apple'], ['I', 'did']]
references_corpus = [[['I', 'ate', 'it'], ['I', 'ate', 'apples']],
        [['I', 'did']]]
bleu_score(candidate_corpus, references_corpus)
```

You get `0` instead of `0.7598356856515925`

**Comment by zhangguanheng66** [comment]
The example in the docs isn't really right. I will update the docs.

**Comment by aigagror** [comment]
Can you explain why your PR yields 0.8 and the current example yields 0?

**Comment by zhangguanheng66** [comment]
Because `max_n` is set to 4, the metric will generate unigrams, bigrams, trigrams, and four-grams and the four-grams is empty for the original example.
With the original example, if you set `max_n` to `2` and `weights` to `[0.5] * 2`, you should be able to have non-zero result.
