### ISSUE TITLE
[HELP WANTED] Re-write datasets in torchtext

### ISSUE THREAD

**Issue by zhangguanheng66** [pytorch/text#742]
As mentioned in https://github.com/pytorch/text/issues/664, we are working on a new dataset abstraction. The new datasets will be more compatible with pytorch core library and capable of out-of-box libraries (like SentencePiece BPE). 

We have landed several datasets in `torchtext.experimental.datasets` folder to test the new abstraction. Now, we want some help from open-source community. Please sign up here and contribute PRs to re-write those datasets in torchtext. Those datasets in `torchtext/experimental/datasets/text_classification` should be some good examples to follow. Some datasets but not limited include:
- [x] Word language modeling datasets. Already in the experimental folder but need some update to the latest abstraction.
- [x] IMDB
- [x] Text classification datasets (AG_NEWS, SogouNews, DBpedia, YelpReviewPolarity, YelpReviewFull, YahooAnswers, AmazonReviewPolarity, AmazonReviewFull)
- [x] Translation
- [x] Question-answer datasets (e.g. SQuAD [here](https://github.com/zhangguanheng66/torchBERT/blob/e8cd8e5546d46d7e9788969bebb85933e0a91bf0/torchBERT/data.py#L135))
- [x] EnWik9, which's already good
- [x] Sequence tagging dataset in #805

Here is a checklist that you may consider to migrate a dataset:
1. Set up a IterableDataset with an iterator to read raw data [link](https://github.com/pytorch/text/blob/8833b970df08b1b0ec18b774cd0047c4160a9f84/torchtext/experimental/datasets/raw/text_classification.py#L89)
2. Cache out the raw dataset and create a transform pipeline [link](https://github.com/pytorch/text/blob/8833b970df08b1b0ec18b774cd0047c4160a9f84/torchtext/experimental/datasets/text_classification.py#L90)
    - pick up a tokenizer
    - generate the vocab object if not provided by users
    - attach tokenizer + vocab + totensor to the transform pipeline
3. Add unit tests [link](https://github.com/pytorch/text/blob/8833b970df08b1b0ec18b774cd0047c4160a9f84/test/data/test_builtin_datasets.py#L114)
    - check the total length of the dataset
    - check the content of the dataset

Free free to ping me and @cpuhrsch if you want to check some ideas for this. Thanks in advance.

**Comment by akurniawan** [comment]
hi @zhangguanheng66 I'm interested to work on the translation dataset migration

**Comment by zhangguanheng66** [comment]
@akurniawan Thanks. There is a draft branch [link](https://github.com/zhangguanheng66/text/blob/new_translation/torchtext/datasets/translation.py) I wrote 5 months ago and was close to finish. You may start from there and consider some changes in the latest abstraction.

**Comment by z-Runmin** [comment]
@zhangguanheng66 willing to work with the Word language modeling datasets.

**Comment by zhangguanheng66** [comment]
@zhangguanheng66 Thanks. Please follow the instructions above to re-write the datasets.

**Comment by akurniawan** [comment]
@zhangguanheng66 I tried to import sequence tagging dataset in #805 , seems not in the list you mentioned above, so I don't know if it's a priority for now. Let me know what you thought.

**Comment by Nayef211** [comment]
Closing as all datasets mentioned in this issue have now been added
