### ISSUE TITLE
torchtext.data.Field errors with "python3 -OO" but not "python3 -O"

### ISSUE THREAD

**Issue by paul-tqh-nguyen** [pytorch/text#752]
## 🐛 Bug
```python3 -OO -c "from torchtext import data; data.Field(tokenize = 'spacy', include_lengths = True, batch_first = True)"``` gets an error. 

```python3 -O -c "from torchtext import data; data.Field(tokenize = 'spacy', include_lengths = True, batch_first = True)"``` does not get an error. 

My understanding is that `-OO` merely removes docstrings (if this understanding is incorrect, please let me know). 

I believe these two should have the same behavior, but they do not. 

**To Reproduce**

I am able to reproduce the error like so:
<details>
pnguyen@pnguyenmachine:/tmp$ python3 -OO -c "from torchtext import data; data.Field(tokenize = 'spacy', include_lengths = True, batch_first = True)"
/home/pnguyen/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/pnguyen/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/pnguyen/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/pnguyen/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/pnguyen/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/pnguyen/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pnguyen/.local/lib/python3.7/site-packages/torchtext/data/field.py", line 163, in __init__
    self.tokenize = get_tokenizer(tokenize, tokenizer_language)
  File "/home/pnguyen/.local/lib/python3.7/site-packages/torchtext/data/utils.py", line 114, in get_tokenizer
    spacy = spacy.load(language)
  File "/home/pnguyen/.local/lib/python3.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/pnguyen/.local/lib/python3.7/site-packages/spacy/util.py", line 164, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/pnguyen/.local/lib/python3.7/site-packages/spacy/util.py", line 181, in load_model_from_link
    return cls.load(**overrides)
  File "/home/pnguyen/.local/lib/python3.7/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/pnguyen/.local/lib/python3.7/site-packages/spacy/util.py", line 228, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/pnguyen/.local/lib/python3.7/site-packages/spacy/util.py", line 199, in load_model_from_path
    nlp = cls(meta=meta, **overrides)
  File "/home/pnguyen/.local/lib/python3.7/site-packages/spacy/language.py", line 175, in __init__
    user_factories = util.get_entry_points(util.ENTRY_POINTS.factories)
  File "/home/pnguyen/.local/lib/python3.7/site-packages/spacy/util.py", line 286, in get_entry_points
    result[entry_point.name] = entry_point.load()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pnguyen/.local/lib/python3.7/site-packages/spacy_transformers/__init__.py", line 1, in <module>
    from .language import TransformersLanguage
  File "/home/pnguyen/.local/lib/python3.7/site-packages/spacy_transformers/language.py", line 5, in <module>
    from .util import is_special_token, pkg_meta, ATTRS, PIPES, LANG_FACTORY
  File "/home/pnguyen/.local/lib/python3.7/site-packages/spacy_transformers/util.py", line 2, in <module>
    import transformers
  File "/home/pnguyen/.local/lib/python3.7/site-packages/transformers/__init__.py", line 20, in <module>
    from .file_utils import (TRANSFORMERS_CACHE, PYTORCH_TRANSFORMERS_CACHE, PYTORCH_PRETRAINED_BERT_CACHE,
  File "/home/pnguyen/.local/lib/python3.7/site-packages/transformers/file_utils.py", line 29, in <module>
    import tensorflow as tf
  File "/home/pnguyen/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/pnguyen/.local/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/home/pnguyen/.local/lib/python3.7/site-packages/tensorflow/python/framework/framework_lib.py", line 52, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/home/pnguyen/.local/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 28, in <module>
    from tensorflow.python.framework import function
  File "/home/pnguyen/.local/lib/python3.7/site-packages/tensorflow/python/framework/function.py", line 36, in <module>
    from tensorflow.python.ops import array_ops
  File "/home/pnguyen/.local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 212, in <module>
    listdiff.__doc__ = gen_array_ops.list_diff.__doc__ + "\n" + listdiff.__doc__
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
pnguyen@pnguyenmachine:/tmp$ python3 -O -c "from torchtext import data; data.Field(tokenize = 'spacy', include_lengths = True, batch_first = True)"
/home/pnguyen/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/pnguyen/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/pnguyen/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/pnguyen/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/pnguyen/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/pnguyen/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/pnguyen/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/pnguyen/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/pnguyen/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/pnguyen/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/pnguyen/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/pnguyen/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
I0502 15:45:17.442192 140696908728128 file_utils.py:32] TensorFlow version 2.0.0-beta0 available.
I0502 15:45:17.442298 140696908728128 file_utils.py:39] PyTorch version 1.4.0 available.
I0502 15:45:22.589372 140696908728128 modeling_xlnet.py:194] Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
pnguyen@pnguyenmachine:/tmp$ 
</details>

Here's my environment information:
```

pnguyen@pnguyenmachine:/tmp$ wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
--2020-05-02 15:53:57--  https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.180.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.180.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12488 (12K) [text/plain]
Saving to: ‘collect_env.py’

collect_env.py                                     100%[==============================================================================================================>]  12.20K  --.-KB/s    in 0s      

2020-05-02 15:53:58 (55.1 MB/s) - ‘collect_env.py’ saved [12488/12488]

pnguyen@pnguyenmachine:/tmp$ python3 collect_env.py 
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 19.10
GCC version: (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1050
Nvidia driver version: 430.50
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.18.2
[pip3] torch==1.4.0
[pip3] torchcontrib==0.0.2
[pip3] torchtext==0.5.0
[pip3] torchvision==0.4.1
[conda] Could not collect
pnguyen@pnguyenmachine:/tmp$ 
```

**Comment by Nayef211** [comment]
Closing this since `torchtext.data.Field` has been deleted and is no longer available in the latest releases.
