### ISSUE TITLE
HTTP 301 when calling FastText()

### ISSUE THREAD

**Issue by TalitaAnthonio** [pytorch/text#754]
## 🐛 Bug
**Describe the bug**

Calling FastText() results to HTTP Error 301: Moved Permanently 

**To Reproduce**

```
from torchtext.vocab import FastText

embeddings = FastText()
```

**Expected behavior**
Making a call to FastText() should download the FastText embeddings. 

**Screenshots**
<img width="939" alt="Schermafbeelding 2020-05-05 om 16 01 14" src="https://user-images.githubusercontent.com/25078987/81074749-bdbc9b80-8ee9-11ea-9d6a-98aca69e41a0.png">

**Environment**

PyTorch version: 1.5.0+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.3
[pip3] torch==1.5.0+cu101
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.6.0+cu101
[conda] Could not collect

**Comment by zhangguanheng66** [comment]
It works on my side. Feel free to re-open it.

**Comment by TalitaAnthonio** [comment]
I now notice that this problem occurred because I was using Google Collaboratory. Sorry :)!

**Comment by tejas0809** [comment]
Any heads up on how to download it when running .ipynb on Google Colab?

**Comment by zhangguanheng66** [comment]
Can you check the version of torchtext and bump it up?

**Comment by tejas0809** [comment]
I upgraded it to 0.6.0 and it worked, thanks! Weird that Google Colab uses a default installation version 0.3.0 for torchtext.
