### ISSUE TITLE
Is the `.data` directory supposed to be auto-created when using the experimental datasets?

### ISSUE THREAD

**Issue by thvasilo** [pytorch/text#760]
I just tried running the following on a fresh instance:

```python
import torch
import torchtext

# import datasets
from torchtext.experimental.datasets import IMDB

SEED = 11

torch.manual_seed(SEED)
torch.backends.cudnn.deterministic = True

# use the default tokenizer
train_dataset, test_dataset = IMDB()
vocab = train_dataset.get_vocab()
```

and got the error `RuntimeError: Download directory .data does not exist. Did you create it?
`

I expected that the library would create the directory on its own, like it does for the `.vector_cache` directory. Is that not the case?

**Comment by zhangguanheng66** [comment]
Fixed by #797
