### ISSUE TITLE
[Feature Request] parameter for detokenization in fields

### ISSUE THREAD

**Issue by Deepblue129** [pytorch/text#82]
The ability to specify how to detokenize a `tensor` using the `field`.

Particularly this came up when using https://github.com/google/sentencepiece. Would like the ability to add subword units together as part of `field`. A counter part to tokenize. 

By default numericalize should have an opposite counter part to denumericalize.

**Comment by jekbradbury** [comment]
This is a good idea. I think I'm going to add a pure-Python sentencepiece-like tokenizer soon, and that will be a good opportunity to add the reverse counterparts to torchtext Fields' tokenize, numericalize, etc. methods.

**Comment by Deepblue129** [comment]
@jekbradbury Looking for one now because sentancepiece from Google is a pain. https://github.com/google/sentencepiece/issues/20

Do you know good Python librarie?

**Comment by jekbradbury** [comment]
no, there isn't much yet, except what's built into https://github.com/tensorflow/tensor2tensor. will hopefully work on this this weekend!

**Comment by Deepblue129** [comment]
@jekbradbury 
Cleaned up the tensor2tensor implementation: https://gist.github.com/Deepblue129/a51defb2dc9506945f58a165026d1a96

**Comment by jekbradbury** [comment]
Closed by #107; I think I oppose adding `reverse` to non-reversible Fields but I can see how it might be helpful in some cases.
