### ISSUE TITLE
Download link for torchtext==0.5.0 wheel is broken

### ISSUE THREAD

**Issue by pmeier** [pytorch/text#826]
## 🐛 Bug

Download link for `torchtext==0.5.0` wheel is broken.

**To Reproduce**

Try to download https://download.pytorch.org/whl/torchtext-0.5.0-py3-none-any.whl

**Additional context**

- Link was scraped from https://download.pytorch.org/whl/torch_stable.html
- For `torchtext==0.6.0` the link is working as expected: https://download.pytorch.org/whl/torchtext-0.6.0-py3-none-any.whl
- Installation of `torchtext==0.5.0` with pip is working as expected.

**Comment by zhangguanheng66** [comment]
@pmeier  Thanks for the report.

**Comment by akihironitta** [comment]
@zhangguanheng66 Hi, it seems that this problem still persists. Is there any plan to fix this issue?
```
ERROR: Could not install requirement torchtext==0.5 from https://download.pytorch.org/whl/torchtext-0.5.0-py3-none-any.whl (from -r ./requirements/./extra.txt (line 6)) because of HTTP error 403 Client Error: Forbidden for url: https://download.pytorch.org/whl/torchtext-0.5.0-py3-none-any.whl for URL https://download.pytorch.org/whl/torchtext-0.5.0-py3-none-any.whl (from https://download.pytorch.org/whl/cpu/torch_stable.html)
```

**Comment by zhangguanheng66** [comment]
cc @seemethere

**Comment by akihironitta** [comment]
@seemethere Pinging again just in case you missed the mention above.

**Comment by cpuhrsch** [comment]
cc @parmeet

**Comment by parmeet** [comment]
> @seemethere Pinging again just in case you missed the mention above.

@seemethere seems the problem still persists, any plan to fix the issue yet?

**Comment by seemethere** [comment]
For some reason it looks like the object in S3 was set to private. I've made it public, can you try it again?

Should be fixed now, can you try?

**Comment by parmeet** [comment]
Great, download link seems to work now. thanks @seemethere
