### ISSUE TITLE
Cannot select embedding size for experimental 6B and twitter.27B GloVe vectors

### ISSUE THREAD

**Issue by bentrevett** [pytorch/text#843]
GloVe embeddings for 6B and twitter.27B are available in multiple dimension sizes, however due to [this](https://github.com/pytorch/text/blob/master/torchtext/experimental/vectors.py#L139) line only the first file (vectors) in each of the extracted archive is loaded.

This is fine for the 420B and 840B GloVe vectors as they only contain one size of embeddings. However, for the 6B and twitter.27B  vectors there are four sizes of embeddings available, but only the first in each archive (the smallest size) is obtained from the new experimental vector class. 

It would be nice to be able to get the other 6B and twitter.27B vectors. Potentially a `dim` argument can be added to the `GloVe` function?

**Comment by zhangguanheng66** [comment]
@Nayef211 I remember we had some discussions about the dim argument when merging the glove vector PR.

**Comment by Nayef211** [comment]
> @Nayef211 I remember we had some discussions about the dim argument when merging the glove vector PR.

Yes I think I should have looked at this more carefully before. I'll create a PR to fix this!
