### ISSUE TITLE
Add interfaces to expose itos and stoi

### ISSUE THREAD

**Issue by kylegao91** [pytorch/text#85]
Maybe I didn't find it through the code, but it'd be nice to expose the token-index translation function through vocabulary interfaces.

**Comment by nelson-liu** [comment]
I might have misunderstood your point, but you can do `vocab.itos[index]` or `vocab.stoi[string]` (this is a dict, so you can use `.get` as well)

**Comment by kylegao91** [comment]
Yes that's what I'm doing now, but it's kind of against The Law of Demeter isn't it?
What I meant is adding two functions `vocab.itos()` and `vocab.stoi()`, which are just wrappers of the get method of the dicts.

**Comment by kylegao91** [comment]
That would be easier for writing docs as well:)

**Comment by Deepblue129** [comment]
Not sure what the difference is between a function and a property?

Both are thoroughly documented and supported by their API.

**Comment by kylegao91** [comment]
@Deepblue129 Maybe it's a personal tasting thing, I feel uncomfortable when I see there are 3 dots in `field.vocab.itos.get(idx)`.

**Comment by jekbradbury** [comment]
Well, `stoi` is a defaultdict and `itos` is a list, so you don’t have to use `get` -- these are intended to be raw Python built-in types to limit overhead.

**Comment by jekbradbury** [comment]
Will close for now; there are performance reasons for wanting to avoid the extra function call as well as Pythonic TIOOWTDI/DRY reasons.
