### ISSUE TITLE
Add loading pre-trained word2vec in bin file to vocab.Vectors

### ISSUE THREAD

**Issue by xdwang0726** [pytorch/text#857]
## 🚀 Feature
Right now, vocab.Vectors could only take .w2v(actually .txt) format pre-trained word vectors. Would it be possible to add loading pre-trained vectors in .bin format as well since .bin is the most commonly used for pre-trained format (i.e. google's pre-trained word2vec is in bin file). If the pre-trained .w2v file is very big, loading from .txt will take much longer than loading from .bin file (for my case, the same pre-trained word2vec in .bin file is ~12G and in .w2v file is 24G). Thank you!

**Comment by xdwang0726** [comment]
Never mind, I got it work!

**Comment by zhangguanheng66** [comment]
Could you share your solution here? @xdwang0726
