### ISSUE TITLE
Length of iterator fails in Python 2

### ISSUE THREAD

**Issue by kylegao91** [pytorch/text#86]
The division `len(dataset) / batch_size` will be cast to int in python2, so that `math.ceil` doesn't really work when `len(dataset)` is not a multiple of batch size.

**Comment by jekbradbury** [comment]
Yeah, this is a bug. The solution should be to wrap batch_size in `float`. Will fix.

**Comment by nelson-liu** [comment]
I think it's preferable to just `from __future__ import division`?

**Comment by jekbradbury** [comment]
Yes, thanks. I'm not very conversant in the Py2 world...
