### ISSUE TITLE
Why does torchtext.data.Batch.to() not exist?

### ISSUE THREAD

**Issue by awaelchli** [pytorch/text#861]
## ❓ Questions and Help

**Description**
I am wondering why the Batch class does not support moving the data to the device with a ".to()" call like it is possible for tensors and nn modules. Since the attribute of this Batch object are tensors, wouldn't it be straightforward to implement this convenience method?

Thanks

**Comment by zhangguanheng66** [comment]
Just a reminder that we will retire `Batch` class. The batched data from DataLoader can be moved to device.

**Comment by awaelchli** [comment]
Ok got it, makes sense not to add it if you drop that anyway. Thanks!
