### ISSUE TITLE
[Discussion] Object Design

### ISSUE THREAD

**Issue by Deepblue129** [pytorch/text#89]
**Background:** Looking into including a subword tokenizer. Been having a difficult time figuring out the right abstractions. The problem is a subword tokenizer unlike other tokenizers requires to define its own subword vocabulary.

Thinking about the above, I have a couple discussion questions.

**Field object vs Batch object abstraction**
The Field object defines instructions for dealing with batches of examples. Should the Batch object handle this responsibility instead? The Field object should only be defined for one example.

**Rename the Field object to TextEncoder**
Tensor2Tensor defines the functionality of converting text to tensors as a "TextEncoder". "TextEncoder" to me is a clearer object name than "Field". Should we rename the "Field" object?
 
Reference: https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/text_encoder.py

**Proper abstraction tokenizers and field objects**
The subword tokenizer requires a subword vocabulary. To achieve this, one would need to override the `build_vocab` method. To implement this, you'd need a separate subword field.

This is not consistent with the moses and spacy tokenizers that do not require separate fields.

**Comment by jekbradbury** [comment]
I'm working on this already; I think I can do it within the existing API but with additional methods on a ReversibleField subclass.

**Comment by jekbradbury** [comment]
An approach similar to this proposal was implemented in [AllenNLP's data library](https://github.com/allenai/allennlp/tree/master/allennlp/data) while we chose a less-breaking (but less general) approach in #107.
