### ISSUE TITLE
Request for configurable delimiter in Tabular Dataset

### ISSUE THREAD

**Issue by harshit-py** [pytorch/text#892]
## 🚀 Feature

Hi

Would like to have additional delimiters while reading flat files as Tabular Dataset. Current supported delimiters are ',' (default) and '\t'

**Motivation**

A lot of raw text data when preprocessed requires special delimiters like '@' or '^' while dumping them so as to not have ',' or even '\t' misinterpreted as a delimiter contained in the text.

**Pitch**

I see TabularDataset constructor accepts 'CSV', 'TSV' or 'JSON' for 'format'. This could be generalised as 'format' only accepting 'CSV' or 'JSON' and having additional kwarg 'delimiter' when 'format' == 'CSV'. This would then be passed to the csv.reader via utils.unicode_csv_reader function.

**Alternatives**

Currently only way around this is to manually change the delimiter in the raw file which might not always work.

**Additional context**

**Comment by JamesTrick** [comment]
Hi @harshit-py 

`TabularDataset` is essentially a wrapper around Python's CSV reader. As such, you can pass any arguments that `csv.reader` accepts to `TabularDataset`'s `csv_reader_params` parameter.

Using your example, some pseudo code would look like:

```python
data = torchtext.data.TabularDataset(path='test.csv', 
                                     format='csv',
                                     fields=[('id', None), ('text', torchtext.data.Field())],
                                     csv_reader_params={'delimiter': '@'}) # Note this extra step.
```

Hope this helps.

**Comment by harshit-py** [comment]
Hey that works thanks
