### ISSUE TITLE
Cannot use the batch with TypeError

### ISSUE THREAD

**Issue by kewellyoung** [pytorch/text#896]
## ❓ Questions and Help
I've load a dataset and try to generate  an iterator with torchtext. When I get the iterator and want to use it, there is TypeError as below

**Description**
Here is my code:

`from torchtext import data, vocab`

`class DataLoader():

    def __init__(self): 
        self.CONTENT = data.Field(sequential=True, 
                                  tokenize=lambda text:list(jieba.cut(text, cut_all=False)), 
                                  fix_length=150)
        self.LABEL = data.Field(sequential=False, use_vocab=False)
        self.field=[( 'text',self.CONTENT), ('label',self.LABEL)]        
        self.train_data, self.valid_data = data.TabularDataset.splits(path='',
                                        train = '%s_t_data.csv'%task,
                                        validation = '%s_v_data.csv'%task,
                                        format = 'csv',
                                        fields = self.field)        
        self.CONTENT.build_vocab(self.train_data)
    def load_data(self):
        batchsize = self.batchsize
        train_iterator = data.BucketIterator(self.train_data, batch_size=batchsize,
                                device='cuda',
                                sort_within_batch=False, shuffle=True,
                                 sort_key = lambda x:len(x.text))
        valid_iterator = data.Iterator(self.valid_data, batch_size=batchsize,
                        device='cuda', train=False,
                        shuffle=False, sort=False, sort_within_batch=False)
        return train_iterator, valid_iterator`

obj = DataLoader()
t,e = obj.load_data()
for batch in e: break

Then I got:

> ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-d67fe0c6e293> in <module>
----> 1 for batch in e:
      2     break

/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torchtext/data/iterator.py in __iter__(self)
    154                     else:
    155                         minibatch.sort(key=self.sort_key, reverse=True)
--> 156                 yield Batch(minibatch, self.dataset, self.device)
    157             if not self.repeat:
    158                 return

/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torchtext/data/batch.py in __init__(self, data, dataset, device)
     32                 if field is not None:
     33                     batch = [getattr(x, name) for x in data]
---> 34                     setattr(self, name, field.process(batch, device=device))
     35 
     36     @classmethod

/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torchtext/data/field.py in process(self, batch, device)
    234             and custom postprocessing Pipeline.
    235         """
--> 236         padded = self.pad(batch)
    237         tensor = self.numericalize(padded, device=device)
    238         return tensor

/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torchtext/data/field.py in pad(self, minibatch)
    269                     + list(x[-max_len:] if self.truncate_first else x[:max_len])
    270                     + ([] if self.eos_token is None else [self.eos_token])
--> 271                     + [self.pad_token] * max(0, max_len - len(x)))
    272             lengths.append(len(padded[-1]) - max(0, max_len - len(x)))
    273         if self.include_lengths:

TypeError: 'generator' object is not subscriptable

**Comment by zhangguanheng66** [comment]
Why not `torch.utils.data.DataLoader`?
