### ISSUE TITLE
How to combine train and test set for IMDB Dataset in Torchtext / Pytorch

### ISSUE THREAD

**Issue by EmreTokyuez** [pytorch/text#912]
## ❓ Questions and Help

I want to use the examples in the test set of the IMDB Sentiment Analysis Dataset for training, as I have built my own benchmark with which I will compare the performance of various Models (my Matura Thesis)

So after trying, I got the appending working and also managed ot split it, so that I have a validation set as well. The code is the following:

```
 from torchtext import datasets
    
    train_data, test_data = datasets.IMDB.splits(TEXT, LABEL)
    
    import random
    train_data, valid_data = train_data.split(random_state = random.seed(SEED))
    from torch.utils.data import ConcatDataset
    data_list = list()
    data_list.append(train_data)
    data_list.append(test_data)
    train_data = ConcatDataset(data_list)
    print(f'Number of validation examples: {len(valid_data)}')
    print(f'Number of training examples: {len(train_data)}')
```

And I get the following split (which is my goal):

```
Number of validation examples: 7500
Number of training examples: 42500
```

Now when I want to built the vocab with the following code, I get this error:

```
MAX_VOCAB_SIZE = 25_000 
LABEL.build_vocab(train_data)

TEXT.build_vocab(train_data, max_size = MAX_VOCAB_SIZE)
~\.conda\envs\matura-ml\lib\collections\__init__.py in update(*args, **kwds)
    654             else:
--> 655                 _count_elements(self, iterable)
    656         if kwds:

TypeError: 'Example' object is not iterable

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
 in 
      1 MAX_VOCAB_SIZE = 25_000
      2 
----> 3 TEXT.build_vocab(train_data, max_size = MAX_VOCAB_SIZE)
      4 LABEL.build_vocab(train_data)

~\.conda\envs\matura-ml\lib\site-packages\torchtext\data\field.py in build_vocab(self, *args, **kwargs)
    299                     counter.update(x)
    300                 except TypeError:
--> 301                     counter.update(chain.from_iterable(x))
    302         specials = list(OrderedDict.fromkeys(
    303             tok for tok in [self.unk_token, self.pad_token, self.init_token,

TypeError: 'Example' object is not iterable
```

How can I combine the train and test split in the correct way?

**Comment by zhangguanheng66** [comment]
If you switch to the new IMDb dataset in `torchtext.experimental`, you should be able to use `torch.utils.data.ConcatDataset` [here](https://pytorch.org/docs/stable/data.html#torch.utils.data.ConcatDataset).

**Comment by EmreTokyuez** [comment]
> 
> 
> If you switch to the new IMDb dataset in `torchtext.experimental`, you should be able to use `torch.utils.data.ConcatDataset` ([here](https://pytorch.org/docs/stable/data.html#torch.utils.data.ConcatDataset)).

Thank you very much, this worked!

How can I get the vocab tho?

I used

**Comment by zhangguanheng66** [comment]
> > If you switch to the new IMDb dataset in `torchtext.experimental`, you should be able to use `torch.utils.data.ConcatDataset` ([here](https://pytorch.org/docs/stable/data.html#torch.utils.data.ConcatDataset)).
> 
> Thank you very much, this worked!
> 
> How can I get the vocab tho?
> 
> I did the following:
> 
> ```
> [from torch.utils.data import ConcatDataset
> train_data = ConcatDataset([train_data, test_data])
> vocab = train_data.get_vocab()](url)
> ```
> 
> and got this:
> 
> ```
> 
> AttributeError                            Traceback (most recent call last)
>  in 
> ----> 1 vocab = train_data.get_vocab()
> 
> AttributeError: 'ConcatDataset' object has no attribute 'get_vocab'
> ```

You should `get_vocab` before sending datasets to `ConcatDataset`. The vocab objects in the two datasets are same.

**Comment by EmreTokyuez** [comment]
That worked, thank you very much!
