### ISSUE TITLE
TypeError: embedding(): argument 'indices' (position 2) must be Tensor, not list

### ISSUE THREAD

**Issue by EmreTokyuez** [pytorch/text#913]
## ❓ Questions and Help

I am following [this](https://github.com/bentrevett/pytorch-sentiment-analysis) tutorial for Sentiment Analysis and I am stuck on the [first tutorial](https://github.com/bentrevett/pytorch-sentiment-analysis/blob/master/1%20-%20Simple%20Sentiment%20Analysis.ipynb)

As I am combining the train and the test set for a valid comparison of different classifiers as mentioned in issue #912 , I was "forced" to use the new experimental dataset for the IMDB Review Dataset. Sadly, the tutorial I am trying to follow is using the legacy tools and thus, can't be used to combine the train and the test sets (as far as I am aware).

Using this code and building the same model as the tutorial, I get the error from the title:

```
from torchtext.experimental.datasets import IMDB
from torchtext.data.utils import get_tokenizer

tokenizer = get_tokenizer("spacy")

train_data, test_data = IMDB(tokenizer = tokenizer)
test_data, valid_data = torch.utils.data.random_split(test_data, [17500,7500], generator=torch.Generator().manual_seed(SEED))
vocab = train_data.get_vocab()
from torch.utils.data import ConcatDataset
train_dataset = ConcatDataset([train_data, test_data])

# Generate 8x8 batches (copied from github issue #651 
import torch
from torch.utils.data import DataLoader
def generate_rows(data):
	label_list = []
	txt_list = []
	for label, txt in data:
		label_list.append(label)
		txt_list.append(txt)
	return txt_list, label_list
dataloader = DataLoader(train_dataset, batch_size=64, num_workers=0,    collate_fn=generate_rows)
```
```
import  torch.nn as nn

class RNN(nn.Module):
    def __init__(self, input_dim, embedding_dim, hidden_dim, output_dim):

        super().__init__()
        
        self.embedding = nn.Embedding(input_dim, embedding_dim)

        self.rnn = nn.RNN(embedding_dim, hidden_dim)

        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self,txt):

        #txt = [sent len, batch size]

        embedded = self.embedding(txt)

        #embedded = [sent len, batch size, emb dim]

        output, hidden = self.rnn(embedded)

        #output = [sent len, batch size, hid dim]
        #hidden = [1, batch size, hid dim]
        
        assert torch.equal(output[-1,:,:], hidden.squeeze(0))
        
        return self.fc(hidden.squeeze(0))

INPUT_DIM = len(vocab)
EMBEDDING_DIM = 250
HIDDEN_DIM = 256
OUTPUT_DIM = 1

model = RNN(INPUT_DIM, EMBEDDING_DIM, HIDDEN_DIM, OUTPUT_DIM)

import torch.optim as optim 

optimizer = optim.SGD(model.parameters(), lr=1e-3)

criterion = nn.BCEWithLogitsLoss()



model = model.to('cuda:0')
criterion = criterion.to('cuda:0')

def  train(model, dataloader, optimizer, criterion):

    epoch_loss = 0
    epoch_acc = 0

    model.train()

    
    for txt, label in dataloader:
        optimizer.zero_grad()
                
        predictions = model(txt).squeeze(1)
        
        loss = criterion(predictions,label)
        
        acc = binary_accuracy(predictions,label)
        
        loss.backward()
        
        optimizer.step()
        
        epoch_loss += loss.item()
        epoch_acc += acc.item()

    return epoch_loss / len(dataloader), epoch_acc / len(dataloader)

def evaluate(model, dataloader, criterion):
    
    epoch_loss = 0
    epoch_acc = 0
    
    model.eval()
    
    with torch.no_grad():
    
        for txt, label in dataloader:


            predictions = model(txt).squeeze(1)
            
            loss = criterion(predictions, label)
            
            acc = binary_accuracy(predictions, label)

            epoch_loss += loss.item()
            epoch_acc += acc.item()
        
    return epoch_loss / len(dataloader), epoch_acc / len(dataloader)

import time

def epoch_time(start_time, end_time):
    elapsed_time = end_time - start_time
    elapsed_mins = int(elapsed_time / 60)
    elapsed_secs = int(elapsed_time - (elapsed_mins * 60))
    return elapsed_mins, elapsed_secs

dataloader_valid = DataLoader(valid_data, batch_size=64, num_workers=0,    collate_fn=generate_rows)

N_EPOCHS = 5

best_valid_loss = float('inf')

for epoch in range(N_EPOCHS):

    start_time = time.time()
    
    train_loss, train_acc = train(model, dataloader, optimizer, criterion)
    valid_loss, valid_acc = evaluate(model, dataloader_valid, criterion)
    
    end_time = time.time()

    epoch_mins, epoch_secs = epoch_time(start_time, end_time)
    
    if valid_loss < best_valid_loss:
        best_valid_loss = valid_loss
        torch.save(model.state_dict(), 'tut1-model.pt')
```

Using this code (sorry for the amount, I am a newbie in pytorch and want to make sure everything that could cause problems is in the post) I get the following error:

```
TypeError                                 Traceback (most recent call last)
 in 
      7     start_time = time.time()
      8 
----> 9     train_loss, train_acc = train(model, dataloader, optimizer, criterion)
     10     valid_loss, valid_acc = evaluate(model, dataloader_valid, criterion)
     11 

 in train(model, dataloader, optimizer, criterion)
     10         optimizer.zero_grad()
     11 
---> 12         predictions = model(txt).squeeze(1)
     13 
     14         loss = criterion(predictions,label)

~\.conda\envs\matura-ml\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

 in forward(self, txt)
     16         #txt = [sent len, batch size]
     17 
---> 18         embedded = self.embedding(txt)
     19 
     20         #embedded = [sent len, batch size, emb dim]

~\.conda\envs\matura-ml\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~\.conda\envs\matura-ml\lib\site-packages\torch\nn\modules\sparse.py in forward(self, input)
    124         return F.embedding(
    125             input, self.weight, self.padding_idx, self.max_norm,
--> 126             self.norm_type, self.scale_grad_by_freq, self.sparse)
    127 
    128     def extra_repr(self) -> str:

~\.conda\envs\matura-ml\lib\site-packages\torch\nn\functional.py in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
   1812         # remove once script supports set_grad_enabled
   1813         _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
-> 1814     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
   1815 
   1816 

TypeError: embedding(): argument 'indices' (position 2) must be Tensor, not list
```

How can I fix this? And are there any good "templates" or guides for the new dataset approach? I couldn't find anything and it's pretty hard as a newbie to convert tutorials with old code into the new code.

Also as a question, does the combination of the train and test set make sense? I trained a naive bayes and a logistic regression classifier using the whole dataset and tested it on reviews I sourced from IMDB and MAL so I thought I could increase the examples I have in my ML model combining the two.

**Comment by zhangguanheng66** [comment]
No, it's not a good practice to combine train and test dataset. For a ML pipeline, test dataset should never be touched during training. We have a classification tutorial with the new dataset ([here](https://pytorch.org/tutorials/beginner/text_sentiment_ngrams_tutorial.html)). I will also reach out to the original author and see if @bentrevett will update his tutorials with the new datasets.

**Comment by EmreTokyuez** [comment]
> No, it's not a good practice to combine train and test dataset. For a ML pipeline, test dataset should never be touched during training. We have a classification tutorial with the new dataset ([here](https://pytorch.org/tutorials/beginner/text_sentiment_ngrams_tutorial.html)). I will also reach out to the original author and see if @bentrevett will update his tutorials with the new datasets.
> 
> 

Thank you very much for asking the author and the advice! I'll do it the normal way with train and test set and use the test set as a measurement as well.

**Comment by bentrevett** [comment]
@EmreTokyuez I am currently updating the tutorials. They are located in the [experimental](https://github.com/bentrevett/pytorch-sentiment-analysis/tree/master/experimental). Will try and get the code for them all done this week - and try and get the RNN one done later today - with in-line explanations done the following week. Please feel free to submit and issue on the repo if you have any questions regarding them and I'll try to answer ASAP.

**Comment by EmreTokyuez** [comment]
> 
> 
> @EmreTokyuez I am currently updating the tutorials. They are located in the [experimental](https://github.com/bentrevett/pytorch-sentiment-analysis/tree/master/experimental). Will try and get the code for them all done this week - and try and get the RNN one done later today - with in-line explanations done the following week. Please feel free to submit and issue on the repo if you have any questions regarding them and I'll try to answer ASAP.

That's really nice of you! Don't stress out about it tho as I followed the first two and they worked fine with your implementation and performance was good. I am not planning on using the entire set anyway because I can use the results of the test set and compare it with other models.
