### ISSUE TITLE
arr = [[self.vocab.stoi[x] for x in ex] for ex in ar Error Message

### ISSUE THREAD

**Issue by manandey** [pytorch/text#937]
Hi,

While training my model in the final iteration I am facing this error: 
Can anyone help me in fixing this issue?

Trace:

KeyError                                  Traceback (most recent call last)
<ipython-input-23-0718dbde03e9> in <module>
      8 
      9     train_loss, train_acc = train(model, train_iter, optimizer, criterion)
---> 10     valid_loss, valid_acc = validate(model, dev_iter, criterion)
     11 
     12     end_time = time.time()

<ipython-input-21-e978bbe0d7de> in validate(model, iterator, criterion)
      3         n_correct, n_total, n_loss = 0, 0, 0
      4         with torch.no_grad():
----> 5             for batch_idx, batch in enumerate(dev_iter):
      6                 answer = model(batch)
      7                 loss = criterion(answer, batch.label)

~\AppData\Local\Continuum\anaconda2\envs\py36\lib\site-packages\torchtext\data\iterator.py in __iter__(self)
    160                     else:
    161                         minibatch.sort(key=self.sort_key, reverse=True)
--> 162                 yield Batch(minibatch, self.dataset, self.device)
    163             if not self.repeat:
    164                 return

~\AppData\Local\Continuum\anaconda2\envs\py36\lib\site-packages\torchtext\data\batch.py in __init__(self, data, dataset, device)
     34                 if field is not None:
     35                     batch = [getattr(x, name) for x in data]
---> 36                     setattr(self, name, field.process(batch, device=device))
     37 
     38     @classmethod

~\AppData\Local\Continuum\anaconda2\envs\py36\lib\site-packages\torchtext\data\field.py in process(self, batch, device)
    232         """
    233         padded = self.pad(batch)
--> 234         tensor = self.numericalize(padded, device=device)
    235         return tensor
    236 

~\AppData\Local\Continuum\anaconda2\envs\py36\lib\site-packages\torchtext\data\field.py in numericalize(self, arr, device)
    333                 arr = [[self.vocab.stoi[x] for x in ex] for ex in arr]
    334             else:
--> 335                 arr = [self.vocab.stoi[x] for x in arr]
    336 
    337             if self.postprocessing is not None:

~\AppData\Local\Continuum\anaconda2\envs\py36\lib\site-packages\torchtext\data\field.py in <listcomp>(.0)
    333                 arr = [[self.vocab.stoi[x] for x in ex] for ex in arr]
    334             else:
--> 335                 arr = [self.vocab.stoi[x] for x in arr]
    336 
    337             if self.postprocessing is not None:

KeyError: '-'

**Comment by zhangguanheng66** [comment]
Can you give more information so we can help you debug?
