### ISSUE TITLE
Cloning issue through pip

### ISSUE THREAD

**Issue by lRadha** [pytorch/text#959]
## ❓ Questions and Help
I tried to install this package as per described on [here](https://github.com/ZJULearning/ReDR), but get this error message:
**ERROR: Command errored out with exit status 1: git submodule update --init --recursive -q Check the logs for full command output.**
Please help.

**Comment by zhangguanheng66** [comment]
Do you install from source code or use our binary packages?

**Comment by lRadha** [comment]
What I'm tring to do is to install all the requirements given on [ReDR](https://github.com/ZJULearning/ReDR), in which to install pytorch/text given command is: `git+https://github.com/pytorch/text`, and I'm tring to install it through `pip`; the complete command is--

![image](https://user-images.githubusercontent.com/17251444/92082985-f2325c80-ede2-11ea-9f57-3bd13c1d92df.png)

I've changed `https` to `http` for the second time.

**Comment by zhangguanheng66** [comment]
Can you try "pip install torchtext"?

**Comment by zhangguanheng66** [comment]
> Can you try "pip install torchtext"?
