### ISSUE TITLE
Does Field support numerical features?

### ISSUE THREAD

**Issue by xuewei4d** [pytorch/text#96]
Hi,

I am processing a text dataset. Beside the text feature which could be processed by ```Field``` in a subclass of ```Dataset```, there is some float numbers which I would like to use with the text. So how could I create a subclass of ```data.Dataset``` with appropriate ```Field```?

Thanks,

**Comment by nelson-liu** [comment]
Perhaps this would help? https://github.com/pytorch/text/issues/78#issuecomment-316884668

**Comment by xuewei4d** [comment]
Thanks! It works.
