### ISSUE TITLE
i can't seem to install or use this python project from github

### ISSUE THREAD

**Issue by logax01** [pytorch/text#97]
Hello,
Can someone please help me install and use this python project i got from github on windows 10/server r2 ?? i really need it to complete my project, i already installed the latest python version and run setup.py but i can't seem to know what to do next. This is the first time i download a github project so please help me. I have no knowledge with python so bear with me.
Thank you,
https://github.com/cloudbase/coriolis

**Comment by nelson-liu** [comment]
you can also `pip install git+git://github.com/pytorch/text.git#egg=torchtext`. What errors are you getting?

**Comment by logax01** [comment]
thank you for answering,
it's not really about the errors, but about the procedure i should follow to make this project executable,

Can you please show me exactly what to do to make it install and execute properly step by step ?

it's my first time using github and python.

**Comment by nelson-liu** [comment]
to install, use the python pip package manager:
```
pip install git+git://github.com/pytorch/text.git#egg=torchtext
```

To use, you should do:

```
import torchtext
```

in your script. this project doesn't have any executables, but is instead used as a python package.

**Comment by jekbradbury** [comment]
Also `pip install torchtext` works now, though it doesn’t have the latest changes.

**Comment by nelson-liu** [comment]
🎉  fantastic to hear, should mention it in the README somewhere
