### ISSUE TITLE
Drop Last Batch in BucketItrator

### ISSUE THREAD

**Issue by manandey** [pytorch/text#970]
Hi,

While using BucketIterator, since my final batch is not having the predefined batch_size, since (no_of_samples%batch_size != 0), how to handle the case? Do we need to drop the last batch? If so how to drop it?

Is there anything available in texttorch, like "drop_last" parameter available in Data loader?

**Comment by zhangguanheng66** [comment]
We are switching to `DataLoader` and retiring `BucketIterator`. Any issues blocking you from `DataLoader`?
