### ISSUE TITLE
getting raw text from train_iterator

### ISSUE THREAD

**Issue by thak123** [pytorch/text#986]
## ❓ Questions and Help
Hi, I am trying to use the bucketiterator for my experiments. I need to get raw text from the dataset and pass it to a third party model as batch, which will numericalize it and pass it back. 

Is there a way in the torchtext where I can prevent numericalizing the text and receive fields as raw strings ?
**Description**

```
score =  Field(sequential=False)
text = Field(tokenize=tokenize_en, init_token='<sos>',
             eos_token='<eos>',
             lower=True, batch_first=False)
fields  = {
    'score':('score',score),
    "text":('text',text),
    }
train_data, valid_data, test_data = TabularDataset.splits(
    path="/content",
    train="train-new.json",
    test="test-new.json",
    validation="valid-new.json",
    format='json',
    fields=fields)
score.build_vocab(train_data)
train_iterator, valid_iterator, test_iterator = BucketIterator.splits((train_data, valid_data, test_data), batch_size=2,sort_key= lambda x:len(x.text), device=device)
```

`I get ValueError: too many dimensions 'str'
`when I perform 
`next(iter(train_iterator))`

PS> tokenize_en is spacy tokenizer .... can something be done about this ?

**Comment by zhangguanheng66** [comment]
We do have a few iterator to yield raw text strings from our datasets. See [here](https://github.com/pytorch/text/tree/master/torchtext/experimental/datasets/raw)

**Comment by thak123** [comment]
Yes got it to work. Thnx
